[package]
name = "contracts"
version = "0.3.0"
edition = "2024"
license = 'GPL-3.0'

[dependencies]
anyhow = "1.0"
async-trait = "0.1.89"
common = { path = "../common" }
chain_block = { path = "../../block" }
hex = "0.4.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tl_api = { version = "0.4.32", path = "../../tl/api" }
tracing = "0.1"
chain-rpc-client = { path = "../chain-rpc-client" }
fs2 = "0.4"
libc = "0.2"
ed25519-dalek = "2"
errno = "0.3"

[dev-dependencies]
tokio = "1.48.0"
tos_sandbox = { path = '../../sandbox' }
tos_vm = { path = '../../vm' }
ed25519-dalek = { version = "2", features = ["rand_core"] }
tempfile = "3"
