# Parent-owned lifecycle: a child failure (including FATAL_ERROR) cannot skip
# retention reporting, and every successful early return gets the same cleanup.
function(counter_run_fixture worker)
  if(NOT DEFINED BUILD_DIR OR NOT IS_DIRECTORY "${BUILD_DIR}")
    message(FATAL_ERROR "Counter fixture requires an existing BUILD_DIR")
  endif()
  get_filename_component(build_root "${BUILD_DIR}" REALPATH)
  if(NOT DEFINED COUNTER_MAX_FIXTURES)
    set(COUNTER_MAX_FIXTURES 16)
  endif()
  if(NOT COUNTER_MAX_FIXTURES MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "COUNTER_MAX_FIXTURES must be a positive integer")
  endif()
  # Admission is serialized across concurrent tests. Failed or interrupted runs
  # consume slots until explicitly inspected/removed; never evict a live fixture.
  file(LOCK "${build_root}/counter-fixture-lifecycle.lock" GUARD FUNCTION TIMEOUT 30)
  file(GLOB candidates LIST_DIRECTORIES TRUE "${build_root}/counter-integration-*")
  set(managed 0)
  foreach(candidate IN LISTS candidates)
    if(IS_DIRECTORY "${candidate}" AND EXISTS "${candidate}/.counter-managed-v1")
      math(EXPR managed "${managed} + 1")
    endif()
  endforeach()
  if(managed GREATER_EQUAL COUNTER_MAX_FIXTURES)
    message(FATAL_ERROR "Counter fixture retention/admission cap ${COUNTER_MAX_FIXTURES} reached in ${build_root}; inspect retained/incomplete fixtures before retrying")
  endif()
  string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
  set(fixture "${build_root}/counter-integration-${suffix}")
  if(EXISTS "${fixture}")
    message(FATAL_ERROR "Counter fixture already exists: ${fixture}")
  endif()
  file(MAKE_DIRECTORY "${fixture}")
  file(WRITE "${fixture}/.counter-managed-v1" "Managed fixture; absence of completed marker means active or interrupted.\n")
  file(LOCK "${build_root}/counter-fixture-lifecycle.lock" RELEASE)
  message(STATUS "Counter fixture active; retained if interrupted: ${fixture}")
  set(arguments "-DCOUNTER_FIXTURE_CHILD=ON" "-DCOUNTER_FIXTURE_PATH=${fixture}")
  foreach(name CREATE_STATE COLLATOR SOURCE_DIR BUILD_DIR NATIVE_SENDER IDLE_ONLY
      CROSS_DELIVERY SELF_DELIVERY ACTIVATION_MODE REJECT_CONFIG_PRESENCE
      COUNTER_LIFECYCLE_TEST_MODE)
    if(DEFINED ${name})
      list(APPEND arguments "-D${name}=${${name}}")
    endif()
  endforeach()
  execute_process(COMMAND "${CMAKE_COMMAND}" ${arguments} -P "${worker}"
    RESULT_VARIABLE result OUTPUT_VARIABLE child_out ERROR_VARIABLE child_err)
  file(WRITE "${fixture}/lifecycle.log" "${child_out}${child_err}")
  if(NOT "${child_out}${child_err}" STREQUAL "")
    message("${child_out}${child_err}")
  endif()
  if("${result}" STREQUAL "0")
    file(REMOVE_RECURSE "${fixture}")
    if(EXISTS "${fixture}")
      message(FATAL_ERROR "Successful Counter fixture could not be removed: ${fixture}")
    endif()
    message(STATUS "Counter fixture passed and removed: ${fixture}")
  else()
    file(WRITE "${fixture}/.completed-failure" "Child exit: ${result}\n")
    message(FATAL_ERROR "Counter fixture FAILED (${result}); retained for inspection: ${fixture}")
  endif()
endfunction()
