find_program(BASE64 base64)
if(NOT BASE64 OR NOT DEFINED CREATE_STATE OR NOT DEFINED COLLATOR OR NOT DEFINED SOURCE_DIR OR NOT DEFINED BUILD_DIR)
  message(FATAL_ERROR "Counter integration requires base64, CREATE_STATE, COLLATOR, SOURCE_DIR and BUILD_DIR")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(fixture "${BUILD_DIR}/counter-integration-${suffix}")
file(MAKE_DIRECTORY "${fixture}/db/static")
string(TIMESTAMP epoch "%s" UTC)
set(includes "${SOURCE_DIR}/crypto/fift/lib:${BUILD_DIR}/crypto/smartcont:${SOURCE_DIR}/crypto/smartcont")
foreach(script counter-shard-genesis counter-masterchain-genesis)
  set(script_path "${SOURCE_DIR}/test/${script}.fif")
  if(script STREQUAL "counter-masterchain-genesis" AND DEFINED ACTIVATION_MODE)
    file(READ "${script_path}" genesis)
    if(ACTIVATION_MODE STREQUAL "missing_capability")
      set(original "1024 or config.version!")
      set(replacement "0 or config.version!")
    elseif(ACTIVATION_MODE STREQUAL "old_version")
      set(original "15 capCreateStats")
      set(replacement "14 capCreateStats")
    else()
      message(FATAL_ERROR "Unknown activation test mode: ${ACTIVATION_MODE}")
    endif()
    string(FIND "${genesis}" "${original}" marker)
    if(marker EQUAL -1)
      message(FATAL_ERROR "Activation fixture no longer contains expected configuration marker")
    endif()
    string(REPLACE "${original}" "${replacement}" genesis "${genesis}")
    set(script_path "${fixture}/activation-genesis.fif")
    file(WRITE "${script_path}" "${genesis}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env "SOURCE_DATE_EPOCH=${epoch}"
    "${CREATE_STATE}" -I "${includes}" "${script_path}"
    WORKING_DIRECTORY "${fixture}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
  file(WRITE "${fixture}/${script}.log" "${output}${errors}")
  if(NOT status STREQUAL "0")
    message(FATAL_ERROR "Genesis generation failed (${status}); see ${fixture}/${script}.log")
  endif()
endforeach()
foreach(state zerostate basestate0 counter-state)
  file(SHA256 "${fixture}/${state}.boc" hash)
  string(TOUPPER "${hash}" hash)
  configure_file("${fixture}/${state}.boc" "${fixture}/db/static/${hash}" COPYONLY)
endforeach()
execute_process(COMMAND "${BASE64}" "${fixture}/zerostate.rhash"
  RESULT_VARIABLE root_status OUTPUT_VARIABLE root)
execute_process(COMMAND "${BASE64}" "${fixture}/zerostate.fhash"
  RESULT_VARIABLE file_status OUTPUT_VARIABLE hash)
if(NOT root_status STREQUAL "0" OR NOT file_status STREQUAL "0")
  message(FATAL_ERROR "Cannot encode fixture state identifiers")
endif()
string(STRIP "${root}" root)
string(STRIP "${hash}" hash)
file(WRITE "${fixture}/global.json" "{
  \"@type\":\"config.global\",
  \"dht\":{\"@type\":\"dht.config.global\",\"k\":6,\"a\":3,
    \"static_nodes\":{\"@type\":\"dht.nodes\",\"nodes\":[]}},
  \"validator\":{\"@type\":\"validator.config.global\",\"zero_state\":{
    \"workchain\":-1,\"shard\":-9223372036854775808,\"seqno\":0,
    \"root_hash\":\"${root}\",\"file_hash\":\"${hash}\"},\"hardforks\":[]}}
")

set(node_db "${fixture}/db")
function(run_node label expected_status expected_text)
  execute_process(COMMAND "${COLLATOR}" -C "${fixture}/global.json" -D "${node_db}" ${ARGN}
    WORKING_DIRECTORY "${fixture}" RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 30)
  set(log "${output}${errors}")
  file(WRITE "${fixture}/${label}.log" "${log}")
  if(NOT status STREQUAL "${expected_status}")
    message(FATAL_ERROR "${label}: exit ${status}, expected ${expected_status}; see ${fixture}/${label}.log")
  endif()
  string(FIND "${log}" "${expected_text}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "${label}: missing '${expected_text}'; see ${fixture}/${label}.log")
  endif()
  if(expected_status STREQUAL "0")
    string(REGEX MATCH "= (\\([0-9-]+,8000000000000000,[0-9]+\\):[0-9A-F]+:[0-9A-F]+) saved to disk" match "${log}")
    if(NOT match)
      message(FATAL_ERROR "${label}: no persisted block identifier; see ${fixture}/${label}.log")
    endif()
    set(last_block "${CMAKE_MATCH_1}" PARENT_SCOPE)
  else()
    string(FIND "${log}" "saved to disk" saved)
    if(NOT saved EQUAL -1)
      message(FATAL_ERROR "${label}: rejected candidate was saved")
    endif()
  endif()
endfunction()

function(require_log label expected)
  file(READ "${fixture}/${label}.log" log)
  string(FIND "${log}" "${expected}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "${label}: missing '${expected}'; see ${fixture}/${label}.log")
  endif()
endfunction()

function(require_batch_after_dispatch label)
  file(READ "${fixture}/${label}.log" log)
  string(REGEX MATCH "delivering deferred message[^\n]*emitted_lt=([0-9]+)" match "${log}")
  if(NOT match)
    message(FATAL_ERROR "${label}: missing deferred emission LT")
  endif()
  set(emitted "${CMAKE_MATCH_1}")
  string(REGEX MATCH "staging workchain batch at lt=([0-9]+)" match "${log}")
  if(NOT match OR NOT CMAKE_MATCH_1 GREATER emitted)
    message(FATAL_ERROR "${label}: batch LT must follow deferred emission LT ${emitted}")
  endif()
endfunction()

run_node(bootstrap 0 "saved to disk" -w -1)
file(COPY "${fixture}/db" DESTINATION "${fixture}/peer")
file(READ "${fixture}/counter-state.rhash" counter_root HEX)
file(READ "${fixture}/counter-state.fhash" counter_hash HEX)
set(previous "(2,8000000000000000,0):${counter_root}:${counter_hash}")
set(zero_block "${previous}")
if(DEFINED SELF_DELIVERY)
  run_node(self_send 0 "saved to disk" --counter-self-send-increment 2 -w 2 -T "${previous}")
  require_log(self_send "from_prev_blk:1000ng to_next_blk:600ng imported:0ng exported:334ng fees_collected:66ng")
  set(previous "${last_block}")
  set(self_previous "${previous}")
  file(COPY "${fixture}/db" DESTINATION "${fixture}/self-peer")
  run_node(self_receive1 0 "saved to disk" --counter-increment 0 -w 2 -T "${previous}"
    --export-candidate "${fixture}/self-receive.candidate")
  require_log(self_receive1 "from_prev_blk:600ng to_next_blk:700ng imported:334ng exported:167ng fees_collected:67ng")
  require_log(self_receive1 "outbound message queue size: 1 -> 1")
  set(previous "${last_block}")
  set(node_db "${fixture}/self-peer/db")
  run_node(self_import 0 "validating imported candidate" --counter-increment 0 -w 2 -T "${self_previous}"
    --import-candidate "${fixture}/self-receive.candidate")
  if(NOT last_block STREQUAL previous)
    message(FATAL_ERROR "Independent peer imported a different incoming batch")
  endif()
  set(node_db "${fixture}/db")
  run_node(self_receive2 0 "saved to disk" --counter-increment 0 -w 2 -T "${previous}")
  require_log(self_receive2 "from_prev_blk:700ng to_next_blk:800ng imported:167ng exported:0ng fees_collected:67ng")
  require_log(self_receive2 "outbound message queue size: 1 -> 0")
  set(previous "${last_block}")
  run_node(self_empty 0 "saved to disk" --counter-increment 0 -w 2 -T "${previous}")
  require_log(self_empty "from_prev_blk:800ng to_next_blk:800ng imported:0ng exported:0ng fees_collected:0ng")
  return()
endif()
if(DEFINED ACTIVATION_MODE)
  run_node(unactivated 2 "block transition is not activated by global version and capability"
    --counter-send-increment 2 -w 2 -T "${previous}")
  file(READ "${fixture}/unactivated.log" rejected_log)
  string(FIND "${rejected_log}" "staging workchain batch at lt=" staged)
  if(NOT staged EQUAL -1)
    message(FATAL_ERROR "Unactivated workchain reached batch staging")
  endif()
  return()
endif()
run_node(counter1 0 "(2,8000000000000000,1)" --counter-send-increment 2 -w 2 -T "${previous}"
  --export-candidate "${fixture}/counter1.candidate")
require_log(counter1 "from_prev_blk:1000ng to_next_blk:600ng imported:0ng exported:334ng fees_collected:66ng")
require_log(counter1 "outbound message queue size: 0 -> 1")
require_log(counter1 "was deferred")
set(previous "${last_block}")
set(node_db "${fixture}/peer/db")
run_node(wrong_import_shard 2 "imported candidate differs from requested shard"
  -w 0 --import-candidate "${fixture}/counter1.candidate")
file(WRITE "${fixture}/invalid.candidate" "invalid archive")
run_node(invalid_import 2 "cannot decode imported candidate" --counter-increment 0 -w 2 -T "${zero_block}"
  --import-candidate "${fixture}/invalid.candidate")
run_node(import1 0 "validating imported candidate" --counter-increment 0 -w 2 -T "${zero_block}"
  --import-candidate "${fixture}/counter1.candidate")
if(NOT last_block STREQUAL previous)
  message(FATAL_ERROR "Peer imported a different block: ${last_block} != ${previous}")
endif()
# Fresh processes reopen the same database. These adjacent limits prove the
# restored value is exactly 42, without trusting a private cache or an RPC claim.
run_node(overflow 2 "counter overflow" --counter-increment 18446744073709551574 -w 2 -T "${previous}")
run_node(counter2_send 0 "(2,8000000000000000,2)" --counter-send-increment 0 -w 2 -T "${previous}")
require_log(counter2_send "from_prev_blk:600ng to_next_blk:200ng imported:167ng exported:501ng fees_collected:66ng")
require_log(counter2_send "outbound message queue size: 1 -> 3")
require_log(counter2_send "delivering deferred message")
require_batch_after_dispatch(counter2_send)
set(previous "${last_block}")
# Four messages have consumed 800 of the 1000 operating atoms. The next pair
# must reject atomically, including the first message that could still be paid.
run_node(insufficient_budget 2 "batch native message send failed" --counter-send-increment 0 -w 2 -T "${previous}")
run_node(counter3 0 "(2,8000000000000000,3)" --counter-increment 18446744073709551573 -w 2 -T "${previous}"
  -s "${fixture}/counter-top-")
require_log(counter3 "from_prev_blk:200ng to_next_blk:200ng imported:167ng exported:167ng fees_collected:0ng")
require_log(counter3 "outbound message queue size: 3 -> 4")
require_log(counter3 "delivering deferred message")
require_batch_after_dispatch(counter3)
set(counter_tip "${last_block}")
run_node(max_overflow 2 "counter overflow" --counter-increment 1 -w 2 -T "${last_block}")
if(NOT EXISTS "${fixture}/counter-top-1.boc")
  message(FATAL_ERROR "Counter top shard description was not saved")
endif()
run_node(register_counter 0 "saved to disk" -w -1 -M "${fixture}/counter-top-1.boc")
require_log(register_counter "updated shard block configuration")
run_node(native_receive 0 "(0,8000000000000000,1)" -w 0 -s "${fixture}/native-top-")
require_log(native_receive "from_prev_blk:0ng to_next_blk:400ng imported:668ng exported:0ng fees_collected:268ng")
require_log(native_receive "outbound message queue size: 0 -> 0")
if(NOT EXISTS "${fixture}/native-top-1.boc")
  message(FATAL_ERROR "Native top shard description was not saved")
endif()
run_node(register_native 0 "saved to disk" -w -1 -M "${fixture}/native-top-1.boc")
require_log(register_native "updated shard block configuration")
require_log(register_native "fees_collected:268ng fees_imported:268ng")
run_node(counter_cleanup 0 "(2,8000000000000000,4)" --counter-increment 0 -w 2 -T "${counter_tip}")
require_log(counter_cleanup "outbound message queue size: 4 -> 0")
require_log(counter_cleanup "from_prev_blk:200ng to_next_blk:200ng imported:0ng exported:0ng fees_collected:0ng")
message(STATUS "Counter collate/validate/restart checks passed; artifacts: ${fixture}")
