if(COUNTER_FIXTURE_CHILD)
  file(WRITE "${COUNTER_FIXTURE_PATH}/probe.log" "worker reached\n")
  if(COUNTER_LIFECYCLE_TEST_MODE STREQUAL "fail")
    message(FATAL_ERROR "intentional lifecycle test failure")
  endif()
  # Exercise a successful early return, not only falling through the last line.
  return()
elseif(DEFINED COUNTER_LIFECYCLE_TEST_MODE)
  include("${CMAKE_CURRENT_LIST_DIR}/counter-fixture-lifecycle.cmake")
  counter_run_fixture("${CMAKE_CURRENT_LIST_FILE}")
  return()
endif()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${BUILD_DIR}/counter-lifecycle-test-${suffix}")
file(MAKE_DIRECTORY "${root}")
function(run mode expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DBUILD_DIR=${root}"
    -DCOUNTER_MAX_FIXTURES=2 "-DCOUNTER_LIFECYCLE_TEST_MODE=${mode}"
    -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(expected STREQUAL "pass")
    if(NOT "${result}" STREQUAL "0" OR NOT "${out}${err}" MATCHES "passed and removed")
      message(FATAL_ERROR "Success lifecycle failed: ${out}${err}; artifacts ${root}")
    endif()
  elseif("${result}" STREQUAL "0" OR NOT "${out}${err}" MATCHES "${expected}")
    message(FATAL_ERROR "Failure lifecycle was not observable: ${out}${err}; artifacts ${root}")
  endif()
endfunction()
run(pass pass)
file(GLOB fixtures "${root}/counter-integration-*")
if(fixtures)
  message(FATAL_ERROR "Successful early return leaked fixture: ${fixtures}")
endif()
run(fail "retained for inspection")
run(fail "retained for inspection")
file(GLOB fixtures "${root}/counter-integration-*")
list(LENGTH fixtures count)
if(NOT count EQUAL 2)
  message(FATAL_ERROR "Expected two retained failures in ${root}")
endif()
foreach(fixture IN LISTS fixtures)
  if(NOT EXISTS "${fixture}/.completed-failure" OR NOT EXISTS "${fixture}/probe.log")
    message(FATAL_ERROR "Failure diagnostics lost: ${fixture}")
  endif()
  file(READ "${fixture}/lifecycle.log" output)
  if(NOT output MATCHES "intentional lifecycle test failure")
    message(FATAL_ERROR "Child error output was not retained: ${fixture}")
  endif()
endforeach()
# Incomplete/active fixtures must count toward the cap and must not be evicted.
list(GET fixtures 0 incomplete)
file(REMOVE "${incomplete}/.completed-failure")
run(pass "retention/admission cap 2 reached")
file(GLOB after "${root}/counter-integration-*")
if(NOT "${after}" STREQUAL "${fixtures}")
  message(FATAL_ERROR "Cap evicted or allocated a fixture: ${root}")
endif()
foreach(fixture IN LISTS fixtures)
  file(READ "${fixture}/probe.log" log)
  if(NOT log STREQUAL "worker reached\n")
    message(FATAL_ERROR "Cap damaged diagnostics: ${fixture}")
  endif()
endforeach()
file(REMOVE_RECURSE "${root}")
message(STATUS "Counter success cleanup, failure retention and admission cap passed")
