foreach(required CREATE_STATE SOURCE_DIR BUILD_DIR)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
file(READ "${SOURCE_DIR}/test/counter-masterchain-genesis.fif" source)
string(FIND "${source}" "0 mkemptyShardState" boundary)
if(boundary LESS 0)
  message(FATAL_ERROR "Cannot locate genesis pre-state boundary")
endif()
string(SUBSTRING "${source}" 0 ${boundary} prefix)
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef nonce)
set(fixture "${BUILD_DIR}/counter-domain-${nonce}")
file(MAKE_DIRECTORY "${fixture}")
foreach(domain -23901 1 -239 -23902)
  string(REPLACE "-23901 setglobalid" "${domain} setglobalid" script "${prefix}")
  file(WRITE "${fixture}/case.fif" "${script}\nB{01} \"reached\" B>file\n")
  execute_process(COMMAND "${CREATE_STATE}" -I "${SOURCE_DIR}/crypto/fift/lib:${BUILD_DIR}/crypto/smartcont:${SOURCE_DIR}/crypto/smartcont" "${fixture}/case.fif"
    WORKING_DIRECTORY "${fixture}" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
  if(domain EQUAL -23901)
    if(NOT result EQUAL 0 OR NOT EXISTS "${fixture}/reached")
      message(FATAL_ERROR "Valid test domain did not reach state boundary; retained ${fixture}: ${errors}")
    endif()
    file(REMOVE "${fixture}/reached")
  else()
    if(EXISTS "${fixture}/reached" OR result EQUAL 0)
      message(FATAL_ERROR "Non-test domain reached genesis state creation; retained ${fixture}")
    endif()
  endif()
endforeach()
file(REMOVE_RECURSE "${fixture}")
message(STATUS "Public-key genesis domain guard verified before state creation")
