[workspace]
members = [
    'adnl',
    'assembler',
    'block',
    'block-json',
    'emulator',
    'executor',
    'lockfree',
    'node-control/commands',
    'node-control/common',
    'node-control/contracts',
    'node-control/control-client',
    'node-control/elections',
    'node-control/nodectl',
    'node-control/service',
    'node-control/chain-rpc-client',
    'secrets-vault',
    'tl/api',
    'toscenter-rs',
    'vm',
    'sandbox',
]
resolver = '2'

[profile.bench]
debug = true

#Uncomment for profiling
#[profile.release]
#debug = 1
