[package]
name = "tos-uno-crypto-prototype"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
nonempty = "=0.11.0"
orchard = { git = "https://github.com/zcash/orchard.git", rev = "29d1d55db62153dcaeef8ef631c8991c53ed1248", default-features = false, features = ["circuit", "multicore", "std"] }

[workspace]

[build-dependencies]
cbindgen = { version = "=0.29.0", default-features = false }

[dev-dependencies]
blake2b_simd = "=1.0.5"
incrementalmerkletree = "=0.8.2"
rand = "=0.8.8"
