function(uno_probe_cargo source available_out reason_out cargo_out)
  if (CMAKE_CROSSCOMPILING)
    set(_uno_cargo_reason "cross-compiled builds are unsupported; a native Linux build is required")
  elseif (NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(_uno_cargo_reason "${CMAKE_SYSTEM_NAME} is unsupported; a native Linux build is required")
  else()
    unset(_uno_cargo CACHE)
    unset(_uno_cargo)
    find_program(_uno_cargo cargo)
    if (NOT _uno_cargo)
      set(_uno_cargo_reason "cargo was not found in PATH")
    else()
      execute_process(COMMAND "${CMAKE_COMMAND}" -E env "CARGO_NET_OFFLINE=true" "${_uno_cargo}" --version
        WORKING_DIRECTORY "${source}" RESULT_VARIABLE _uno_cargo_status
        OUTPUT_VARIABLE _uno_cargo_version ERROR_VARIABLE _uno_cargo_diagnostic
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_STRIP_TRAILING_WHITESPACE)
      if (NOT "${_uno_cargo_status}" STREQUAL "0")
        set(_uno_cargo_reason "cargo at '${_uno_cargo}' could not report its version (exit ${_uno_cargo_status}): ${_uno_cargo_diagnostic}")
      elseif (NOT _uno_cargo_version MATCHES "^cargo 1\\.97\\.1 ")
        set(_uno_cargo_reason "cargo 1.97.1 is required, found '${_uno_cargo_version}' at '${_uno_cargo}'")
      else()
        set(${available_out} TRUE PARENT_SCOPE)
        set(${reason_out} "" PARENT_SCOPE)
        set(${cargo_out} "${_uno_cargo}" PARENT_SCOPE)
        return()
      endif()
    endif()
  endif()

  set(${available_out} FALSE PARENT_SCOPE)
  set(${reason_out} "${_uno_cargo_reason}" PARENT_SCOPE)
  set(${cargo_out} "" PARENT_SCOPE)
endfunction()

function(uno_require_cargo source cargo_out)
  uno_probe_cargo("${source}" _uno_cargo_available _uno_cargo_reason _uno_cargo)
  if (NOT _uno_cargo_available)
    message(FATAL_ERROR "UNO crypto prototype tests require the pinned Rust toolchain: ${_uno_cargo_reason}")
  endif()
  set(${cargo_out} "${_uno_cargo}" PARENT_SCOPE)
endfunction()
