/*
 * Copyright (C) 2026-2026 TOS Blockchain Teams.
 *
 * Licensed under the GNU General Public License v3.0.
 * See the LICENSE file in the root of this repository.
 */
//! Poseidon2 t=8 over BLS12-381 `Fr`, outside the constraint system.
//!
//! This is the witness-generating half of the gadget in
//! [`crate::gadgets::poseidon2`]. Both halves are written against profile
//! sections 1.2 and 1.3, and both are checked against the known-answer vectors
//! generated by the pinned upstream reference. The out-of-circuit half exists
//! so that a wrong value can be found without a constraint system in the way;
//! it is not evidence on its own, because a gadget can compute a right value
//! while constraining nothing.

use ark_ff::AdditiveGroup;

use crate::field::Fr;
use crate::params::{params, ROUNDS_F_BEGINNING, ROUNDS_P, ROUNDS_TOTAL, STATE_WIDTH};

/// `x^5`, the frozen S-box.
fn sbox(x: Fr) -> Fr {
    let squared = x * x;
    let quartic = squared * squared;
    quartic * x
}

/// The cheap 4x4 MDS block, applied to each quarter of the state.
fn matmul_m4(x: &mut [Fr]) {
    let t0 = x[0] + x[1];
    let t1 = x[2] + x[3];
    let t2 = x[1].double() + t1;
    let t3 = x[3].double() + t0;
    let t4 = t1.double().double() + t3;
    let t5 = t0.double().double() + t2;
    let t6 = t3 + t5;
    let t7 = t2 + t4;
    x[0] = t6;
    x[1] = t5;
    x[2] = t7;
    x[3] = t4;
}

/// The external (full-round) linear layer for t=8.
fn matmul_external(state: &mut [Fr; STATE_WIDTH]) {
    let (first, second) = state.split_at_mut(4);
    matmul_m4(first);
    matmul_m4(second);
    let mut stored = [Fr::from(0u64); 4];
    for (lane, slot) in stored.iter_mut().enumerate() {
        *slot = state[lane] + state[4 + lane];
    }
    for (lane, slot) in state.iter_mut().enumerate() {
        *slot += stored[lane % 4];
    }
}

/// The internal (partial-round) linear layer. It reads only the diagonal of the
/// internal matrix, which is why the rest of that matrix is held to the
/// manifest digest and not to any output.
fn matmul_internal(state: &mut [Fr; STATE_WIDTH]) {
    let diag = &params().diag;
    let mut sum = state[0];
    for value in state.iter().skip(1) {
        sum += value;
    }
    for (lane, slot) in state.iter_mut().enumerate() {
        *slot = *slot * diag[lane] + sum;
    }
}

/// The frozen permutation: `POSEIDON2_PERM8` of profile section 1.3.
pub fn permute(input: &[Fr; STATE_WIDTH]) -> [Fr; STATE_WIDTH] {
    let constants = &params().round_constants;
    let mut state = *input;

    matmul_external(&mut state);

    for round in constants.iter().take(ROUNDS_F_BEGINNING) {
        for (lane, slot) in state.iter_mut().enumerate() {
            *slot = sbox(*slot + round[lane]);
        }
        matmul_external(&mut state);
    }

    let partial_end = ROUNDS_F_BEGINNING.saturating_add(ROUNDS_P);
    for round in constants.iter().take(partial_end).skip(ROUNDS_F_BEGINNING) {
        state[0] = sbox(state[0] + round[0]);
        matmul_internal(&mut state);
    }

    for round in constants.iter().take(ROUNDS_TOTAL).skip(partial_end) {
        for (lane, slot) in state.iter_mut().enumerate() {
            *slot = sbox(*slot + round[lane]);
        }
        matmul_external(&mut state);
    }

    state
}

/// `POSEIDON2_HASH7` of profile section 1.3: absorb the domain and seven
/// inputs, permute, take lane zero.
pub fn hash7(domain: Fr, inputs: &[Fr; 7]) -> Fr {
    let mut state = [Fr::from(0u64); STATE_WIDTH];
    state[0] = domain;
    for (slot, value) in state.iter_mut().skip(1).zip(inputs.iter()) {
        *slot = *value;
    }
    permute(&state)[0]
}
