#ifndef UNO_PLONKY3_FFI_H
#define UNO_PLONKY3_FFI_H

#pragma once

/* Auto-generated by cbindgen from uno/plonky3-ffi/src/lib.rs. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Maximum spend count (§4.1 ConfigParam 84).
#define MAX_SPENDS 4

// Maximum output count (§4.1 ConfigParam 84).
#define MAX_OUTPUTS 4

// Minimum spend count — at least one spend is required for a Transfer.
#define MIN_SPENDS 1

// Minimum output count — at least one output is required.
#define MIN_OUTPUTS 1

// Width of the narrow Poseidon2 permutation (Merkle / IvkCm / Nf).
#define POSEIDON2_WIDTH 8

// Width of the wide Poseidon2 permutation (claim 2 / claim 6 note-
// commitment absorb; §3.2). The 15-fe input (`domain_tag, d, pk_d,
// ivk_commitment, value, rcm`) needs a width-16 sponge.
#define POSEIDON2_WIDTH_16 16

// S-box degree (α=7 on Goldilocks).
#define POSEIDON2_SBOX_DEGREE 7

// Number of committed intermediate registers per S-box at degree 7.
#define POSEIDON2_SBOX_REGISTERS 1

// Number of full rounds per half. Total `R_F = 8`. Same for widths 8 / 16.
#define POSEIDON2_HALF_FULL_ROUNDS GOLDILOCKS_POSEIDON2_HALF_FULL_ROUNDS

// Number of partial rounds. `R_P = 22` for width-8 Goldilocks (§16 #42).
#define POSEIDON2_PARTIAL_ROUNDS GOLDILOCKS_POSEIDON2_PARTIAL_ROUNDS_8

// Number of partial rounds for width-16 Goldilocks. Also 22.
#define POSEIDON2_PARTIAL_ROUNDS_16 GOLDILOCKS_POSEIDON2_PARTIAL_ROUNDS_16

// Domain tag for the IVK-commitment Poseidon2.
#define TAG_IVK_CM 105111591102868323

// Domain tag for the note-commitment Poseidon2.
#define TAG_CM 105111591001617969

// Domain tag for the nullifier Poseidon2.
#define TAG_NF 105111591185708593

// Depth of the note-commitment Merkle tree (§2.3 / §10.2 ConfigParam 84).
#define MERKLE_DEPTH 32

// Global (tx-level) columns:
//
// ```text
//   [fee]                                            (1 col)
//   [GS_ROW_SEL[0..MERKLE_DEPTH]]                    (32 cols, one-hot bank)
//   [shared Cm/OutCm Poseidon2-16 block]             (316 cols, claim 2/6)
//   [shared IvkCm/Nf Poseidon2-8 block]              (180 cols, claim 3/4)
// ```
//
// The 32 row selectors are the AIR's clock for all three shared
// Poseidon2 blocks: `GS_ROW_SEL[k]` is `1` exactly on trace row `k` for
// `k ∈ 0..32`, `0` on rows 32..63. Step 1 (K-air-col-share) introduced
// them for the Merkle row-loop; step 2 (K-air-col-step2) reuses the
// same bank for the Cm/IvkCm/Nf row-loops — no extra selector columns.
#define GLOBAL_COLS (((1 + MERKLE_DEPTH) + POSEIDON2_COLS_PER_INSTANCE_16) + POSEIDON2_COLS_PER_INSTANCE)

// Width in bits of the bit-decomposition range check for `value_i` /
// `value_j` (§4.2 claims 5 & 7). Each value is committed as 64 bit
// columns so the AIR constrains `value < 2^64`; since
// `p_Goldilocks = 2^64 − 2^32 + 1`, the additional 32 high-bit
// combinations in `[2^64 − 2^32 + 1, 2^64)` are unreachable by a single
// field element, so the bit decomposition is exact on canonical inputs.
#define VALUE_BITS 64

// Per-spend proxy columns: leaf, d, value, ivk, ivk_commitment_claim,
// pk_d, rcm, nk, pos (9 leading fields), plus 32 path-bit proxies, 32
// sibling-hash proxies for the 32-level Merkle path (§2.3), and
// VALUE_BITS bit columns for the explicit u64 range-check on `value_i`
// (§4.2 claim 5).
#define SPEND_PROXY_COLS (((9 + MERKLE_DEPTH) + MERKLE_DEPTH) + VALUE_BITS)

// Per-output proxy columns: cm_claim, d, pk_d, ivk_commitment, value,
// rcm (6 leading fields), plus VALUE_BITS bit columns for the explicit
// u64 range-check on `value_j` (§4.2 claim 7).
#define OUTPUT_PROXY_COLS (6 + VALUE_BITS)

// Narrow (width-8) Poseidon2 instances per spend after K-air-col-step2:
// only the shared-Merkle slot remains. IvkCm + Nf are folded into a
// single globally-shared row-looped block on rows 0..7.
#define POSEIDON2_NARROW_PER_SPEND 1

// Per-spend variable columns that are NOT constant across rows (i.e., not
// included in the transition "proxies are constant" equality). Currently:
// `S_CURRENT` (running Merkle digest).
#define SPEND_VAR_COLS 1

// Wide (width-16) Poseidon2 instances per spend after K-air-col-step2:
// zero (the claim-2 Cm compression is folded into the global shared
// w=16 block on trace rows 0..3).
#define POSEIDON2_WIDE_PER_SPEND 0

// Wide (width-16) Poseidon2 instances per output after K-air-col-step2:
// zero (the claim-6 Cm compression is folded into the global shared
// w=16 block on trace rows 4..7).
#define POSEIDON2_WIDE_PER_OUTPUT 0

// Default test chain_id ("UNOT" LE).
#define CHAIN_ID_TEST 1414483541

// Default test expiry_block for witness-derived public inputs.
#define EXPIRY_BLOCK_TEST 100000

// Sponge width. Matches `Poseidon2Goldilocks<8>`.
#define SPONGE_WIDTH 8

// Absorb / squeeze rate. Matches prover's `DuplexChallenger<_, _, 8, 4>`.
#define SPONGE_RATE 4

// Capacity (non-absorbed state positions).
#define SPONGE_CAPACITY (SPONGE_WIDTH - SPONGE_RATE)

// Column layout for the future ChallengerAir. Each row represents one
// operation: `Observe(v)`, `Sample → v'`, `Duplex`, or `Idle`. Phase
// A2-2 will wire the constraints; Phase A2-1 only documents the
// intent.
//
// # Per-row columns (width ≈ 24 + 1 Poseidon2-w8 block on duplex rows)
//
// ```text
// ----- State (persistent across rows) -----
//   state_local[0..8]     : 8 cols   — sponge state mirror
//   in_buf[0..4]          : 4 cols   — pending inputs
//   in_buf_len            : 1 col    — current in_buf fill (0..=4)
//   out_buf[0..4]         : 4 cols   — output queue
//   out_buf_len           : 1 col    — current out_buf fill (0..=4)
//
// ----- Per-row operation selector (one-hot) -----
//   is_observe            : 1 col
//   is_sample             : 1 col
//   is_duplex_auto        : 1 col    — triggered by in_buf_len == 4
//   is_duplex_forced      : 1 col    — triggered by sample-on-empty-out
//   is_idle               : 1 col
//
// ----- Per-row operation payload -----
//   observed_value        : 1 col    — the F being absorbed (if observe)
//   sampled_value         : 1 col    — the F being squeezed (if sample)
//
// ----- Duplex row extension (only populated on duplex rows) -----
//   p2_cols               : 180 cols — shared Poseidon2 block
//                                      (row-gated by is_duplex_* via
//                                       the GS_ROW_SEL-style selector
//                                       pattern from K-air-col-share)
// ```
//
// **Rough per-row width: ~24 cols for the state-tracking side, plus
// the shared Poseidon2-w8 block (180 cols) — same size as the
// per-spend Merkle block in `transfer_air`.** Phase A2-2 must
// confirm this fits the §3 aggregator column-budget estimate
// (~200-300 cols/slot in `doc/uno-aggregation-design.md` §1.3).
#define CHALLENGER_STATE_COLS ((((8 + 4) + 1) + 4) + 1)

// Per-row operation selectors + payloads.
#define CHALLENGER_OP_COLS (5 + 2)

// Total non-P2 columns per challenger row.
#define CHALLENGER_NON_P2_COLS (CHALLENGER_STATE_COLS + CHALLENGER_OP_COLS)

// Operation kind flag values (one-hot column index inside the trace row).
#define OP_KIND_OBSERVE 0

#define OP_KIND_SAMPLE 1

#define OP_KIND_DUPLEX 2

#define OP_KIND_IDLE 3

// Number of distinct row kinds; matches the one-hot selector width.
#define CHALLENGER_NUM_OP_KINDS 4



// Offset of state[0].
#define STATE0 0

// Width of the state block = SPONGE_WIDTH (8).
#define STATE_END (STATE0 + SPONGE_WIDTH)

#define IN_BUF0 STATE_END

#define IN_BUF_END (IN_BUF0 + SPONGE_RATE)

#define IN_BUF_LEN IN_BUF_END

// One-hot decoder of in_buf_len: IN_BUF_LEN_FLAG[i] = 1 iff in_buf_len == i,
// for i ∈ {0, 1, 2, 3, 4}. 5 positions.
#define IN_BUF_LEN_FLAG0 (IN_BUF_LEN + 1)

#define IN_BUF_LEN_FLAG_END (IN_BUF_LEN_FLAG0 + (SPONGE_RATE + 1))

#define OUT_BUF0 IN_BUF_LEN_FLAG_END

#define OUT_BUF_END (OUT_BUF0 + SPONGE_RATE)

#define OUT_BUF_LEN OUT_BUF_END

#define OUT_BUF_LEN_FLAG0 (OUT_BUF_LEN + 1)

#define OUT_BUF_LEN_FLAG_END (OUT_BUF_LEN_FLAG0 + (SPONGE_RATE + 1))

#define KIND0 OUT_BUF_LEN_FLAG_END

#define KIND_END (KIND0 + CHALLENGER_NUM_OP_KINDS)

// Value absorbed on OBSERVE rows; constrained to 0 on non-OBSERVE rows
// (not strictly required for soundness, but simplifies audit).
#define OBSERVED_VALUE KIND_END

// Value squeezed on SAMPLE rows; equal to out_buf_local[out_buf_len_local - 1].
#define SAMPLED_VALUE (OBSERVED_VALUE + 1)

// Total column width of a ChallengerAir trace row.
#define WIDTH (SAMPLED_VALUE + 1)

// Per-block maximum aggregated Transfer count. See design doc §2.3.
//
// Rationale: matches §1.4 success criterion #7 (15–30 TPS sustained)
// at 1 s block cadence. A higher cap increases aggregator prove time
// and may push the block production off the 1 s schedule.
#define BLOCK_TX_CAP 30

// Minimum aggregated Transfer count. Zero-Transfer blocks are legal
// (empty block → empty aggregator proof), but the aggregator only
// runs when N >= 1.
#define BLOCK_TX_MIN 0

// Result codes returned across the C ABI.
//
// These are stable wire values; renumbering is a breaking change. C++ side
// mirrors this enum in `uno/crypto/plonky3-verifier.h`.
enum Plonky3Status
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    // Verification succeeded / prover produced a valid proof.
    Ok = 0,
    // The proof bytes could not be deserialized into a Plonky3 proof.
    ProofDecodeFailed = 1,
    // Public-input bytes could not be decoded into field elements.
    PublicInputDecodeFailed = 2,
    // Public-input vector length does not match the AIR's declared length.
    PublicInputLengthMismatch = 3,
    // Plonky3 STARK verify returned a constraint-violation error.
    VerifyFailed = 4,
    // A prover-only entry point was called but the witness was invalid
    // (e.g. out-of-range value, inconsistent Merkle siblings).
    WitnessInvalid = 5,
    // The caller passed a null pointer where a non-null one was required.
    NullPointer = 6,
    // A length argument was larger than `isize::MAX` (ABI guard).
    LengthTooLarge = 7,
    // Rust-side panic caught at FFI boundary. Indicates a bug in this
    // crate or the pinned Plonky3 rev; never returned in correct usage.
    InternalError = 99,
};
#ifndef __cplusplus
typedef int32_t Plonky3Status;
#endif // __cplusplus

// Opaque handle to an initialized Plonky3 reference prover.
//
// Constructed by [`uno_plonky3_prover_init`], destroyed by
// [`uno_plonky3_prover_free`]. Not used by the validator; used by
// `tosctl` for witness-generation and by integration tests.
typedef struct Plonky3ProverHandle Plonky3ProverHandle;

// Opaque handle to an initialized Plonky3 verifier.
//
// Constructed by [`uno_plonky3_verifier_init`] and destroyed by
// [`uno_plonky3_verifier_free`]. Internally holds the Plonky3 `StarkConfig`
// and a reference to the statically-configured MVP AIR instance.
//
// Thread-safety: the handle is `Send + Sync` and may be used concurrently
// from multiple threads. This is required by design doc §13 P.3 (parallel
// verify across `num_cores` workers is an activation prerequisite).
typedef struct Plonky3VerifierHandle Plonky3VerifierHandle;

// Borrowed byte slice passed across the FFI. Matches C `struct { const
// uint8_t* ptr; uintptr_t len; }`.
//
// The buffer is valid for the duration of the FFI call only; the Rust
// side may read but not retain it.
typedef struct {
    // Pointer to the first byte of the serialized proof.
    const uint8_t *ptr;
    // Length in bytes.
    uintptr_t len;
} Plonky3ProofBytes;

// Borrowed byte slice containing the canonical public-input encoding.
//
// # Wire format (decision #5 / §4.3 step 4)
//
// Each Goldilocks element serializes as 8 bytes little-endian u64
// (canonical Plonky3 form: `Goldilocks::from_canonical_u64` /
// `Goldilocks::from_wrapped_u64`). 256-bit inputs split into 4 × u64 LE
// chunks, each reduced mod `p_Goldilocks = 2^64 - 2^32 + 1`. The
// verifier decodes via `transfer_air::decode_public_inputs`, which
// rejects non-canonical limbs (v ≥ p) to close off a wire-encoding
// malleability vector.
//
// Production Transfer AIR element order is §4.3 step 4 bullets 1–7:
// scheme_id, chain_id, expiry_block, fee, anchor (4 limbs), and per
// spend/output the corresponding nf/rk/cm/epk/filter_tag fields. Total
// byte length: `64 + 64·spend_count + 72·output_count`.
//
// Cross-impl byte parity is enforced by the golden fixture
// `uno/test/golden/public-inputs-v1.hex` — produced by the C++ encoder
// (`uno/core/transaction.cpp :: build_plonky3_public_inputs`) and
// checked by this crate's `tests/public_input_fixture.rs`. Any wire
// drift is a scheme_id bump.
//
// The MVP AIR shipped in P.0 uses a simpler 4-element schema (3 → 4
// elements after decision #1's claim-3 extension); see
// `transfer_air::MvpWitness::public_inputs_bytes`.
typedef struct {
    // Pointer to the first byte of the public-input encoding.
    const uint8_t *ptr;
    // Length in bytes. Must be a multiple of 8 (Goldilocks byte width).
    uintptr_t len;
} Plonky3PublicInputs;

// Borrowed witness bytes for the reference prover. Layout is defined in
// [`transfer_air::MvpWitness::encode`].
//
// # Witness wire length (P.2 scale-to-envelope)
//
// The witness encoding is length-variable across the §4.1 envelope:
//
// ```text
// witness_len = 18 + 64·n_spends + 40·n_outputs
// ```
//
// — `1 ≤ n_spends, n_outputs ≤ 4`. Prior slices (A4 MVP → N-P2 real
// Poseidon2) shipped a fixed 64 B witness at (1, 1). This slice
// replaces the fixed shape with a shape header (`u8 n_spends || u8
// n_outputs`) followed by per-spend and per-output records. The
// witness is a **prover-only** wire format and does not affect the
// consensus-binding public-input or proof bytes.
typedef struct {
    // Pointer to the first byte of the encoded witness.
    const uint8_t *ptr;
    // Length in bytes.
    uintptr_t len;
} Plonky3Witness;

// Owned output buffer used by the prover to return a serialized proof.
// The Rust side allocates via `Box::into_raw`; the caller must free via
// [`uno_plonky3_proof_free`] exactly once.
//
// Layout must match the C side byte-for-byte.
typedef struct {
    // Heap-allocated buffer (aligned to `u8`). Never null on Ok return.
    uint8_t *ptr;
    // Length in bytes.
    uintptr_t len;
    // Capacity in bytes (needed for correct `Vec` reconstruction on free).
    uintptr_t cap;
} Plonky3OwnedProof;





#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Initialize a Plonky3 verifier and return an opaque handle to it.
//
// On success, writes a non-null handle pointer to `out_handle` and returns
// [`Plonky3Status::Ok`]. On failure, `*out_handle` is set to null.
//
// The caller owns the returned handle and **must** call
// [`uno_plonky3_verifier_free`] exactly once when done.
//
// # Safety
// `out_handle` must be a valid, aligned, writable `*mut *mut
// Plonky3VerifierHandle` pointer.
int32_t uno_plonky3_verifier_init(Plonky3VerifierHandle **out_handle);

// Free a verifier handle previously returned by [`uno_plonky3_verifier_init`].
//
// Safe to call with a null pointer (no-op). Must not be called twice for
// the same non-null pointer.
//
// # Safety
// `handle` must have been returned by [`uno_plonky3_verifier_init`] and
// not freed.
void uno_plonky3_verifier_free(Plonky3VerifierHandle *handle);

// Verify a Plonky3 STARK proof of the MVP AIR against the given public
// inputs.
//
// Returns:
// - [`Plonky3Status::Ok`] iff the proof is valid for the public inputs.
// - A specific decode / mismatch / verify error code otherwise.
//
// This is the entry point called from the validator's compute phase (via
// Agent 5's `Plonky3Verifier::verify(proof_bytes, public_inputs)` C++
// wrapper).
//
// # Safety
// `handle` must be a live handle from [`uno_plonky3_verifier_init`]. The
// `proof` and `public_inputs` buffers must be valid for reads of their
// declared lengths for the duration of the call.
int32_t uno_plonky3_verify(const Plonky3VerifierHandle *handle,
                           Plonky3ProofBytes proof,
                           Plonky3PublicInputs public_inputs);

// Initialize a reference prover and return an opaque handle.
//
// # Safety
// `out_handle` must be a valid writable pointer.
int32_t uno_plonky3_prover_init(Plonky3ProverHandle **out_handle);

// Free a prover handle.
//
// # Safety
// Same rules as [`uno_plonky3_verifier_free`].
void uno_plonky3_prover_free(Plonky3ProverHandle *handle);

// Run the reference prover against a witness, producing a serialized proof.
//
// On `Ok`, `*out_proof` is populated with a heap-allocated buffer that the
// caller must free via [`uno_plonky3_proof_free`]. On any non-Ok return,
// `*out_proof` is set to an empty descriptor.
//
// This is a **reference** implementation suitable for test fixtures and
// `tosctl`; it is not optimized for wallet-side proving performance. The
// production prover (P.2 full Transfer AIR) will be written in a later
// iteration.
//
// # Safety
// - `handle` must be from [`uno_plonky3_prover_init`].
// - `witness` buffer must be valid for the call.
// - `out_proof` must be a valid writable pointer.
int32_t uno_plonky3_prove(const Plonky3ProverHandle *handle,
                          Plonky3Witness witness,
                          Plonky3OwnedProof *out_proof);

// Free a buffer previously returned by [`uno_plonky3_prove`].
//
// # Safety
// `proof.ptr` must have come from a prior `uno_plonky3_prove` call and
// must not have been freed. Other fields of `proof` must be unchanged.
void uno_plonky3_proof_free(Plonky3OwnedProof proof);

// Returns the ABI revision of this crate. The C++ bridge checks this at
// `Plonky3Verifier::init()` to catch a version-skew between the shipped
// Rust static-lib and the compiled C++ header.
//
// Current value: 1. Bump on any layout change to `Plonky3OwnedProof`,
// `Plonky3ProofBytes`, `Plonky3PublicInputs`, `Plonky3Witness`, or
// `Plonky3Status`, or on any addition/removal of FFI entry points.
uint32_t uno_plonky3_abi_version(void);

// Width-8 Poseidon2-Goldilocks permutation, in place.
//
// On success the 8 `u64`s at `state` are replaced with the permutation
// output (also canonical `< p_G`). If `state` is null or any limb is
// `>= p_G`, the call returns without writing.
//
// # Safety
// `state` must either be null or point to a writable, properly-aligned
// buffer of at least 8 `u64`s for the duration of the call.
void uno_poseidon2_goldilocks_permute_t8(uint64_t *state);

// Width-16 Poseidon2-Goldilocks permutation, in place.
//
// Contract mirrors [`uno_poseidon2_goldilocks_permute_t8`] at width 16.
// Used by the wide sponge for claim-2 / claim-6 note-commitment absorb
// (15-fe input fits in the width-16 state with one capacity slot).
//
// # Safety
// `state` must either be null or point to a writable, properly-aligned
// buffer of at least 16 `u64`s for the duration of the call.
void uno_poseidon2_goldilocks_permute_t16(uint64_t *state);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UNO_PLONKY3_FFI_H */
