#ifndef UNO_PLONKY3_FFI_H
#define UNO_PLONKY3_FFI_H

#pragma once

/* Auto-generated by cbindgen from uno/plonky3-ffi/src/lib.rs. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// AIR mixing coefficient used by the MVP ivk-commitment binding (decision
// #1, §4.2 claim 3 scaffold):
//
// ```text
//     ivk_commitment_claim = ivk * IVK_CM_MIX_COEF + sibling   // sibling reused as `d` proxy
// ```
//
// Linear stand-in for `Poseidon2("uno-ivk-cm-v1", ivk, d)`. Same role as
// `MERKLE_MIX_COEF`: preserves the constraint family (one public-input
// output bound to a hash-like combination of a private witness and a
// trace-accessible value) while deferring the full Poseidon2 expansion to
// P.2. A different mix coefficient is used so the two constraints don't
// collapse into the same linear relation — an adversary who satisfies the
// Merkle step without knowing the right `ivk` still gets the wrong
// `ivk_commitment_claim`. Value: 0xbadcafe0_ivkcmv1 formatted as a nonce.
//
// TODO(uno-design-gap): replace with the real in-circuit Poseidon2 over
// the 6-element input `[ivk (4 fes), d_packed (2 fes)]` at P.2. Verifier
// side (off-circuit, §2.6) already uses real Poseidon2.
#define IVK_CM_MIX_COEF 841551897658772225

#define IVK 5

#define IVK_COMMITMENT_CLAIM 6

// Result codes returned across the C ABI.
//
// These are stable wire values; renumbering is a breaking change. C++ side
// mirrors this enum in `uno/crypto/plonky3-verifier.h`.
enum Plonky3Status
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    // Verification succeeded / prover produced a valid proof.
    Ok = 0,
    // The proof bytes could not be deserialized into a Plonky3 proof.
    ProofDecodeFailed = 1,
    // Public-input bytes could not be decoded into field elements.
    PublicInputDecodeFailed = 2,
    // Public-input vector length does not match the AIR's declared length.
    PublicInputLengthMismatch = 3,
    // Plonky3 STARK verify returned a constraint-violation error.
    VerifyFailed = 4,
    // A prover-only entry point was called but the witness was invalid
    // (e.g. out-of-range value, inconsistent Merkle siblings).
    WitnessInvalid = 5,
    // The caller passed a null pointer where a non-null one was required.
    NullPointer = 6,
    // A length argument was larger than `isize::MAX` (ABI guard).
    LengthTooLarge = 7,
    // Rust-side panic caught at FFI boundary. Indicates a bug in this
    // crate or the pinned Plonky3 rev; never returned in correct usage.
    InternalError = 99,
};
#ifndef __cplusplus
typedef int32_t Plonky3Status;
#endif // __cplusplus

// Opaque handle to an initialized Plonky3 reference prover.
//
// Constructed by [`uno_plonky3_prover_init`], destroyed by
// [`uno_plonky3_prover_free`]. Not used by the validator; used by
// `tosctl` for witness-generation and by integration tests.
typedef struct Plonky3ProverHandle Plonky3ProverHandle;

// Opaque handle to an initialized Plonky3 verifier.
//
// Constructed by [`uno_plonky3_verifier_init`] and destroyed by
// [`uno_plonky3_verifier_free`]. Internally holds the Plonky3 `StarkConfig`
// and a reference to the statically-configured MVP AIR instance.
//
// Thread-safety: the handle is `Send + Sync` and may be used concurrently
// from multiple threads. This is required by design doc §13 P.3 (parallel
// verify across `num_cores` workers is an activation prerequisite).
typedef struct Plonky3VerifierHandle Plonky3VerifierHandle;

// Borrowed byte slice passed across the FFI. Matches C `struct { const
// uint8_t* ptr; uintptr_t len; }`.
//
// The buffer is valid for the duration of the FFI call only; the Rust
// side may read but not retain it.
typedef struct {
    // Pointer to the first byte of the serialized proof.
    const uint8_t *ptr;
    // Length in bytes.
    uintptr_t len;
} Plonky3ProofBytes;

// Borrowed byte slice containing the canonical public-input encoding.
//
// # Wire format (decision #5 / §4.3 step 4)
//
// Each Goldilocks element serializes as 8 bytes little-endian u64
// (canonical Plonky3 form: `Goldilocks::from_canonical_u64` /
// `Goldilocks::from_wrapped_u64`). 256-bit inputs split into 4 × u64 LE
// chunks, each reduced mod `p_Goldilocks = 2^64 - 2^32 + 1`. The
// verifier decodes via `transfer_air::decode_public_inputs`, which
// rejects non-canonical limbs (v ≥ p) to close off a wire-encoding
// malleability vector.
//
// Production Transfer AIR element order is §4.3 step 4 bullets 1–7:
// scheme_id, chain_id, expiry_block, fee, anchor (4 limbs), and per
// spend/output the corresponding nf/rk/cm/epk/filter_tag fields. Total
// byte length: `64 + 64·spend_count + 72·output_count`.
//
// Cross-impl byte parity is enforced by the golden fixture
// `uno/test/golden/public-inputs-v1.hex` — produced by the C++ encoder
// (`uno/core/transaction.cpp :: build_plonky3_public_inputs`) and
// checked by this crate's `tests/public_input_fixture.rs`. Any wire
// drift is a scheme_id bump.
//
// The MVP AIR shipped in P.0 uses a simpler 4-element schema (3 → 4
// elements after decision #1's claim-3 extension); see
// `transfer_air::MvpWitness::public_inputs_bytes`.
typedef struct {
    // Pointer to the first byte of the public-input encoding.
    const uint8_t *ptr;
    // Length in bytes. Must be a multiple of 8 (Goldilocks byte width).
    uintptr_t len;
} Plonky3PublicInputs;

// Borrowed witness bytes for the reference prover. Layout is MVP-AIR
// specific and defined in [`transfer_air::MvpWitness::encode`].
typedef struct {
    // Pointer to the first byte of the encoded witness.
    const uint8_t *ptr;
    // Length in bytes.
    uintptr_t len;
} Plonky3Witness;

// Owned output buffer used by the prover to return a serialized proof.
// The Rust side allocates via `Box::into_raw`; the caller must free via
// [`uno_plonky3_proof_free`] exactly once.
//
// Layout must match the C side byte-for-byte.
typedef struct {
    // Heap-allocated buffer (aligned to `u8`). Never null on Ok return.
    uint8_t *ptr;
    // Length in bytes.
    uintptr_t len;
    // Capacity in bytes (needed for correct `Vec` reconstruction on free).
    uintptr_t cap;
} Plonky3OwnedProof;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Initialize a Plonky3 verifier and return an opaque handle to it.
//
// On success, writes a non-null handle pointer to `out_handle` and returns
// [`Plonky3Status::Ok`]. On failure, `*out_handle` is set to null.
//
// The caller owns the returned handle and **must** call
// [`uno_plonky3_verifier_free`] exactly once when done.
//
// # Safety
// `out_handle` must be a valid, aligned, writable `*mut *mut
// Plonky3VerifierHandle` pointer.
int32_t uno_plonky3_verifier_init(Plonky3VerifierHandle **out_handle);

// Free a verifier handle previously returned by [`uno_plonky3_verifier_init`].
//
// Safe to call with a null pointer (no-op). Must not be called twice for
// the same non-null pointer.
//
// # Safety
// `handle` must have been returned by [`uno_plonky3_verifier_init`] and
// not freed.
void uno_plonky3_verifier_free(Plonky3VerifierHandle *handle);

// Verify a Plonky3 STARK proof of the MVP AIR against the given public
// inputs.
//
// Returns:
// - [`Plonky3Status::Ok`] iff the proof is valid for the public inputs.
// - A specific decode / mismatch / verify error code otherwise.
//
// This is the entry point called from the validator's compute phase (via
// Agent 5's `Plonky3Verifier::verify(proof_bytes, public_inputs)` C++
// wrapper).
//
// # Safety
// `handle` must be a live handle from [`uno_plonky3_verifier_init`]. The
// `proof` and `public_inputs` buffers must be valid for reads of their
// declared lengths for the duration of the call.
int32_t uno_plonky3_verify(const Plonky3VerifierHandle *handle,
                           Plonky3ProofBytes proof,
                           Plonky3PublicInputs public_inputs);

// Initialize a reference prover and return an opaque handle.
//
// # Safety
// `out_handle` must be a valid writable pointer.
int32_t uno_plonky3_prover_init(Plonky3ProverHandle **out_handle);

// Free a prover handle.
//
// # Safety
// Same rules as [`uno_plonky3_verifier_free`].
void uno_plonky3_prover_free(Plonky3ProverHandle *handle);

// Run the reference prover against a witness, producing a serialized proof.
//
// On `Ok`, `*out_proof` is populated with a heap-allocated buffer that the
// caller must free via [`uno_plonky3_proof_free`]. On any non-Ok return,
// `*out_proof` is set to an empty descriptor.
//
// This is a **reference** implementation suitable for test fixtures and
// `tosctl`; it is not optimized for wallet-side proving performance. The
// production prover (P.2 full Transfer AIR) will be written in a later
// iteration.
//
// # Safety
// - `handle` must be from [`uno_plonky3_prover_init`].
// - `witness` buffer must be valid for the call.
// - `out_proof` must be a valid writable pointer.
int32_t uno_plonky3_prove(const Plonky3ProverHandle *handle,
                          Plonky3Witness witness,
                          Plonky3OwnedProof *out_proof);

// Free a buffer previously returned by [`uno_plonky3_prove`].
//
// # Safety
// `proof.ptr` must have come from a prior `uno_plonky3_prove` call and
// must not have been freed. Other fields of `proof` must be unchanged.
void uno_plonky3_proof_free(Plonky3OwnedProof proof);

// Returns the ABI revision of this crate. The C++ bridge checks this at
// `Plonky3Verifier::init()` to catch a version-skew between the shipped
// Rust static-lib and the compiled C++ header.
//
// Current value: 1. Bump on any layout change to `Plonky3OwnedProof`,
// `Plonky3ProofBytes`, `Plonky3PublicInputs`, `Plonky3Witness`, or
// `Plonky3Status`, or on any addition/removal of FFI entry points.
uint32_t uno_plonky3_abi_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* UNO_PLONKY3_FFI_H */
