# CMake generated Testfile for 
# Source directory: /home/tomi/tos-m2
# Build directory: /tmp/uno-publication-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-workchain-proof-boundary-gates "/home/tomi/.local/bin/python3" "/home/tomi/tos-m2/crypto/test/workchain-proof-boundary-gates.py")
set_tests_properties(test-workchain-proof-boundary-gates PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;655;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-proof-backend "/tmp/uno-publication-build/test-workchain-proof-backend" "/home/tomi/tos-m2/uno/crypto/fixtures/balance-kernel-v2.txt")
set_tests_properties(test-workchain-proof-backend PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;666;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-proof-operation-trace "/home/tomi/.local/bin/python3" "/home/tomi/tos-m2/crypto/test/workchain-proof-trace.py" "--source" "/home/tomi/tos-m2" "--build" "/tmp/uno-publication-build")
set_tests_properties(test-workchain-proof-operation-trace PROPERTIES  RESOURCE_LOCK "uno_crypto_cargo" TIMEOUT "600" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;669;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-quorum-static-grep "bash" "/home/tomi/tos-m2/scripts/check-quorum-static.sh" "/home/tomi/tos-m2")
set_tests_properties(test-quorum-static-grep PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;755;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-smoke "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke")
set_tests_properties(plumtree-graph-sim-smoke PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;772;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-simple-smoke "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke" "--broadcast-mode" "simple")
set_tests_properties(plumtree-graph-sim-simple-smoke PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;773;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-loss "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke" "--packet-loss" "0.10" "--broadcast-count" "5" "--seed" "17")
set_tests_properties(plumtree-graph-sim-loss PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;774;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-simple-loss "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke" "--broadcast-mode" "simple" "--packet-loss" "0.08" "--broadcast-count" "5" "--seed" "17")
set_tests_properties(plumtree-graph-sim-simple-loss PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;776;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-partition-recovery "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke" "--isolate-node" "11" "--isolate-broadcasts" "2" "--broadcast-count" "3" "--seed" "23")
set_tests_properties(plumtree-graph-sim-partition-recovery PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;778;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-selective-forwarding "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke" "--drop-outbound-node" "4" "--broadcast-count" "5" "--seed" "29")
set_tests_properties(plumtree-graph-sim-selective-forwarding PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;780;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-rotating-outage "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke" "--isolate-node" "4" "--isolate-broadcasts" "4" "--rotate-isolated-node" "--broadcast-count" "5" "--seed" "31")
set_tests_properties(plumtree-graph-sim-rotating-outage PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;782;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-simple-selective-forwarding "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke" "--broadcast-mode" "simple" "--drop-outbound-node" "4" "--broadcast-count" "5" "--seed" "37")
set_tests_properties(plumtree-graph-sim-simple-selective-forwarding PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;785;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-simple-rotating-outage "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke" "--broadcast-mode" "simple" "--isolate-node" "4" "--isolate-broadcasts" "4" "--rotate-isolated-node" "--broadcast-count" "5" "--seed" "41")
set_tests_properties(plumtree-graph-sim-simple-rotating-outage PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;788;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-fec-stress "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke" "--payload-bytes" "262144" "--jitter" "0.5" "--bandwidth-mb" "1" "--broadcast-count" "20" "--seed" "43")
set_tests_properties(plumtree-graph-sim-fec-stress PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;791;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(plumtree-graph-sim-simple-stress "/tmp/uno-publication-build/plumtree-graph-sim" "--smoke" "--broadcast-mode" "simple" "--payload-bytes" "262144" "--jitter" "0.5" "--bandwidth-mb" "1" "--broadcast-count" "20" "--seed" "47")
set_tests_properties(plumtree-graph-sim-simple-stress PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;794;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-collator-admission "/usr/bin/cmake" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-P" "/home/tomi/tos-m2/test/test-counter-collator-admission.cmake")
set_tests_properties(test-counter-collator-admission PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;801;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-disk-integration "/usr/bin/cmake" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-P" "/home/tomi/tos-m2/test/test-counter-disk-integration.cmake")
set_tests_properties(test-counter-disk-integration PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;804;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-account-binding-readiness "/usr/bin/cmake" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-DACCOUNT_BINDING_ONLY=ON" "-P" "/home/tomi/tos-m2/test/test-counter-disk-integration.cmake")
set_tests_properties(test-counter-account-binding-readiness PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;810;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-fixture-lifecycle "/usr/bin/cmake" "-DBUILD_DIR=/tmp/uno-publication-build" "-P" "/home/tomi/tos-m2/test/test-counter-fixture-lifecycle.cmake")
set_tests_properties(test-counter-fixture-lifecycle PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;816;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-idle-replay "/usr/bin/cmake" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-DIDLE_ONLY=ON" "-P" "/home/tomi/tos-m2/test/test-counter-disk-integration.cmake")
set_tests_properties(test-counter-idle-replay PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;820;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-self-delivery "/usr/bin/cmake" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-DSELF_DELIVERY=ON" "-P" "/home/tomi/tos-m2/test/test-counter-disk-integration.cmake")
set_tests_properties(test-counter-self-delivery PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;826;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-cross-delivery "/usr/bin/cmake" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-DCROSS_DELIVERY=ON" "-P" "/home/tomi/tos-m2/test/test-counter-disk-integration.cmake")
set_tests_properties(test-counter-cross-delivery PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;832;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-native-sender "/usr/bin/cmake" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-DNATIVE_SENDER=ON" "-P" "/home/tomi/tos-m2/test/test-counter-disk-integration.cmake")
set_tests_properties(test-counter-native-sender PROPERTIES  TIMEOUT "120" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;838;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-validator-local-visitors "/home/tomi/.local/bin/python3" "/home/tomi/tos-m2/crypto/test/workchain-validator-prepared-expiry.py" "--repo" "/home/tomi/tos-m2" "--probe" "/tmp/uno-publication-build/test-workchain-validator-local-visitors" "--fixture" "/home/tomi/tos-m2/doc/measurements/uno-local-profile/run-3/state/zerostate.boc")
set_tests_properties(test-workchain-validator-local-visitors PROPERTIES  LABELS "private;workchain;prepared-not-connected" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;860;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-ingress-transition "/tmp/uno-publication-build/test-workchain-ingress-transition")
set_tests_properties(test-workchain-ingress-transition PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;872;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-activation-missing_capability "/home/tomi/.local/bin/python3" "/home/tomi/tos-m2/crypto/test/workchain-genesis-activation.py" "--repo" "/home/tomi/tos-m2" "--probe" "/tmp/uno-publication-build/test-workchain-activation-control" "--mode" "missing-capability")
set_tests_properties(test-counter-activation-missing_capability PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;876;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-config-presence-missing_capability "/usr/bin/cmake" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-DACTIVATION_MODE=missing_capability" "-DREJECT_CONFIG_PRESENCE=ON" "-P" "/home/tomi/tos-m2/test/test-counter-disk-integration.cmake")
set_tests_properties(test-counter-config-presence-missing_capability PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;881;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-activation-old_version "/home/tomi/.local/bin/python3" "/home/tomi/tos-m2/crypto/test/workchain-genesis-activation.py" "--repo" "/home/tomi/tos-m2" "--probe" "/tmp/uno-publication-build/test-workchain-activation-control" "--mode" "old-version")
set_tests_properties(test-counter-activation-old_version PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;876;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-config-presence-old_version "/usr/bin/cmake" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-DACTIVATION_MODE=old_version" "-DREJECT_CONFIG_PRESENCE=ON" "-P" "/home/tomi/tos-m2/test/test-counter-disk-integration.cmake")
set_tests_properties(test-counter-config-presence-old_version PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;881;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-config-binding "/usr/bin/cmake" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-DACTIVATION_MODE=policy_version" "-DREJECT_CONFIG_PRESENCE=ON" "-P" "/home/tomi/tos-m2/test/test-counter-disk-integration.cmake")
set_tests_properties(test-counter-config-binding PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;890;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-engine-config "/usr/bin/cmake" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DCOLLATOR=/tmp/uno-publication-build/test-tos-collator" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-DACTIVATION_MODE=engine_payload" "-P" "/home/tomi/tos-m2/test/test-counter-disk-integration.cmake")
set_tests_properties(test-counter-engine-config PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;898;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-uno-partition-storage-smoke "/usr/bin/cmake" "-E" "env" "TOS_UNO_STORAGE_KEYS=1000" "TOS_UNO_STORAGE_PAGES=16" "/tmp/uno-publication-build/test-uno-storage-measurement" "--filter" "PartitionPersistenceStages")
set_tests_properties(test-uno-partition-storage-smoke PROPERTIES  FAIL_REGULAR_EXPRESSION "0 test[(]s[)] passed" LABELS "uno;storage;smoke" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;967;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-uno-incremental-storage-smoke "/usr/bin/cmake" "-E" "env" "TOS_UNO_STORAGE_KEYS=1000" "TOS_UNO_STORAGE_PAGES=16" "TOS_UNO_STORAGE_SHAPE=uniform" "/tmp/uno-publication-build/test-uno-storage-measurement" "--filter" "PartitionIncrementalRecords")
set_tests_properties(test-uno-incremental-storage-smoke PROPERTIES  FAIL_REGULAR_EXPRESSION "0 test[(]s[)] passed" LABELS "uno;storage;smoke" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;972;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-uno-split-storage-smoke "/usr/bin/cmake" "-E" "env" "TOS_UNO_STORAGE_KEYS=1000" "TOS_UNO_STORAGE_PAGES=16" "TOS_UNO_STORAGE_SHAPE=split" "/tmp/uno-publication-build/test-uno-storage-measurement" "--filter" "PartitionIncrementalRecords")
set_tests_properties(test-uno-split-storage-smoke PROPERTIES  FAIL_REGULAR_EXPRESSION "0 test[(]s[)] passed" LABELS "uno;storage;smoke" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;978;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-uno-split-prefix-storage-smoke "/usr/bin/cmake" "-E" "env" "TOS_UNO_STORAGE_KEYS=1000" "TOS_UNO_STORAGE_PAGES=16" "TOS_UNO_STORAGE_SHAPE=split-prefix" "/tmp/uno-publication-build/test-uno-storage-measurement" "--filter" "PartitionIncrementalRecords")
set_tests_properties(test-uno-split-prefix-storage-smoke PROPERTIES  FAIL_REGULAR_EXPRESSION "0 test[(]s[)] passed" LABELS "uno;storage;smoke" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;978;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-ed25519 "/tmp/uno-publication-build/test-ed25519")
set_tests_properties(test-ed25519 PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1215;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-bigint "/tmp/uno-publication-build/test-bigint")
set_tests_properties(test-bigint PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1216;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-vm "/tmp/uno-publication-build/test-vm" "--regression" "/home/tomi/tos-m2/test/regression-tests.ans" "--filter" "-Bench")
set_tests_properties(test-vm PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1217;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-fift "/tmp/uno-publication-build/test-fift" "--regression" "/home/tomi/tos-m2/test/regression-tests.ans" "--filter" "-Bench")
set_tests_properties(test-fift PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1218;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-cells "/tmp/uno-publication-build/test-cells" "--regression" "/home/tomi/tos-m2/test/regression-tests.ans" "--filter" "-Bench")
set_tests_properties(test-cells PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1219;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-block "/tmp/uno-publication-build/test-workchain-block")
set_tests_properties(test-workchain-block PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1220;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-settlement-continuation "/tmp/uno-publication-build/test-workchain-settlement-continuation")
set_tests_properties(test-workchain-settlement-continuation PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1221;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-collator-compute-mode "/tmp/uno-publication-build/test-workchain-collator-compute-mode")
set_tests_properties(test-workchain-collator-compute-mode PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1222;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-proof-work "/tmp/uno-publication-build/test-workchain-proof-work")
set_tests_properties(test-workchain-proof-work PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1223;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-proof-contracts "/tmp/uno-publication-build/test-workchain-proof-contracts")
set_tests_properties(test-workchain-proof-contracts PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1224;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-admission "/tmp/uno-publication-build/test-workchain-admission")
set_tests_properties(test-workchain-admission PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1225;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-smartcont "/tmp/uno-publication-build/test-smartcont" "--regression" "/home/tomi/tos-m2/test/regression-tests.ans" "--filter" "-Bench")
set_tests_properties(test-smartcont PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1226;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-net "/tmp/uno-publication-build/test-net")
set_tests_properties(test-net PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1227;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-tdactor "/tmp/uno-publication-build/test-tdactor")
set_tests_properties(test-tdactor PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1228;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-tdutils "/tmp/uno-publication-build/test-tdutils")
set_tests_properties(test-tdutils PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1231;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-toslib-offline "/tmp/uno-publication-build/test-toslib-offline")
set_tests_properties(test-toslib-offline PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1232;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-func "python3" "run_tests.py" "tests/")
set_tests_properties(test-func PROPERTIES  ENVIRONMENT "FUNC_EXECUTABLE=/tmp/uno-publication-build/crypto/func;FIFT_EXECUTABLE=/tmp/uno-publication-build/crypto/fift;FIFTPATH=/home/tomi/tos-m2/crypto/fift/lib/" WORKING_DIRECTORY "/home/tomi/tos-m2/crypto/func/auto-tests" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;1242;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-func-legacy "python3" "legacy_tester.py")
set_tests_properties(test-func-legacy PROPERTIES  ENVIRONMENT "FUNC_EXECUTABLE=/tmp/uno-publication-build/crypto/func;FIFT_EXECUTABLE=/tmp/uno-publication-build/crypto/fift;FIFTPATH=/home/tomi/tos-m2/crypto/fift/lib/" WORKING_DIRECTORY "/home/tomi/tos-m2/crypto/func/auto-tests" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;1258;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-tol "python3" "tol-tester.py" "tests/")
set_tests_properties(test-tol PROPERTIES  ENVIRONMENT "TOL_EXECUTABLE=/tmp/uno-publication-build/tol/tol;FIFT_EXECUTABLE=/tmp/uno-publication-build/crypto/fift;FIFTPATH=/home/tomi/tos-m2/crypto/fift/lib/" WORKING_DIRECTORY "/home/tomi/tos-m2/tol-tester" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;1282;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-adnl "/tmp/uno-publication-build/test-adnl")
set_tests_properties(test-adnl PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1301;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-dht "/tmp/uno-publication-build/test-dht")
set_tests_properties(test-dht PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1302;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-rldp2 "/tmp/uno-publication-build/test-rldp2")
set_tests_properties(test-rldp2 PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1303;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-rldp2-connection-cap "/tmp/uno-publication-build/test-rldp2-connection-cap")
set_tests_properties(test-rldp2-connection-cap PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1304;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-rldp2-query-eviction "/tmp/uno-publication-build/test-rldp2-query-eviction")
set_tests_properties(test-rldp2-query-eviction PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1305;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-rldp-http-proxy-routing "/tmp/uno-publication-build/test-rldp-http-proxy-routing")
set_tests_properties(test-rldp-http-proxy-routing PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1306;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-overlay-peer-cleanup "/tmp/uno-publication-build/test-overlay-peer-cleanup")
set_tests_properties(test-overlay-peer-cleanup PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1307;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-download-state-budget "/tmp/uno-publication-build/test-download-state-budget")
set_tests_properties(test-download-state-budget PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1308;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-download-next-blocks-validation "/tmp/uno-publication-build/test-download-next-blocks-validation")
set_tests_properties(test-download-next-blocks-validation PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1309;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-ext-message-pool "/tmp/uno-publication-build/test-ext-message-pool")
set_tests_properties(test-ext-message-pool PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1310;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-msg-envelope "/tmp/uno-publication-build/test-msg-envelope")
set_tests_properties(test-msg-envelope PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1311;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-rate-limiter "/tmp/uno-publication-build/test-rate-limiter")
set_tests_properties(test-rate-limiter PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1312;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-config-transition "/tmp/uno-publication-build/test-config-transition")
set_tests_properties(test-config-transition PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1313;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-json-rpc-parse "/tmp/uno-publication-build/test-json-rpc-parse")
set_tests_properties(test-json-rpc-parse PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1314;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-http-server-limits "/tmp/uno-publication-build/test-http-server-limits")
set_tests_properties(test-http-server-limits PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1315;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-wallet-message-processor "/tmp/uno-publication-build/test-wallet-message-processor")
set_tests_properties(test-wallet-message-processor PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1316;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-vm-exception-hardening "/tmp/uno-publication-build/test-vm-exception-hardening")
set_tests_properties(test-vm-exception-hardening PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1317;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-celldb-streaming-import "/tmp/uno-publication-build/test-celldb-streaming-import")
set_tests_properties(test-celldb-streaming-import PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1318;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-celldb-actor-restart "/tmp/uno-publication-build/test-celldb-actor-restart")
set_tests_properties(test-celldb-actor-restart PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1319;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-validator-options "/tmp/uno-publication-build/test-validator-options")
set_tests_properties(test-validator-options PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1320;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-full-node-shard-routing "/tmp/uno-publication-build/test-full-node-shard-routing")
set_tests_properties(test-full-node-shard-routing PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1321;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-uno-state-snapshot "/tmp/uno-publication-build/test-uno-state-snapshot")
set_tests_properties(test-uno-state-snapshot PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1322;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-genesis-domain "/usr/bin/cmake" "-DCREATE_STATE=/tmp/uno-publication-build/crypto/create-state" "-DSOURCE_DIR=/home/tomi/tos-m2" "-DBUILD_DIR=/tmp/uno-publication-build" "-P" "/home/tomi/tos-m2/test/test-counter-genesis-domain.cmake")
set_tests_properties(test-counter-genesis-domain PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;1323;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-uno-genesis-operators "/home/tomi/.local/bin/python3" "/home/tomi/tos-m2/test/test-uno-genesis-operators.py" "--create-state" "/tmp/uno-publication-build/crypto/create-state" "--repo" "/home/tomi/tos-m2")
set_tests_properties(test-uno-genesis-operators PROPERTIES  LABELS "uno;genesis" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;1327;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-workchain-genesis-routing "/home/tomi/tos/.venv/bin/python" "/home/tomi/tos-m2/crypto/test/workchain-genesis-routing.py" "--repo" "/home/tomi/tos-m2" "--create-state" "/tmp/uno-publication-build/crypto/create-state" "--collator" "/tmp/uno-publication-build/test-tos-collator")
set_tests_properties(test-workchain-genesis-routing PROPERTIES  LABELS "uno;genesis;harness" TIMEOUT "300" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;1340;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-counter-python-harness "/home/tomi/tos/.venv/bin/python" "-m" "pytest" "test/tostester/test_counter_committee.py" "test/tostester/test_counter_genesis.py" "test/tostester/test_counter_state_check.py")
set_tests_properties(test-counter-python-harness PROPERTIES  LABELS "uno;harness" TIMEOUT "300" WORKING_DIRECTORY "/home/tomi/tos-m2" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;1345;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-uno-build-wiring "/home/tomi/tos/.venv/bin/python" "/home/tomi/tos-m2/test/test-uno-build-wiring.py")
set_tests_properties(test-uno-build-wiring PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;1348;add_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-block-handle-flags "/tmp/uno-publication-build/test-block-handle-flags")
set_tests_properties(test-block-handle-flags PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1358;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-keyring-temp-key "/tmp/uno-publication-build/test-keyring-temp-key")
set_tests_properties(test-keyring-temp-key PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1359;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-collator-node-limits "/tmp/uno-publication-build/test-collator-node-limits")
set_tests_properties(test-collator-node-limits PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1360;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-rldp2-connection-limits "/tmp/uno-publication-build/test-rldp2-connection-limits")
set_tests_properties(test-rldp2-connection-limits PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1361;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-promise-loss-contract "/tmp/uno-publication-build/test-promise-loss-contract")
set_tests_properties(test-promise-loss-contract PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1362;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-json-rpc-handler-guard "/tmp/uno-publication-build/test-json-rpc-handler-guard")
set_tests_properties(test-json-rpc-handler-guard PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1363;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-metrics-label-bound "/tmp/uno-publication-build/test-metrics-label-bound")
set_tests_properties(test-metrics-label-bound PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1364;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-rldp2-inbound-transfer-bound "/tmp/uno-publication-build/test-rldp2-inbound-transfer-bound")
set_tests_properties(test-rldp2-inbound-transfer-bound PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1365;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-consensus-config-admission "/tmp/uno-publication-build/test-consensus-config-admission")
set_tests_properties(test-consensus-config-admission PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1366;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-weak-ptr-registry "/tmp/uno-publication-build/test-weak-ptr-registry")
set_tests_properties(test-weak-ptr-registry PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1367;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-wallet-index "/tmp/uno-publication-build/test-wallet-index")
set_tests_properties(test-wallet-index PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1368;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-quorum "/tmp/uno-publication-build/test-quorum")
set_tests_properties(test-quorum PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1369;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-emulator "/tmp/uno-publication-build/test-emulator")
set_tests_properties(test-emulator PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1370;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-fec "/tmp/uno-publication-build/test-fec")
set_tests_properties(test-fec PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1372;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-tddb "/tmp/uno-publication-build/test-tddb" "--regression" "/home/tomi/tos-m2/test/regression-tests.ans" "--filter" "-Bench")
set_tests_properties(test-tddb PROPERTIES  ENVIRONMENT "TOS_ROCKSDB_BLOCK_CACHE_SIZE=33554432;TOS_ROCKSDB_CRITICAL_WRITE_BUFFER_SIZE=67108864;TOS_ROCKSDB_CRITICAL_WRITE_BUFFER_ALLOW_STALL=1;TOS_ROCKSDB_GLOBAL_WRITE_BUFFER_SIZE=134217728;TOS_ROCKSDB_GLOBAL_WRITE_BUFFER_ALLOW_STALL=1" _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1373;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
add_test(test-db "/tmp/uno-publication-build/test-db" "--regression" "/home/tomi/tos-m2/test/regression-tests.ans" "--filter" "-Bench")
set_tests_properties(test-db PROPERTIES  _BACKTRACE_TRIPLES "/home/tomi/tos-m2/CMakeLists.txt;531;add_test;/home/tomi/tos-m2/CMakeLists.txt;1376;tos_test;/home/tomi/tos-m2/CMakeLists.txt;0;")
subdirs("third-party/rocksdb")
subdirs("third-party/abseil-cpp")
subdirs("third-party/crc32c")
subdirs("third-party/ngtcp2")
subdirs("third-party/tl-parser")
subdirs("uno/crypto")
subdirs("tdutils")
subdirs("memprof")
subdirs("metrics")
subdirs("tdactor")
subdirs("tdnet")
subdirs("tddb")
subdirs("tdtl")
subdirs("tl")
subdirs("terminal")
subdirs("keys")
subdirs("tl-utils")
subdirs("adnl")
subdirs("crypto")
subdirs("lite-client")
subdirs("emulator")
subdirs("tol")
subdirs("toslib")
subdirs("common")
subdirs("http")
subdirs("tdfec")
subdirs("keyring")
subdirs("fec")
subdirs("rldp2")
subdirs("dht")
subdirs("overlay")
subdirs("validator")
subdirs("blockchain-explorer")
subdirs("storage")
subdirs("validator-engine")
subdirs("validator-engine-console")
subdirs("create-hardfork")
subdirs("dht-server")
subdirs("utils")
subdirs("rldp-http-proxy")
subdirs("quic")
subdirs("test")
