// Generated by tools/validator-auth/generate.py.
#pragma once
#include <array>
#include <cstdint>
namespace block {
inline constexpr std::array<std::uint8_t,32> validator_auth_profile_fingerprint{128,50,170,136,254,126,194,137,248,27,116,25,177,245,225,167,243,247,174,180,177,23,201,76,10,98,215,16,221,184,78,241};
}
