// Generated by tools/validator-auth/generate.py.
#pragma once
#include <array>
#include <cstdint>
namespace block {
inline constexpr std::array<std::uint8_t,32> validator_auth_profile_fingerprint{141,76,93,215,164,16,71,41,86,216,234,75,90,225,247,105,5,163,73,42,10,209,138,72,239,229,38,117,180,0,249,130};
}
