[Service]
Environment=TOS_MEMORY_DIAGNOSTICS=1
Environment=MALLOC_CONF=background_thread:true,dirty_decay_ms:10000,muzzy_decay_ms:10000
ExecStart=
ExecStart=/home/tomi/tos/build/validator-engine/validator-engine --global-config /home/tomi/tos/test/integration/.network/node3/config.global.json --local-config /home/tomi/tos/test/integration/.network/node3/config.json --db . -v2 --initial-sync-delay 5 --celldb-cache-size 1073741824 --celldb-cache-min-size 1073741824 --celldb-cell-cache-max-size 100000 --quic-flood-control -1
