/* Copyright 2026 TOS Blockchain Teams. SPDX-License-Identifier: LGPL-2.0-or-later */
#pragma once
#include "auto/tl/lite_api.hpp"
#include "tl-utils/lite-utils.hpp"
#include "tos/lite-tl.hpp"
#include "td/utils/base64.h"
namespace tos::proofverify {
// Only query kinds generated by acquisition.cpp. No sendMessage or nested query.
inline td::Result<td::BufferSlice> checked_readonly_query(td::Slice bytes) {
  if (bytes.empty() || bytes.size() > 16384) return td::Status::Error("proof query size refused");
  TRY_RESULT(query, tos::fetch_tl_object<tos::lite_api::Function>(td::BufferSlice(bytes), true));
  if (query->get_id() == tos::lite_api::liteServer_getConfigParams::ID &&
      static_cast<const tos::lite_api::liteServer_getConfigParams &>(*query).param_list_.size() > 64) {
    return td::Status::Error("proof configuration query limit");
  }
  if (query->get_id() == tos::lite_api::liteServer_getLibrariesWithProof::ID &&
      static_cast<const tos::lite_api::liteServer_getLibrariesWithProof &>(*query).library_list_.size() > 16) {
    return td::Status::Error("proof library query limit");
  }
  switch (query->get_id()) {
    case tos::lite_api::liteServer_getMasterchainInfo::ID:
    case tos::lite_api::liteServer_getBlockProof::ID:
    case tos::lite_api::liteServer_getConfigParams::ID:
    case tos::lite_api::liteServer_getConfigAll::ID:
    case tos::lite_api::liteServer_getAccountState::ID:
    case tos::lite_api::liteServer_getLibrariesWithProof::ID:
      return tos::serialize_tl_object(query, true);
    default: return td::Status::Error("proof query kind refused");
  }
}
inline td::Result<std::string> readonly_reply_json(td::Slice bytes) {
  if (bytes.empty() || bytes.size() > (64u << 20)) return td::Status::Error("proof response size refused");
  return std::string("{\"reply\":\"") + td::base64_encode(bytes) + "\"}";
}

}
