# tosctl service config (local): chain_rpc=http://127.0.0.1:8082, api=http://127.0.0.1:8080

http:
    bind: "127.0.0.1:8080"
    enable_swagger: true

chain_rpc:
    urls:
        - "http://127.0.0.1:8082"
    api_key: null

nodes_adnl: {}
wallets: {}
elections: {}
