// Generated by tools/validator-auth/generate.py.
use crate::codec::{Error, Hash, Reader, Wire, Writer};
pub const INTERFACE_FINGERPRINT: Hash = [
    128, 50, 170, 136, 254, 126, 194, 137, 248, 27, 116, 25, 177, 245, 225, 167, 243, 247, 174,
    180, 177, 23, 201, 76, 10, 98, 215, 16, 221, 184, 78, 241,
];
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Suite {
    pub suite: u16,
    pub parameters: u16,
}
impl Wire for Suite {
    const MIN_SIZE: usize = 4;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        Ok(Self { suite: r.integer(2)? as u16, parameters: r.integer(2)? as u16 })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.integer(self.suite as u64, 2)?;
        w.integer(self.parameters as u64, 2)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Keyref {
    pub suite: u16,
    pub parameters: u16,
    pub epoch: u64,
    pub key_id: Hash,
}
impl Wire for Keyref {
    const MIN_SIZE: usize = 44;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        Ok(Self {
            suite: r.integer(2)? as u16,
            parameters: r.integer(2)? as u16,
            epoch: r.integer(8)?,
            key_id: r.hash()?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.integer(self.suite as u64, 2)?;
        w.integer(self.parameters as u64, 2)?;
        w.integer(self.epoch, 8)?;
        w.bytes(&self.key_id)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Component {
    pub suite: u16,
    pub parameters: u16,
    pub epoch: u64,
    pub key_id: Hash,
    pub signature: Vec<u8>,
}
impl Wire for Component {
    const MIN_SIZE: usize = 48;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        Ok(Self {
            suite: r.integer(2)? as u16,
            parameters: r.integer(2)? as u16,
            epoch: r.integer(8)?,
            key_id: r.hash()?,
            signature: r.blob(65536)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.integer(self.suite as u64, 2)?;
        w.integer(self.parameters as u64, 2)?;
        w.integer(self.epoch, 8)?;
        w.bytes(&self.key_id)?;
        w.blob(&self.signature, 65536)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Record {
    pub identity: Hash,
    pub components: Vec<Component>,
}
impl Wire for Record {
    const MIN_SIZE: usize = 33;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        Ok(Self { identity: r.hash()?, components: r.list::<Component>(1, 2)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.bytes(&self.identity)?;
        w.list(&self.components, 1, 2)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Roleref {
    pub role: u8,
    pub key: Keyref,
}
impl Wire for Roleref {
    const MIN_SIZE: usize = 45;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        Ok(Self { role: r.integer(1)? as u8, key: Keyref::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.integer(self.role as u64, 1)?;
        self.key.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Key {
    pub identity: Hash,
    pub role: u8,
    pub suite: u16,
    pub parameters: u16,
    pub epoch: u64,
    pub valid_from: u32,
    pub valid_until: u32,
    pub public_key: Vec<u8>,
    pub capacity_domain: Hash,
    pub capacity_limit: u64,
}
impl Wire for Key {
    const MIN_SIZE: usize = 105;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAK1")?;
        Ok(Self {
            identity: r.hash()?,
            role: r.integer(1)? as u8,
            suite: r.integer(2)? as u16,
            parameters: r.integer(2)? as u16,
            epoch: r.integer(8)?,
            valid_from: r.integer(4)? as u32,
            valid_until: r.integer(4)? as u32,
            public_key: r.blob(16384)?,
            capacity_domain: r.hash()?,
            capacity_limit: r.integer(8)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAK1")?;
        w.bytes(&self.identity)?;
        w.integer(self.role as u64, 1)?;
        w.integer(self.suite as u64, 2)?;
        w.integer(self.parameters as u64, 2)?;
        w.integer(self.epoch, 8)?;
        w.integer(self.valid_from as u64, 4)?;
        w.integer(self.valid_until as u64, 4)?;
        w.blob(&self.public_key, 16384)?;
        w.bytes(&self.capacity_domain)?;
        w.integer(self.capacity_limit, 8)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Policy {
    pub revision: u64,
    pub previous: Hash,
    pub interface_digest: Hash,
    pub effective_from: u32,
    pub phase: u8,
    pub suites: Vec<Suite>,
    pub max_envelope: u32,
    pub max_certificate: u32,
}
impl Wire for Policy {
    const MIN_SIZE: usize = 94;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAP1")?;
        Ok(Self {
            revision: r.integer(8)?,
            previous: r.hash()?,
            interface_digest: r.hash()?,
            effective_from: r.integer(4)? as u32,
            phase: r.integer(1)? as u8,
            suites: r.list::<Suite>(1, 2)?,
            max_envelope: r.integer(4)? as u32,
            max_certificate: r.integer(4)? as u32,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAP1")?;
        w.integer(self.revision, 8)?;
        w.bytes(&self.previous)?;
        w.bytes(&self.interface_digest)?;
        w.integer(self.effective_from as u64, 4)?;
        w.integer(self.phase as u64, 1)?;
        w.list(&self.suites, 1, 2)?;
        w.integer(self.max_envelope as u64, 4)?;
        w.integer(self.max_certificate as u64, 4)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Member {
    pub identity: Hash,
    pub stake_id: Hash,
    pub weight: u64,
    pub adnl_id: Hash,
    pub keys: Vec<Key>,
}
impl Wire for Member {
    const MIN_SIZE: usize = 105;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        Ok(Self {
            identity: r.hash()?,
            stake_id: r.hash()?,
            weight: r.integer(8)?,
            adnl_id: r.hash()?,
            keys: r.list::<Key>(1, 10)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.bytes(&self.identity)?;
        w.bytes(&self.stake_id)?;
        w.integer(self.weight, 8)?;
        w.bytes(&self.adnl_id)?;
        w.list(&self.keys, 1, 10)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Committee {
    pub policy: Hash,
    pub election: Hash,
    pub workchain: i32,
    pub shard: u64,
    pub catchain: u32,
    pub anchor_mc: u32,
    pub members: Vec<Member>,
}
impl Wire for Committee {
    const MIN_SIZE: usize = 94;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAM1")?;
        Ok(Self {
            policy: r.hash()?,
            election: r.hash()?,
            workchain: r.integer(4)? as i32,
            shard: r.integer(8)?,
            catchain: r.integer(4)? as u32,
            anchor_mc: r.integer(4)? as u32,
            members: r.list::<Member>(2, 400)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAM1")?;
        w.bytes(&self.policy)?;
        w.bytes(&self.election)?;
        w.integer(self.workchain as u64, 4)?;
        w.integer(self.shard, 8)?;
        w.integer(self.catchain as u64, 4)?;
        w.integer(self.anchor_mc as u64, 4)?;
        w.list(&self.members, 2, 400)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Duty {
    pub network: i32,
    pub genesis_root: Hash,
    pub genesis_file: Hash,
    pub policy: Hash,
    pub committee: Hash,
    pub session: Hash,
    pub workchain: i32,
    pub shard: u64,
    pub anchor_mc: u32,
    pub catchain: u32,
    pub position: u64,
    pub role: u8,
    pub payload_hash: Hash,
}
impl Wire for Duty {
    const MIN_SIZE: usize = 233;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAD1")?;
        Ok(Self {
            network: r.integer(4)? as i32,
            genesis_root: r.hash()?,
            genesis_file: r.hash()?,
            policy: r.hash()?,
            committee: r.hash()?,
            session: r.hash()?,
            workchain: r.integer(4)? as i32,
            shard: r.integer(8)?,
            anchor_mc: r.integer(4)? as u32,
            catchain: r.integer(4)? as u32,
            position: r.integer(8)?,
            role: r.integer(1)? as u8,
            payload_hash: r.hash()?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAD1")?;
        w.integer(self.network as u64, 4)?;
        w.bytes(&self.genesis_root)?;
        w.bytes(&self.genesis_file)?;
        w.bytes(&self.policy)?;
        w.bytes(&self.committee)?;
        w.bytes(&self.session)?;
        w.integer(self.workchain as u64, 4)?;
        w.integer(self.shard, 8)?;
        w.integer(self.anchor_mc as u64, 4)?;
        w.integer(self.catchain as u64, 4)?;
        w.integer(self.position, 8)?;
        w.integer(self.role as u64, 1)?;
        w.bytes(&self.payload_hash)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Statement {
    pub duty: Duty,
    pub identity: Hash,
    pub keys: Vec<Keyref>,
}
impl Wire for Statement {
    const MIN_SIZE: usize = 274;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAS1")?;
        Ok(Self { duty: Duty::read(r)?, identity: r.hash()?, keys: r.list::<Keyref>(1, 2)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAS1")?;
        self.duty.write(w)?;
        w.bytes(&self.identity)?;
        w.list(&self.keys, 1, 2)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Envelope {
    pub duty: Duty,
    pub payload: Vec<u8>,
    pub record: Record,
}
impl Wire for Envelope {
    const MIN_SIZE: usize = 278;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAE1")?;
        Ok(Self { duty: Duty::read(r)?, payload: r.blob(4096)?, record: Record::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAE1")?;
        self.duty.write(w)?;
        w.blob(&self.payload, 4096)?;
        self.record.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Certificate {
    pub duty: Duty,
    pub payload: Vec<u8>,
    pub records: Vec<Record>,
}
impl Wire for Certificate {
    const MIN_SIZE: usize = 247;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAC1")?;
        Ok(Self {
            duty: Duty::read(r)?,
            payload: r.blob(4096)?,
            records: r.list::<Record>(2, 400)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAC1")?;
        self.duty.write(w)?;
        w.blob(&self.payload, 4096)?;
        w.list(&self.records, 2, 400)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Update {
    pub operation: u8,
    pub identity: Hash,
    pub nonce: u64,
    pub previous: Hash,
    pub effective_from: u32,
    pub old_key: Hash,
    pub new_key: Vec<u8>,
    pub new_policy: Vec<u8>,
    pub operation_data: Vec<u8>,
}
impl Wire for Update {
    const MIN_SIZE: usize = 129;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAU1")?;
        Ok(Self {
            operation: r.integer(1)? as u8,
            identity: r.hash()?,
            nonce: r.integer(8)?,
            previous: r.hash()?,
            effective_from: r.integer(4)? as u32,
            old_key: r.hash()?,
            new_key: r.blob(32768)?,
            new_policy: r.blob(4096)?,
            operation_data: r.blob(4096)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAU1")?;
        w.integer(self.operation as u64, 1)?;
        w.bytes(&self.identity)?;
        w.integer(self.nonce, 8)?;
        w.bytes(&self.previous)?;
        w.integer(self.effective_from as u64, 4)?;
        w.bytes(&self.old_key)?;
        w.blob(&self.new_key, 32768)?;
        w.blob(&self.new_policy, 4096)?;
        w.blob(&self.operation_data, 4096)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Transition {
    pub operation: u8,
    pub role: u8,
    pub suite: u16,
    pub parameters: u16,
    pub old_key: Hash,
    pub new_key: Hash,
    pub effective_from: u32,
    pub accepted_at: u32,
    pub nonce: u64,
    pub predecessor: Hash,
    pub update_id: Hash,
    pub authorization_id: Hash,
}
impl Wire for Transition {
    const MIN_SIZE: usize = 190;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VATr")?;
        Ok(Self {
            operation: r.integer(1)? as u8,
            role: r.integer(1)? as u8,
            suite: r.integer(2)? as u16,
            parameters: r.integer(2)? as u16,
            old_key: r.hash()?,
            new_key: r.hash()?,
            effective_from: r.integer(4)? as u32,
            accepted_at: r.integer(4)? as u32,
            nonce: r.integer(8)?,
            predecessor: r.hash()?,
            update_id: r.hash()?,
            authorization_id: r.hash()?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VATr")?;
        w.integer(self.operation as u64, 1)?;
        w.integer(self.role as u64, 1)?;
        w.integer(self.suite as u64, 2)?;
        w.integer(self.parameters as u64, 2)?;
        w.bytes(&self.old_key)?;
        w.bytes(&self.new_key)?;
        w.integer(self.effective_from as u64, 4)?;
        w.integer(self.accepted_at as u64, 4)?;
        w.integer(self.nonce, 8)?;
        w.bytes(&self.predecessor)?;
        w.bytes(&self.update_id)?;
        w.bytes(&self.authorization_id)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Identity {
    pub identity: Hash,
    pub stake_id: Hash,
    pub owner_workchain: i32,
    pub owner_address: Hash,
    pub next_nonce: u64,
    pub previous: Hash,
    pub active: Vec<Roleref>,
    pub pending: Vec<Transition>,
}
impl Wire for Identity {
    const MIN_SIZE: usize = 150;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAI1")?;
        Ok(Self {
            identity: r.hash()?,
            stake_id: r.hash()?,
            owner_workchain: r.integer(4)? as i32,
            owner_address: r.hash()?,
            next_nonce: r.integer(8)?,
            previous: r.hash()?,
            active: r.list::<Roleref>(1, 10)?,
            pending: r.list::<Transition>(1, 10)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAI1")?;
        w.bytes(&self.identity)?;
        w.bytes(&self.stake_id)?;
        w.integer(self.owner_workchain as u64, 4)?;
        w.bytes(&self.owner_address)?;
        w.integer(self.next_nonce, 8)?;
        w.bytes(&self.previous)?;
        w.list(&self.active, 1, 10)?;
        w.list(&self.pending, 1, 10)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Activation {
    pub revision: u64,
    pub previous: Hash,
    pub next_policy: Hash,
    pub effective_from: u32,
    pub checkpoint_seqno: u32,
    pub checkpoint_root: Hash,
    pub checkpoint_file: Hash,
    pub checkpoint_state: Hash,
}
impl Wire for Activation {
    const MIN_SIZE: usize = 184;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAT1")?;
        Ok(Self {
            revision: r.integer(8)?,
            previous: r.hash()?,
            next_policy: r.hash()?,
            effective_from: r.integer(4)? as u32,
            checkpoint_seqno: r.integer(4)? as u32,
            checkpoint_root: r.hash()?,
            checkpoint_file: r.hash()?,
            checkpoint_state: r.hash()?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAT1")?;
        w.integer(self.revision, 8)?;
        w.bytes(&self.previous)?;
        w.bytes(&self.next_policy)?;
        w.integer(self.effective_from as u64, 4)?;
        w.integer(self.checkpoint_seqno as u64, 4)?;
        w.bytes(&self.checkpoint_root)?;
        w.bytes(&self.checkpoint_file)?;
        w.bytes(&self.checkpoint_state)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Observation {
    pub suite: u16,
    pub parameters: u16,
    pub registry_root: Hash,
    pub valid_from: u32,
    pub valid_until: u32,
    pub enabled: u8,
}
impl Wire for Observation {
    const MIN_SIZE: usize = 53;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAO1")?;
        Ok(Self {
            suite: r.integer(2)? as u16,
            parameters: r.integer(2)? as u16,
            registry_root: r.hash()?,
            valid_from: r.integer(4)? as u32,
            valid_until: r.integer(4)? as u32,
            enabled: r.integer(1)? as u8,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAO1")?;
        w.integer(self.suite as u64, 2)?;
        w.integer(self.parameters as u64, 2)?;
        w.bytes(&self.registry_root)?;
        w.integer(self.valid_from as u64, 4)?;
        w.integer(self.valid_until as u64, 4)?;
        w.integer(self.enabled as u64, 1)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Anchor {
    pub seqno: u32,
    pub root: Hash,
    pub file: Hash,
    pub state: Hash,
}
impl Wire for Anchor {
    const MIN_SIZE: usize = 108;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAB1")?;
        Ok(Self { seqno: r.integer(4)? as u32, root: r.hash()?, file: r.hash()?, state: r.hash()? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAB1")?;
        w.integer(self.seqno as u64, 4)?;
        w.bytes(&self.root)?;
        w.bytes(&self.file)?;
        w.bytes(&self.state)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ObjectRef {
    pub kind: u8,
    pub byte_length: u32,
    pub object_id: Hash,
    pub chunk_hashes: Vec<Hash>,
}
impl Wire for ObjectRef {
    const MIN_SIZE: usize = 46;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAOr")?;
        Ok(Self {
            kind: r.integer(1)? as u8,
            byte_length: r.integer(4)? as u32,
            object_id: r.hash()?,
            chunk_hashes: r.list::<Hash>(1, 64)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAOr")?;
        w.integer(self.kind as u64, 1)?;
        w.integer(self.byte_length as u64, 4)?;
        w.bytes(&self.object_id)?;
        w.list(&self.chunk_hashes, 1, 64)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ObjectValue {
    pub kind: u8,
    pub inline: Vec<u8>,
    pub reference: Vec<ObjectRef>,
}
impl Wire for ObjectValue {
    const MIN_SIZE: usize = 14;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAOv")?;
        Ok(Self {
            kind: r.integer(1)? as u8,
            inline: r.blob(65536)?,
            reference: r.list::<ObjectRef>(1, 1)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAOv")?;
        w.integer(self.kind as u64, 1)?;
        w.blob(&self.inline, 65536)?;
        w.list(&self.reference, 1, 1)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Proofref {
    pub anchor: Anchor,
    pub kind: u8,
    pub object_id: Hash,
    pub proof_hash: Hash,
    pub proof: ObjectValue,
}
impl Wire for Proofref {
    const MIN_SIZE: usize = 195;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAF1")?;
        Ok(Self {
            anchor: Anchor::read(r)?,
            kind: r.integer(1)? as u8,
            object_id: r.hash()?,
            proof_hash: r.hash()?,
            proof: ObjectValue::read(r)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAF1")?;
        self.anchor.write(w)?;
        w.integer(self.kind as u64, 1)?;
        w.bytes(&self.object_id)?;
        w.bytes(&self.proof_hash)?;
        self.proof.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct OwnerAuth {
    pub update_id: Hash,
    pub stake_id: Hash,
    pub owner_workchain: i32,
    pub owner_address: Hash,
    pub proof: Proofref,
}
impl Wire for OwnerAuth {
    const MIN_SIZE: usize = 303;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAOw")?;
        Ok(Self {
            update_id: r.hash()?,
            stake_id: r.hash()?,
            owner_workchain: r.integer(4)? as i32,
            owner_address: r.hash()?,
            proof: Proofref::read(r)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAOw")?;
        w.bytes(&self.update_id)?;
        w.bytes(&self.stake_id)?;
        w.integer(self.owner_workchain as u64, 4)?;
        w.bytes(&self.owner_address)?;
        self.proof.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PossessionAuth {
    pub update_id: Hash,
    pub key: Keyref,
    pub signature: Vec<u8>,
}
impl Wire for PossessionAuth {
    const MIN_SIZE: usize = 88;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAPo")?;
        Ok(Self { update_id: r.hash()?, key: Keyref::read(r)?, signature: r.blob(65536)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAPo")?;
        w.bytes(&self.update_id)?;
        self.key.write(w)?;
        w.blob(&self.signature, 65536)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct IdentityAuth {
    pub update_id: Hash,
    pub identity: Hash,
    pub certificate: ObjectValue,
}
impl Wire for IdentityAuth {
    const MIN_SIZE: usize = 86;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAAd")?;
        Ok(Self { update_id: r.hash()?, identity: r.hash()?, certificate: ObjectValue::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAAd")?;
        w.bytes(&self.update_id)?;
        w.bytes(&self.identity)?;
        self.certificate.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct GovernanceAuth {
    pub update_id: Hash,
    pub committee: Hash,
    pub certificate: ObjectValue,
}
impl Wire for GovernanceAuth {
    const MIN_SIZE: usize = 86;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAGo")?;
        Ok(Self { update_id: r.hash()?, committee: r.hash()?, certificate: ObjectValue::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAGo")?;
        w.bytes(&self.update_id)?;
        w.bytes(&self.committee)?;
        self.certificate.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Authorizations {
    pub owner: Vec<OwnerAuth>,
    pub possession: Vec<PossessionAuth>,
    pub administration: Vec<IdentityAuth>,
    pub governance: Vec<GovernanceAuth>,
}
impl Wire for Authorizations {
    const MIN_SIZE: usize = 12;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAA1")?;
        Ok(Self {
            owner: r.list::<OwnerAuth>(1, 1)?,
            possession: r.list::<PossessionAuth>(1, 1)?,
            administration: r.list::<IdentityAuth>(1, 1)?,
            governance: r.list::<GovernanceAuth>(1, 1)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAA1")?;
        w.list(&self.owner, 1, 1)?;
        w.list(&self.possession, 1, 1)?;
        w.list(&self.administration, 1, 1)?;
        w.list(&self.governance, 1, 1)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PermitBody {
    pub issuer: Hash,
    pub service_policy: Hash,
    pub audience: Hash,
    pub network: i32,
    pub genesis_root: Hash,
    pub genesis_file: Hash,
    pub anchor: Anchor,
    pub registry_root: Hash,
    pub policy: Hash,
    pub committee: Hash,
    pub session: Hash,
    pub identity: Hash,
    pub method: u8,
    pub subject: Hash,
    pub expires_mc: u32,
    pub fence: u64,
}
impl Wire for PermitBody {
    const MIN_SIZE: usize = 485;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAPb")?;
        Ok(Self {
            issuer: r.hash()?,
            service_policy: r.hash()?,
            audience: r.hash()?,
            network: r.integer(4)? as i32,
            genesis_root: r.hash()?,
            genesis_file: r.hash()?,
            anchor: Anchor::read(r)?,
            registry_root: r.hash()?,
            policy: r.hash()?,
            committee: r.hash()?,
            session: r.hash()?,
            identity: r.hash()?,
            method: r.integer(1)? as u8,
            subject: r.hash()?,
            expires_mc: r.integer(4)? as u32,
            fence: r.integer(8)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAPb")?;
        w.bytes(&self.issuer)?;
        w.bytes(&self.service_policy)?;
        w.bytes(&self.audience)?;
        w.integer(self.network as u64, 4)?;
        w.bytes(&self.genesis_root)?;
        w.bytes(&self.genesis_file)?;
        self.anchor.write(w)?;
        w.bytes(&self.registry_root)?;
        w.bytes(&self.policy)?;
        w.bytes(&self.committee)?;
        w.bytes(&self.session)?;
        w.bytes(&self.identity)?;
        w.integer(self.method as u64, 1)?;
        w.bytes(&self.subject)?;
        w.integer(self.expires_mc as u64, 4)?;
        w.integer(self.fence, 8)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ServiceComponent {
    pub suite: u16,
    pub parameters: u16,
    pub key_id: Hash,
    pub signature: Vec<u8>,
}
impl Wire for ServiceComponent {
    const MIN_SIZE: usize = 40;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        Ok(Self {
            suite: r.integer(2)? as u16,
            parameters: r.integer(2)? as u16,
            key_id: r.hash()?,
            signature: r.blob(65536)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.integer(self.suite as u64, 2)?;
        w.integer(self.parameters as u64, 2)?;
        w.bytes(&self.key_id)?;
        w.blob(&self.signature, 65536)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Permit {
    pub body: PermitBody,
    pub components: Vec<ServiceComponent>,
}
impl Wire for Permit {
    const MIN_SIZE: usize = 494;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAPt")?;
        Ok(Self { body: PermitBody::read(r)?, components: r.list::<ServiceComponent>(1, 2)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAPt")?;
        self.body.write(w)?;
        w.list(&self.components, 1, 2)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ReceiptBody {
    pub issuer: Hash,
    pub service_policy: Hash,
    pub audience: Hash,
    pub request_id: Hash,
    pub method: u8,
    pub subject: Hash,
    pub result_hash: Hash,
    pub journal_sequence: u64,
    pub fence: u64,
    pub state: u8,
    pub context_id: Hash,
}
impl Wire for ReceiptBody {
    const MIN_SIZE: usize = 250;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VARb")?;
        Ok(Self {
            issuer: r.hash()?,
            service_policy: r.hash()?,
            audience: r.hash()?,
            request_id: r.hash()?,
            method: r.integer(1)? as u8,
            subject: r.hash()?,
            result_hash: r.hash()?,
            journal_sequence: r.integer(8)?,
            fence: r.integer(8)?,
            state: r.integer(1)? as u8,
            context_id: r.hash()?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VARb")?;
        w.bytes(&self.issuer)?;
        w.bytes(&self.service_policy)?;
        w.bytes(&self.audience)?;
        w.bytes(&self.request_id)?;
        w.integer(self.method as u64, 1)?;
        w.bytes(&self.subject)?;
        w.bytes(&self.result_hash)?;
        w.integer(self.journal_sequence, 8)?;
        w.integer(self.fence, 8)?;
        w.integer(self.state as u64, 1)?;
        w.bytes(&self.context_id)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Receipt {
    pub body: ReceiptBody,
    pub components: Vec<ServiceComponent>,
}
impl Wire for Receipt {
    const MIN_SIZE: usize = 259;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VARt")?;
        Ok(Self { body: ReceiptBody::read(r)?, components: r.list::<ServiceComponent>(1, 2)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VARt")?;
        self.body.write(w)?;
        w.list(&self.components, 1, 2)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Capabilities {
    pub interface_digest: Hash,
    pub installed: Vec<Suite>,
    pub admitted: Vec<Suite>,
    pub max_request: u32,
    pub max_result: u32,
    pub persistent_journal: u8,
    pub fencing: u8,
    pub stateful: u8,
}
impl Wire for Capabilities {
    const MIN_SIZE: usize = 53;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAc1")?;
        Ok(Self {
            interface_digest: r.hash()?,
            installed: r.list::<Suite>(1, 2)?,
            admitted: r.list::<Suite>(1, 2)?,
            max_request: r.integer(4)? as u32,
            max_result: r.integer(4)? as u32,
            persistent_journal: r.integer(1)? as u8,
            fencing: r.integer(1)? as u8,
            stateful: r.integer(1)? as u8,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAc1")?;
        w.bytes(&self.interface_digest)?;
        w.list(&self.installed, 1, 2)?;
        w.list(&self.admitted, 1, 2)?;
        w.integer(self.max_request as u64, 4)?;
        w.integer(self.max_result as u64, 4)?;
        w.integer(self.persistent_journal as u64, 1)?;
        w.integer(self.fencing as u64, 1)?;
        w.integer(self.stateful as u64, 1)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ApiError {
    pub request_id: Hash,
    pub method: u8,
    pub code: u16,
    pub retryable: u8,
    pub request_state: u8,
    pub message: Vec<u8>,
}
impl Wire for ApiError {
    const MIN_SIZE: usize = 49;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAEr")?;
        Ok(Self {
            request_id: r.hash()?,
            method: r.integer(1)? as u8,
            code: r.integer(2)? as u16,
            retryable: r.integer(1)? as u8,
            request_state: r.integer(1)? as u8,
            message: r.blob(256)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAEr")?;
        w.bytes(&self.request_id)?;
        w.integer(self.method as u64, 1)?;
        w.integer(self.code as u64, 2)?;
        w.integer(self.retryable as u64, 1)?;
        w.integer(self.request_state as u64, 1)?;
        w.blob(&self.message, 256)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct Cursor {
    pub anchor: Anchor,
    pub query_id: Hash,
    pub last_identity: Hash,
}
impl Wire for Cursor {
    const MIN_SIZE: usize = 180;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VACu")?;
        Ok(Self { anchor: Anchor::read(r)?, query_id: r.hash()?, last_identity: r.hash()? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VACu")?;
        self.anchor.write(w)?;
        w.bytes(&self.query_id)?;
        w.bytes(&self.last_identity)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct KeyHandle {
    pub key: Key,
    pub handle: Hash,
}
impl Wire for KeyHandle {
    const MIN_SIZE: usize = 145;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAKh")?;
        Ok(Self { key: Key::read(r)?, handle: r.hash()? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAKh")?;
        self.key.write(w)?;
        w.bytes(&self.handle)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SignResult {
    pub request_id: Hash,
    pub statement_id: Hash,
    pub record: Record,
    pub fence: u64,
    pub receipt: Receipt,
}
impl Wire for SignResult {
    const MIN_SIZE: usize = 372;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VASr")?;
        Ok(Self {
            request_id: r.hash()?,
            statement_id: r.hash()?,
            record: Record::read(r)?,
            fence: r.integer(8)?,
            receipt: Receipt::read(r)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VASr")?;
        w.bytes(&self.request_id)?;
        w.bytes(&self.statement_id)?;
        self.record.write(w)?;
        w.integer(self.fence, 8)?;
        self.receipt.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RequestState {
    pub request_id: Hash,
    pub state: u8,
    pub statement_id: Hash,
    pub fence: u64,
    pub result: Vec<SignResult>,
    pub receipt: Vec<Receipt>,
}
impl Wire for RequestState {
    const MIN_SIZE: usize = 83;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAQs")?;
        Ok(Self {
            request_id: r.hash()?,
            state: r.integer(1)? as u8,
            statement_id: r.hash()?,
            fence: r.integer(8)?,
            result: r.list::<SignResult>(1, 1)?,
            receipt: r.list::<Receipt>(1, 1)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAQs")?;
        w.bytes(&self.request_id)?;
        w.integer(self.state as u64, 1)?;
        w.bytes(&self.statement_id)?;
        w.integer(self.fence, 8)?;
        w.list(&self.result, 1, 1)?;
        w.list(&self.receipt, 1, 1)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ProfileResult {
    pub anchor: Anchor,
    pub interface_digest: Hash,
    pub policy: Hash,
    pub installed: Vec<Suite>,
    pub active: Vec<Suite>,
    pub can_parse: u8,
    pub can_verify: u8,
    pub proof: Proofref,
}
impl Wire for ProfileResult {
    const MIN_SIZE: usize = 379;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAPr")?;
        Ok(Self {
            anchor: Anchor::read(r)?,
            interface_digest: r.hash()?,
            policy: r.hash()?,
            installed: r.list::<Suite>(1, 2)?,
            active: r.list::<Suite>(1, 2)?,
            can_parse: r.integer(1)? as u8,
            can_verify: r.integer(1)? as u8,
            proof: Proofref::read(r)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAPr")?;
        self.anchor.write(w)?;
        w.bytes(&self.interface_digest)?;
        w.bytes(&self.policy)?;
        w.list(&self.installed, 1, 2)?;
        w.list(&self.active, 1, 2)?;
        w.integer(self.can_parse as u64, 1)?;
        w.integer(self.can_verify as u64, 1)?;
        self.proof.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PolicyResult {
    pub anchor: Anchor,
    pub policy: Policy,
    pub proof: Proofref,
}
impl Wire for PolicyResult {
    const MIN_SIZE: usize = 405;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAPl")?;
        Ok(Self { anchor: Anchor::read(r)?, policy: Policy::read(r)?, proof: Proofref::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAPl")?;
        self.anchor.write(w)?;
        self.policy.write(w)?;
        self.proof.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RegistryResult {
    pub anchor: Anchor,
    pub query_id: Hash,
    pub identities: Vec<Identity>,
    pub cursor: Vec<Cursor>,
    pub proof: Proofref,
}
impl Wire for RegistryResult {
    const MIN_SIZE: usize = 345;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VARg")?;
        Ok(Self {
            anchor: Anchor::read(r)?,
            query_id: r.hash()?,
            identities: r.list::<Identity>(1, 128)?,
            cursor: r.list::<Cursor>(1, 1)?,
            proof: Proofref::read(r)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VARg")?;
        self.anchor.write(w)?;
        w.bytes(&self.query_id)?;
        w.list(&self.identities, 1, 128)?;
        w.list(&self.cursor, 1, 1)?;
        self.proof.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct KeyResult {
    pub anchor: Anchor,
    pub key: Key,
    pub proof: Proofref,
}
impl Wire for KeyResult {
    const MIN_SIZE: usize = 416;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAKr")?;
        Ok(Self { anchor: Anchor::read(r)?, key: Key::read(r)?, proof: Proofref::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAKr")?;
        self.anchor.write(w)?;
        self.key.write(w)?;
        self.proof.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct CertificateResult {
    pub anchor: Anchor,
    pub era: u8,
    pub interface_digest: Hash,
    pub certificate: ObjectValue,
    pub committee: Proofref,
    pub policy: Proofref,
}
impl Wire for CertificateResult {
    const MIN_SIZE: usize = 553;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VACr")?;
        Ok(Self {
            anchor: Anchor::read(r)?,
            era: r.integer(1)? as u8,
            interface_digest: r.hash()?,
            certificate: ObjectValue::read(r)?,
            committee: Proofref::read(r)?,
            policy: Proofref::read(r)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VACr")?;
        self.anchor.write(w)?;
        w.integer(self.era as u64, 1)?;
        w.bytes(&self.interface_digest)?;
        self.certificate.write(w)?;
        self.committee.write(w)?;
        self.policy.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct VerifyResult {
    pub anchor: Anchor,
    pub certificate_id: Hash,
    pub policy: Hash,
    pub committee: Hash,
    pub duty: Hash,
    pub signers: Vec<Hash>,
    pub weight: u64,
}
impl Wire for VerifyResult {
    const MIN_SIZE: usize = 254;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAVr")?;
        Ok(Self {
            anchor: Anchor::read(r)?,
            certificate_id: r.hash()?,
            policy: r.hash()?,
            committee: r.hash()?,
            duty: r.hash()?,
            signers: r.list::<Hash>(2, 400)?,
            weight: r.integer(8)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAVr")?;
        self.anchor.write(w)?;
        w.bytes(&self.certificate_id)?;
        w.bytes(&self.policy)?;
        w.bytes(&self.committee)?;
        w.bytes(&self.duty)?;
        w.list(&self.signers, 2, 400)?;
        w.integer(self.weight, 8)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct CapabilitiesRequest {}
impl Wire for CapabilitiesRequest {
    const MIN_SIZE: usize = 8;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAq1")?;
        Ok(Self {})
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAq1")?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PublicRequest {
    pub key_id: Hash,
}
impl Wire for PublicRequest {
    const MIN_SIZE: usize = 40;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAq2")?;
        Ok(Self { key_id: r.hash()? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAq2")?;
        w.bytes(&self.key_id)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PrepareRequest {
    pub preparation_id: Hash,
    pub identity: Hash,
    pub role: u8,
    pub suite: u16,
    pub parameters: u16,
    pub epoch: u64,
    pub valid_from: u32,
    pub valid_until: u32,
    pub mode: u8,
    pub provider_handle: Hash,
    pub fence: u64,
}
impl Wire for PrepareRequest {
    const MIN_SIZE: usize = 134;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAq3")?;
        Ok(Self {
            preparation_id: r.hash()?,
            identity: r.hash()?,
            role: r.integer(1)? as u8,
            suite: r.integer(2)? as u16,
            parameters: r.integer(2)? as u16,
            epoch: r.integer(8)?,
            valid_from: r.integer(4)? as u32,
            valid_until: r.integer(4)? as u32,
            mode: r.integer(1)? as u8,
            provider_handle: r.hash()?,
            fence: r.integer(8)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAq3")?;
        w.bytes(&self.preparation_id)?;
        w.bytes(&self.identity)?;
        w.integer(self.role as u64, 1)?;
        w.integer(self.suite as u64, 2)?;
        w.integer(self.parameters as u64, 2)?;
        w.integer(self.epoch, 8)?;
        w.integer(self.valid_from as u64, 4)?;
        w.integer(self.valid_until as u64, 4)?;
        w.integer(self.mode as u64, 1)?;
        w.bytes(&self.provider_handle)?;
        w.integer(self.fence, 8)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct StageRequest {
    pub key: Key,
    pub handle: Hash,
    pub update: Update,
    pub authorizations: Authorizations,
    pub permit: Permit,
    pub fence: u64,
}
impl Wire for StageRequest {
    const MIN_SIZE: usize = 788;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAq4")?;
        Ok(Self {
            key: Key::read(r)?,
            handle: r.hash()?,
            update: Update::read(r)?,
            authorizations: Authorizations::read(r)?,
            permit: Permit::read(r)?,
            fence: r.integer(8)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAq4")?;
        self.key.write(w)?;
        w.bytes(&self.handle)?;
        self.update.write(w)?;
        self.authorizations.write(w)?;
        self.permit.write(w)?;
        w.integer(self.fence, 8)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SignRequest {
    pub request_id: Hash,
    pub key_handles: Vec<Hash>,
    pub envelope_template: Vec<u8>,
    pub permit: Permit,
    pub fence: u64,
}
impl Wire for SignRequest {
    const MIN_SIZE: usize = 547;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAq5")?;
        Ok(Self {
            request_id: r.hash()?,
            key_handles: r.list::<Hash>(1, 2)?,
            envelope_template: r.blob(262144)?,
            permit: Permit::read(r)?,
            fence: r.integer(8)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAq5")?;
        w.bytes(&self.request_id)?;
        w.list(&self.key_handles, 1, 2)?;
        w.blob(&self.envelope_template, 262144)?;
        self.permit.write(w)?;
        w.integer(self.fence, 8)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ResultRequest {
    pub request_id: Hash,
}
impl Wire for ResultRequest {
    const MIN_SIZE: usize = 40;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAq6")?;
        Ok(Self { request_id: r.hash()? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAq6")?;
        w.bytes(&self.request_id)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RetireRequest {
    pub key_id: Hash,
    pub update: Update,
    pub authorizations: Authorizations,
    pub permit: Permit,
    pub fence: u64,
}
impl Wire for RetireRequest {
    const MIN_SIZE: usize = 683;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAq7")?;
        Ok(Self {
            key_id: r.hash()?,
            update: Update::read(r)?,
            authorizations: Authorizations::read(r)?,
            permit: Permit::read(r)?,
            fence: r.integer(8)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAq7")?;
        w.bytes(&self.key_id)?;
        self.update.write(w)?;
        self.authorizations.write(w)?;
        self.permit.write(w)?;
        w.integer(self.fence, 8)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PrepareResult {
    pub prepared: KeyHandle,
    pub receipt: Receipt,
}
impl Wire for PrepareResult {
    const MIN_SIZE: usize = 412;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAk3")?;
        Ok(Self { prepared: KeyHandle::read(r)?, receipt: Receipt::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAk3")?;
        self.prepared.write(w)?;
        self.receipt.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct StageResult {
    pub key: Key,
    pub possession: PossessionAuth,
    pub receipt: Receipt,
}
impl Wire for StageResult {
    const MIN_SIZE: usize = 460;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAk4")?;
        Ok(Self {
            key: Key::read(r)?,
            possession: PossessionAuth::read(r)?,
            receipt: Receipt::read(r)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAk4")?;
        self.key.write(w)?;
        self.possession.write(w)?;
        self.receipt.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RetireResult {
    pub key_id: Hash,
    pub update_id: Hash,
    pub receipt: Receipt,
}
impl Wire for RetireResult {
    const MIN_SIZE: usize = 331;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAk7")?;
        Ok(Self { key_id: r.hash()?, update_id: r.hash()?, receipt: Receipt::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAk7")?;
        w.bytes(&self.key_id)?;
        w.bytes(&self.update_id)?;
        self.receipt.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct GetProfileRequest {
    pub anchor: Anchor,
}
impl Wire for GetProfileRequest {
    const MIN_SIZE: usize = 116;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAq8")?;
        Ok(Self { anchor: Anchor::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAq8")?;
        self.anchor.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct GetPolicyRequest {
    pub anchor: Anchor,
    pub policy_id: Hash,
}
impl Wire for GetPolicyRequest {
    const MIN_SIZE: usize = 148;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAq9")?;
        Ok(Self { anchor: Anchor::read(r)?, policy_id: r.hash()? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAq9")?;
        self.anchor.write(w)?;
        w.bytes(&self.policy_id)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct GetRegistryRequest {
    pub anchor: Anchor,
    pub limit: u8,
    pub cursor: Vec<Cursor>,
}
impl Wire for GetRegistryRequest {
    const MIN_SIZE: usize = 118;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAqa")?;
        Ok(Self {
            anchor: Anchor::read(r)?,
            limit: r.integer(1)? as u8,
            cursor: r.list::<Cursor>(1, 1)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAqa")?;
        self.anchor.write(w)?;
        w.integer(self.limit as u64, 1)?;
        w.list(&self.cursor, 1, 1)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct GetKeyRequest {
    pub anchor: Anchor,
    pub key_id: Hash,
}
impl Wire for GetKeyRequest {
    const MIN_SIZE: usize = 148;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAqb")?;
        Ok(Self { anchor: Anchor::read(r)?, key_id: r.hash()? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAqb")?;
        self.anchor.write(w)?;
        w.bytes(&self.key_id)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct GetCertificateRequest {
    pub anchor: Anchor,
    pub certificate_id: Hash,
}
impl Wire for GetCertificateRequest {
    const MIN_SIZE: usize = 148;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAqc")?;
        Ok(Self { anchor: Anchor::read(r)?, certificate_id: r.hash()? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAqc")?;
        self.anchor.write(w)?;
        w.bytes(&self.certificate_id)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct VerifyCertificateRequest {
    pub anchor: Anchor,
    pub certificate: ObjectValue,
    pub committee: Proofref,
    pub policy: Proofref,
}
impl Wire for VerifyCertificateRequest {
    const MIN_SIZE: usize = 520;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAqd")?;
        Ok(Self {
            anchor: Anchor::read(r)?,
            certificate: ObjectValue::read(r)?,
            committee: Proofref::read(r)?,
            policy: Proofref::read(r)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAqd")?;
        self.anchor.write(w)?;
        self.certificate.write(w)?;
        self.committee.write(w)?;
        self.policy.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct SignResultBody {
    pub request_id: Hash,
    pub statement_id: Hash,
    pub record: Record,
    pub fence: u64,
}
impl Wire for SignResultBody {
    const MIN_SIZE: usize = 113;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VASb")?;
        Ok(Self {
            request_id: r.hash()?,
            statement_id: r.hash()?,
            record: Record::read(r)?,
            fence: r.integer(8)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VASb")?;
        w.bytes(&self.request_id)?;
        w.bytes(&self.statement_id)?;
        self.record.write(w)?;
        w.integer(self.fence, 8)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PrepareResultBody {
    pub prepared: KeyHandle,
}
impl Wire for PrepareResultBody {
    const MIN_SIZE: usize = 153;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAkb")?;
        Ok(Self { prepared: KeyHandle::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAkb")?;
        self.prepared.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct StageResultBody {
    pub key: Key,
    pub possession: PossessionAuth,
}
impl Wire for StageResultBody {
    const MIN_SIZE: usize = 201;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAsb")?;
        Ok(Self { key: Key::read(r)?, possession: PossessionAuth::read(r)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAsb")?;
        self.key.write(w)?;
        self.possession.write(w)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RetireResultBody {
    pub key_id: Hash,
    pub update_id: Hash,
}
impl Wire for RetireResultBody {
    const MIN_SIZE: usize = 72;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VArb")?;
        Ok(Self { key_id: r.hash()?, update_id: r.hash()? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VArb")?;
        w.bytes(&self.key_id)?;
        w.bytes(&self.update_id)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ProfileState {
    pub interface_digest: Hash,
    pub policy: Hash,
    pub active: Vec<Suite>,
}
impl Wire for ProfileState {
    const MIN_SIZE: usize = 73;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAPs")?;
        Ok(Self { interface_digest: r.hash()?, policy: r.hash()?, active: r.list::<Suite>(1, 2)? })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAPs")?;
        w.bytes(&self.interface_digest)?;
        w.bytes(&self.policy)?;
        w.list(&self.active, 1, 2)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ChunkRequest {
    pub anchor: Anchor,
    pub manifest: ObjectRef,
    pub index: u8,
}
impl Wire for ChunkRequest {
    const MIN_SIZE: usize = 163;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAqe")?;
        Ok(Self {
            anchor: Anchor::read(r)?,
            manifest: ObjectRef::read(r)?,
            index: r.integer(1)? as u8,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAqe")?;
        self.anchor.write(w)?;
        self.manifest.write(w)?;
        w.integer(self.index as u64, 1)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ChunkResult {
    pub anchor: Anchor,
    pub manifest_id: Hash,
    pub index: u8,
    pub data: Vec<u8>,
}
impl Wire for ChunkResult {
    const MIN_SIZE: usize = 153;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VARe")?;
        Ok(Self {
            anchor: Anchor::read(r)?,
            manifest_id: r.hash()?,
            index: r.integer(1)? as u8,
            data: r.blob(1048576)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VARe")?;
        self.anchor.write(w)?;
        w.bytes(&self.manifest_id)?;
        w.integer(self.index as u64, 1)?;
        w.blob(&self.data, 1048576)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PutChunkRequest {
    pub anchor: Anchor,
    pub manifest: ObjectRef,
    pub index: u8,
    pub data: Vec<u8>,
}
impl Wire for PutChunkRequest {
    const MIN_SIZE: usize = 167;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VAqf")?;
        Ok(Self {
            anchor: Anchor::read(r)?,
            manifest: ObjectRef::read(r)?,
            index: r.integer(1)? as u8,
            data: r.blob(1048576)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VAqf")?;
        self.anchor.write(w)?;
        self.manifest.write(w)?;
        w.integer(self.index as u64, 1)?;
        w.blob(&self.data, 1048576)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct PutChunkResult {
    pub anchor: Anchor,
    pub manifest_id: Hash,
    pub index: u8,
}
impl Wire for PutChunkResult {
    const MIN_SIZE: usize = 149;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VARf")?;
        Ok(Self { anchor: Anchor::read(r)?, manifest_id: r.hash()?, index: r.integer(1)? as u8 })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VARf")?;
        self.anchor.write(w)?;
        w.bytes(&self.manifest_id)?;
        w.integer(self.index as u64, 1)?;
        Ok(())
    }
}
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct ServicePolicy {
    pub issuer: Hash,
    pub revision: u64,
    pub previous: Hash,
    pub suites: Vec<Suite>,
}
impl Wire for ServicePolicy {
    const MIN_SIZE: usize = 81;
    fn read(r: &mut Reader) -> Result<Self, Error> {
        r.header(b"VASp")?;
        Ok(Self {
            issuer: r.hash()?,
            revision: r.integer(8)?,
            previous: r.hash()?,
            suites: r.list::<Suite>(1, 2)?,
        })
    }
    fn write(&self, w: &mut Writer) -> Result<(), Error> {
        w.header(b"VASp")?;
        w.bytes(&self.issuer)?;
        w.integer(self.revision, 8)?;
        w.bytes(&self.previous)?;
        w.list(&self.suites, 1, 2)?;
        Ok(())
    }
}
