[package]
name = "chain-rpc-client"
version = "0.3.0"
edition = "2024"
license = 'GPL-3.0'

[dependencies]
serde = { version = "1.0" }
serde_json = "1.0.145"
base64 = "0.22"
hex = "0.4"
anyhow = "1.0"
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }
url = "2.5"
chain_block = { path = "../../block" }
tl_api = { path = "../../tl/api" }
common = { path = "../common" }
chain_rpc_rs = { package = "toscenter-rs", path = "../../toscenter-rs" }

[dev-dependencies]
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "net",
    "io-util",
] }
