/* TOS Network - Avata default opcode gas schedule for the v1 contract profile.
 *
 * These costs are the standalone defaults used before ConfigParam 85 is loaded.
 * Every slot must be in [1, UINT64_MAX-1] (zero and UINT64_MAX are reserved).
 * Governance can override the table via avata_set_opcode_gas_costs().
 */

#ifndef AVATA_GAS_SCHEDULE_H
#define AVATA_GAS_SCHEDULE_H

#include <stdint.h>

/* Tier constants — grouped by computational complexity. */
#define TOS_GAS_NOP          1  /* nop, constant pushes, aconst_null */
#define TOS_GAS_STACK        1  /* load/store locals, dup/pop/swap, bipush/sipush/ldc */
#define TOS_GAS_INT_ARITH    2  /* iadd/isub/imul/ineg/iand/ior/ixor/ishl/ishr/iushr/iinc */
#define TOS_GAS_LONG_ARITH   2  /* ladd/lsub/lmul/lneg/land/lor/lxor/lshl/lshr/lushr */
#define TOS_GAS_FLOAT_ARITH  3  /* fadd/fsub/fmul/fdiv/frem/fneg */
#define TOS_GAS_DOUBLE_ARITH 3  /* dadd/dsub/dmul/ddiv/drem/dneg */
#define TOS_GAS_DIV          5  /* idiv/irem/ldiv/lrem — variable latency */
#define TOS_GAS_CONVERT      2  /* i2l/i2f/i2d/l2i/l2f/l2d/f2i/f2l/f2d/d2i/d2l/d2f/i2b/i2c/i2s */
#define TOS_GAS_COMPARE      2  /* lcmp/fcmpg/fcmpl/dcmpg/dcmpl */
#define TOS_GAS_BRANCH       2  /* ifXX/goto/jsr/ret/tableswitch/lookupswitch */
#define TOS_GAS_RETURN       1  /* ireturn/lreturn/freturn/dreturn/areturn/return */
#define TOS_GAS_FIELD        3  /* getstatic/putstatic/getfield/putfield */
#define TOS_GAS_INVOKE      10  /* invokevirtual/invokespecial/invokestatic/invokeinterface/invokedynamic */
#define TOS_GAS_ALLOC        5  /* new/newarray/anewarray/multianewarray (base; helper adds per-word/element) */
#define TOS_GAS_ARRAY_ACCESS 2  /* xaload/xastore */
#define TOS_GAS_THROW       10  /* athrow */
#define TOS_GAS_TYPECHECK    5  /* checkcast/instanceof */
#define TOS_GAS_MONITOR      3  /* monitorenter/monitorexit */
#define TOS_GAS_DEFAULT      1  /* unused/reserved opcode slots */

/*
 * Default per-opcode cost table indexed by opcode byte value [0..255].
 * Defined as a static const array so it can be included once in machine.cpp.
 */
#ifdef AVATA_GAS_SCHEDULE_DEFINE_TABLE

static const uint64_t kTosDefaultOpcodeGasCosts[256] = {
    /* 0x00 nop            */ TOS_GAS_NOP,
    /* 0x01 aconst_null    */ TOS_GAS_NOP,
    /* 0x02 iconst_m1      */ TOS_GAS_NOP,
    /* 0x03 iconst_0       */ TOS_GAS_NOP,
    /* 0x04 iconst_1       */ TOS_GAS_NOP,
    /* 0x05 iconst_2       */ TOS_GAS_NOP,
    /* 0x06 iconst_3       */ TOS_GAS_NOP,
    /* 0x07 iconst_4       */ TOS_GAS_NOP,
    /* 0x08 iconst_5       */ TOS_GAS_NOP,
    /* 0x09 lconst_0       */ TOS_GAS_NOP,
    /* 0x0a lconst_1       */ TOS_GAS_NOP,
    /* 0x0b fconst_0       */ TOS_GAS_NOP,
    /* 0x0c fconst_1       */ TOS_GAS_NOP,
    /* 0x0d fconst_2       */ TOS_GAS_NOP,
    /* 0x0e dconst_0       */ TOS_GAS_NOP,
    /* 0x0f dconst_1       */ TOS_GAS_NOP,
    /* 0x10 bipush         */ TOS_GAS_STACK,
    /* 0x11 sipush         */ TOS_GAS_STACK,
    /* 0x12 ldc            */ TOS_GAS_STACK,
    /* 0x13 ldc_w          */ TOS_GAS_STACK,
    /* 0x14 ldc2_w         */ TOS_GAS_STACK,
    /* 0x15 iload          */ TOS_GAS_STACK,
    /* 0x16 lload          */ TOS_GAS_STACK,
    /* 0x17 fload          */ TOS_GAS_STACK,
    /* 0x18 dload          */ TOS_GAS_STACK,
    /* 0x19 aload          */ TOS_GAS_STACK,
    /* 0x1a iload_0        */ TOS_GAS_STACK,
    /* 0x1b iload_1        */ TOS_GAS_STACK,
    /* 0x1c iload_2        */ TOS_GAS_STACK,
    /* 0x1d iload_3        */ TOS_GAS_STACK,
    /* 0x1e lload_0        */ TOS_GAS_STACK,
    /* 0x1f lload_1        */ TOS_GAS_STACK,
    /* 0x20 lload_2        */ TOS_GAS_STACK,
    /* 0x21 lload_3        */ TOS_GAS_STACK,
    /* 0x22 fload_0        */ TOS_GAS_STACK,
    /* 0x23 fload_1        */ TOS_GAS_STACK,
    /* 0x24 fload_2        */ TOS_GAS_STACK,
    /* 0x25 fload_3        */ TOS_GAS_STACK,
    /* 0x26 dload_0        */ TOS_GAS_STACK,
    /* 0x27 dload_1        */ TOS_GAS_STACK,
    /* 0x28 dload_2        */ TOS_GAS_STACK,
    /* 0x29 dload_3        */ TOS_GAS_STACK,
    /* 0x2a aload_0        */ TOS_GAS_STACK,
    /* 0x2b aload_1        */ TOS_GAS_STACK,
    /* 0x2c aload_2        */ TOS_GAS_STACK,
    /* 0x2d aload_3        */ TOS_GAS_STACK,
    /* 0x2e iaload         */ TOS_GAS_ARRAY_ACCESS,
    /* 0x2f laload         */ TOS_GAS_ARRAY_ACCESS,
    /* 0x30 faload         */ TOS_GAS_ARRAY_ACCESS,
    /* 0x31 daload         */ TOS_GAS_ARRAY_ACCESS,
    /* 0x32 aaload         */ TOS_GAS_ARRAY_ACCESS,
    /* 0x33 baload         */ TOS_GAS_ARRAY_ACCESS,
    /* 0x34 caload         */ TOS_GAS_ARRAY_ACCESS,
    /* 0x35 saload         */ TOS_GAS_ARRAY_ACCESS,
    /* 0x36 istore         */ TOS_GAS_STACK,
    /* 0x37 lstore         */ TOS_GAS_STACK,
    /* 0x38 fstore         */ TOS_GAS_STACK,
    /* 0x39 dstore         */ TOS_GAS_STACK,
    /* 0x3a astore         */ TOS_GAS_STACK,
    /* 0x3b istore_0       */ TOS_GAS_STACK,
    /* 0x3c istore_1       */ TOS_GAS_STACK,
    /* 0x3d istore_2       */ TOS_GAS_STACK,
    /* 0x3e istore_3       */ TOS_GAS_STACK,
    /* 0x3f lstore_0       */ TOS_GAS_STACK,
    /* 0x40 lstore_1       */ TOS_GAS_STACK,
    /* 0x41 lstore_2       */ TOS_GAS_STACK,
    /* 0x42 lstore_3       */ TOS_GAS_STACK,
    /* 0x43 fstore_0       */ TOS_GAS_STACK,
    /* 0x44 fstore_1       */ TOS_GAS_STACK,
    /* 0x45 fstore_2       */ TOS_GAS_STACK,
    /* 0x46 fstore_3       */ TOS_GAS_STACK,
    /* 0x47 dstore_0       */ TOS_GAS_STACK,
    /* 0x48 dstore_1       */ TOS_GAS_STACK,
    /* 0x49 dstore_2       */ TOS_GAS_STACK,
    /* 0x4a dstore_3       */ TOS_GAS_STACK,
    /* 0x4b astore_0       */ TOS_GAS_STACK,
    /* 0x4c astore_1       */ TOS_GAS_STACK,
    /* 0x4d astore_2       */ TOS_GAS_STACK,
    /* 0x4e astore_3       */ TOS_GAS_STACK,
    /* 0x4f iastore        */ TOS_GAS_ARRAY_ACCESS,
    /* 0x50 lastore        */ TOS_GAS_ARRAY_ACCESS,
    /* 0x51 fastore        */ TOS_GAS_ARRAY_ACCESS,
    /* 0x52 dastore        */ TOS_GAS_ARRAY_ACCESS,
    /* 0x53 aastore        */ TOS_GAS_ARRAY_ACCESS,
    /* 0x54 bastore        */ TOS_GAS_ARRAY_ACCESS,
    /* 0x55 castore        */ TOS_GAS_ARRAY_ACCESS,
    /* 0x56 sastore        */ TOS_GAS_ARRAY_ACCESS,
    /* 0x57 pop            */ TOS_GAS_STACK,
    /* 0x58 pop2           */ TOS_GAS_STACK,
    /* 0x59 dup            */ TOS_GAS_STACK,
    /* 0x5a dup_x1         */ TOS_GAS_STACK,
    /* 0x5b dup_x2         */ TOS_GAS_STACK,
    /* 0x5c dup2           */ TOS_GAS_STACK,
    /* 0x5d dup2_x1        */ TOS_GAS_STACK,
    /* 0x5e dup2_x2        */ TOS_GAS_STACK,
    /* 0x5f swap           */ TOS_GAS_STACK,
    /* 0x60 iadd           */ TOS_GAS_INT_ARITH,
    /* 0x61 ladd           */ TOS_GAS_LONG_ARITH,
    /* 0x62 fadd           */ TOS_GAS_FLOAT_ARITH,
    /* 0x63 dadd           */ TOS_GAS_DOUBLE_ARITH,
    /* 0x64 isub           */ TOS_GAS_INT_ARITH,
    /* 0x65 lsub           */ TOS_GAS_LONG_ARITH,
    /* 0x66 fsub           */ TOS_GAS_FLOAT_ARITH,
    /* 0x67 dsub           */ TOS_GAS_DOUBLE_ARITH,
    /* 0x68 imul           */ TOS_GAS_INT_ARITH,
    /* 0x69 lmul           */ TOS_GAS_LONG_ARITH,
    /* 0x6a fmul           */ TOS_GAS_FLOAT_ARITH,
    /* 0x6b dmul           */ TOS_GAS_DOUBLE_ARITH,
    /* 0x6c idiv           */ TOS_GAS_DIV,
    /* 0x6d ldiv           */ TOS_GAS_DIV,
    /* 0x6e fdiv           */ TOS_GAS_FLOAT_ARITH,
    /* 0x6f ddiv           */ TOS_GAS_DOUBLE_ARITH,
    /* 0x70 irem           */ TOS_GAS_DIV,
    /* 0x71 lrem           */ TOS_GAS_DIV,
    /* 0x72 frem           */ TOS_GAS_FLOAT_ARITH,
    /* 0x73 drem           */ TOS_GAS_DOUBLE_ARITH,
    /* 0x74 ineg           */ TOS_GAS_INT_ARITH,
    /* 0x75 lneg           */ TOS_GAS_LONG_ARITH,
    /* 0x76 fneg           */ TOS_GAS_FLOAT_ARITH,
    /* 0x77 dneg           */ TOS_GAS_DOUBLE_ARITH,
    /* 0x78 ishl           */ TOS_GAS_INT_ARITH,
    /* 0x79 lshl           */ TOS_GAS_LONG_ARITH,
    /* 0x7a ishr           */ TOS_GAS_INT_ARITH,
    /* 0x7b lshr           */ TOS_GAS_LONG_ARITH,
    /* 0x7c iushr          */ TOS_GAS_INT_ARITH,
    /* 0x7d lushr          */ TOS_GAS_LONG_ARITH,
    /* 0x7e iand           */ TOS_GAS_INT_ARITH,
    /* 0x7f land           */ TOS_GAS_LONG_ARITH,
    /* 0x80 ior            */ TOS_GAS_INT_ARITH,
    /* 0x81 lor            */ TOS_GAS_LONG_ARITH,
    /* 0x82 ixor           */ TOS_GAS_INT_ARITH,
    /* 0x83 lxor           */ TOS_GAS_LONG_ARITH,
    /* 0x84 iinc           */ TOS_GAS_INT_ARITH,
    /* 0x85 i2l            */ TOS_GAS_CONVERT,
    /* 0x86 i2f            */ TOS_GAS_CONVERT,
    /* 0x87 i2d            */ TOS_GAS_CONVERT,
    /* 0x88 l2i            */ TOS_GAS_CONVERT,
    /* 0x89 l2f            */ TOS_GAS_CONVERT,
    /* 0x8a l2d            */ TOS_GAS_CONVERT,
    /* 0x8b f2i            */ TOS_GAS_CONVERT,
    /* 0x8c f2l            */ TOS_GAS_CONVERT,
    /* 0x8d f2d            */ TOS_GAS_CONVERT,
    /* 0x8e d2i            */ TOS_GAS_CONVERT,
    /* 0x8f d2l            */ TOS_GAS_CONVERT,
    /* 0x90 d2f            */ TOS_GAS_CONVERT,
    /* 0x91 i2b            */ TOS_GAS_CONVERT,
    /* 0x92 i2c            */ TOS_GAS_CONVERT,
    /* 0x93 i2s            */ TOS_GAS_CONVERT,
    /* 0x94 lcmp           */ TOS_GAS_COMPARE,
    /* 0x95 fcmpl          */ TOS_GAS_COMPARE,
    /* 0x96 fcmpg          */ TOS_GAS_COMPARE,
    /* 0x97 dcmpl          */ TOS_GAS_COMPARE,
    /* 0x98 dcmpg          */ TOS_GAS_COMPARE,
    /* 0x99 ifeq           */ TOS_GAS_BRANCH,
    /* 0x9a ifne           */ TOS_GAS_BRANCH,
    /* 0x9b iflt           */ TOS_GAS_BRANCH,
    /* 0x9c ifge           */ TOS_GAS_BRANCH,
    /* 0x9d ifgt           */ TOS_GAS_BRANCH,
    /* 0x9e ifle           */ TOS_GAS_BRANCH,
    /* 0x9f if_icmpeq      */ TOS_GAS_BRANCH,
    /* 0xa0 if_icmpne      */ TOS_GAS_BRANCH,
    /* 0xa1 if_icmplt      */ TOS_GAS_BRANCH,
    /* 0xa2 if_icmpge      */ TOS_GAS_BRANCH,
    /* 0xa3 if_icmpgt      */ TOS_GAS_BRANCH,
    /* 0xa4 if_icmple      */ TOS_GAS_BRANCH,
    /* 0xa5 if_acmpeq      */ TOS_GAS_BRANCH,
    /* 0xa6 if_acmpne      */ TOS_GAS_BRANCH,
    /* 0xa7 goto           */ TOS_GAS_BRANCH,
    /* 0xa8 jsr            */ TOS_GAS_BRANCH,
    /* 0xa9 ret            */ TOS_GAS_BRANCH,
    /* 0xaa tableswitch    */ TOS_GAS_BRANCH,
    /* 0xab lookupswitch   */ TOS_GAS_BRANCH,
    /* 0xac ireturn        */ TOS_GAS_RETURN,
    /* 0xad lreturn        */ TOS_GAS_RETURN,
    /* 0xae freturn        */ TOS_GAS_RETURN,
    /* 0xaf dreturn        */ TOS_GAS_RETURN,
    /* 0xb0 areturn        */ TOS_GAS_RETURN,
    /* 0xb1 return         */ TOS_GAS_RETURN,
    /* 0xb2 getstatic      */ TOS_GAS_FIELD,
    /* 0xb3 putstatic      */ TOS_GAS_FIELD,
    /* 0xb4 getfield       */ TOS_GAS_FIELD,
    /* 0xb5 putfield       */ TOS_GAS_FIELD,
    /* 0xb6 invokevirtual  */ TOS_GAS_INVOKE,
    /* 0xb7 invokespecial  */ TOS_GAS_INVOKE,
    /* 0xb8 invokestatic   */ TOS_GAS_INVOKE,
    /* 0xb9 invokeinterface*/ TOS_GAS_INVOKE,
    /* 0xba invokedynamic  */ TOS_GAS_INVOKE,
    /* 0xbb new            */ TOS_GAS_ALLOC,
    /* 0xbc newarray       */ TOS_GAS_ALLOC,
    /* 0xbd anewarray      */ TOS_GAS_ALLOC,
    /* 0xbe arraylength    */ TOS_GAS_STACK,
    /* 0xbf athrow         */ TOS_GAS_THROW,
    /* 0xc0 checkcast      */ TOS_GAS_TYPECHECK,
    /* 0xc1 instanceof     */ TOS_GAS_TYPECHECK,
    /* 0xc2 monitorenter   */ TOS_GAS_MONITOR,
    /* 0xc3 monitorexit    */ TOS_GAS_MONITOR,
    /* 0xc4 wide           */ TOS_GAS_STACK,
    /* 0xc5 multianewarray */ TOS_GAS_ALLOC,
    /* 0xc6 ifnull         */ TOS_GAS_BRANCH,
    /* 0xc7 ifnonnull      */ TOS_GAS_BRANCH,
    /* 0xc8 goto_w         */ TOS_GAS_BRANCH,
    /* 0xc9 jsr_w          */ TOS_GAS_BRANCH,
    /* 0xca breakpoint     */ TOS_GAS_DEFAULT,
    /* 0xcb              */ TOS_GAS_DEFAULT,
    /* 0xcc              */ TOS_GAS_DEFAULT,
    /* 0xcd              */ TOS_GAS_DEFAULT,
    /* 0xce              */ TOS_GAS_DEFAULT,
    /* 0xcf              */ TOS_GAS_DEFAULT,
    /* 0xd0              */ TOS_GAS_DEFAULT,
    /* 0xd1              */ TOS_GAS_DEFAULT,
    /* 0xd2              */ TOS_GAS_DEFAULT,
    /* 0xd3              */ TOS_GAS_DEFAULT,
    /* 0xd4              */ TOS_GAS_DEFAULT,
    /* 0xd5              */ TOS_GAS_DEFAULT,
    /* 0xd6              */ TOS_GAS_DEFAULT,
    /* 0xd7              */ TOS_GAS_DEFAULT,
    /* 0xd8              */ TOS_GAS_DEFAULT,
    /* 0xd9              */ TOS_GAS_DEFAULT,
    /* 0xda              */ TOS_GAS_DEFAULT,
    /* 0xdb              */ TOS_GAS_DEFAULT,
    /* 0xdc              */ TOS_GAS_DEFAULT,
    /* 0xdd              */ TOS_GAS_DEFAULT,
    /* 0xde              */ TOS_GAS_DEFAULT,
    /* 0xdf              */ TOS_GAS_DEFAULT,
    /* 0xe0              */ TOS_GAS_DEFAULT,
    /* 0xe1              */ TOS_GAS_DEFAULT,
    /* 0xe2              */ TOS_GAS_DEFAULT,
    /* 0xe3              */ TOS_GAS_DEFAULT,
    /* 0xe4              */ TOS_GAS_DEFAULT,
    /* 0xe5              */ TOS_GAS_DEFAULT,
    /* 0xe6              */ TOS_GAS_DEFAULT,
    /* 0xe7              */ TOS_GAS_DEFAULT,
    /* 0xe8              */ TOS_GAS_DEFAULT,
    /* 0xe9              */ TOS_GAS_DEFAULT,
    /* 0xea              */ TOS_GAS_DEFAULT,
    /* 0xeb              */ TOS_GAS_DEFAULT,
    /* 0xec              */ TOS_GAS_DEFAULT,
    /* 0xed              */ TOS_GAS_DEFAULT,
    /* 0xee              */ TOS_GAS_DEFAULT,
    /* 0xef              */ TOS_GAS_DEFAULT,
    /* 0xf0              */ TOS_GAS_DEFAULT,
    /* 0xf1              */ TOS_GAS_DEFAULT,
    /* 0xf2              */ TOS_GAS_DEFAULT,
    /* 0xf3              */ TOS_GAS_DEFAULT,
    /* 0xf4              */ TOS_GAS_DEFAULT,
    /* 0xf5              */ TOS_GAS_DEFAULT,
    /* 0xf6              */ TOS_GAS_DEFAULT,
    /* 0xf7              */ TOS_GAS_DEFAULT,
    /* 0xf8              */ TOS_GAS_DEFAULT,
    /* 0xf9              */ TOS_GAS_DEFAULT,
    /* 0xfa              */ TOS_GAS_DEFAULT,
    /* 0xfb              */ TOS_GAS_DEFAULT,
    /* 0xfc              */ TOS_GAS_DEFAULT,
    /* 0xfd              */ TOS_GAS_DEFAULT,
    /* 0xfe impdep1      */ TOS_GAS_DEFAULT,
    /* 0xff impdep2      */ TOS_GAS_DEFAULT,
};

#endif  /* AVATA_GAS_SCHEDULE_DEFINE_TABLE */

#endif  /* AVATA_GAS_SCHEDULE_H */
