[package]
name = "tos-uno-wallet-prover"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]

[workspace]

[dependencies]
tos-uno-crypto-prototype = { path = "../crypto" }
bulletproofs = { path = "../crypto/vendor/bulletproofs", default-features = false }
curve25519-dalek = { git = "https://github.com/tosnetwork/curve25519-dalek", rev = "10042b03cfc92e505e9d33d2827d5c0f0d36989a", default-features = false, features = ["alloc", "std", "precomputed-tables", "zeroize"] }
rand = { version = "=0.10.1", default-features = false, features = ["std", "std_rng", "sys_rng"] }
chacha20 = { version = "=0.10.2", default-features = false, features = ["rng", "zeroize"] }
zeroize = "=1.9.0"

[dev-dependencies]
sha2 = "=0.10.9"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
