// Generated by tools/validator-auth/generate.py; schema SHA256 40b801c7e79dbd02355ccf8e8b76689338ad396d49e2d2ce7d5241a2e92717b5
#pragma once
#include "codec.h"
namespace tos::auth {
inline constexpr Hash interface_fingerprint{155,17,133,5,171,154,63,104,17,141,197,11,81,242,116,43,61,41,202,129,198,190,33,92,245,75,40,244,222,131,181,104};
struct Suite {
  std::uint16_t suite_{};
  std::uint16_t parameters_{};
  bool operator==(const Suite&) const = default;
};
inline void read(Reader& r, Suite& v) {
  r.integer(v.suite_);
  r.integer(v.parameters_);
}
inline void write(Writer& w, const Suite& v) {
  w.integer(v.suite_);
  w.integer(v.parameters_);
}
struct Keyref {
  std::uint16_t suite_{};
  std::uint16_t parameters_{};
  std::uint64_t epoch_{};
  Hash key_id_{};
  bool operator==(const Keyref&) const = default;
};
inline void read(Reader& r, Keyref& v) {
  r.integer(v.suite_);
  r.integer(v.parameters_);
  r.integer(v.epoch_);
  r.hash(v.key_id_);
}
inline void write(Writer& w, const Keyref& v) {
  w.integer(v.suite_);
  w.integer(v.parameters_);
  w.integer(v.epoch_);
  w.bytes(v.key_id_);
}
struct Component {
  std::uint16_t suite_{};
  std::uint16_t parameters_{};
  std::uint64_t epoch_{};
  Hash key_id_{};
  Bytes signature_{};
  bool operator==(const Component&) const = default;
};
inline void read(Reader& r, Component& v) {
  r.integer(v.suite_);
  r.integer(v.parameters_);
  r.integer(v.epoch_);
  r.hash(v.key_id_);
  r.blob(v.signature_, 65536);
}
inline void write(Writer& w, const Component& v) {
  w.integer(v.suite_);
  w.integer(v.parameters_);
  w.integer(v.epoch_);
  w.bytes(v.key_id_);
  w.blob(v.signature_, 65536);
}
struct Record {
  Hash identity_{};
  std::vector<Component> components_{};
  bool operator==(const Record&) const = default;
};
inline void read(Reader& r, Record& v) {
  r.hash(v.identity_);
  r.list(v.components_, 1, 2, 48);
}
inline void write(Writer& w, const Record& v) {
  w.bytes(v.identity_);
  w.list(v.components_, 1, 2);
}
struct Roleref {
  std::uint8_t role_{};
  Keyref key_{};
  bool operator==(const Roleref&) const = default;
};
inline void read(Reader& r, Roleref& v) {
  r.integer(v.role_);
  read(r, v.key_);
}
inline void write(Writer& w, const Roleref& v) {
  w.integer(v.role_);
  write(w, v.key_);
}
struct Key {
  Hash identity_{};
  std::uint8_t role_{};
  std::uint16_t suite_{};
  std::uint16_t parameters_{};
  std::uint64_t epoch_{};
  std::uint32_t valid_from_{};
  std::uint32_t valid_until_{};
  Bytes public_key_{};
  Hash capacity_domain_{};
  std::uint64_t capacity_limit_{};
  bool operator==(const Key&) const = default;
};
inline void read(Reader& r, Key& v) {
  r.header("VAK1");
  r.hash(v.identity_);
  r.integer(v.role_);
  r.integer(v.suite_);
  r.integer(v.parameters_);
  r.integer(v.epoch_);
  r.integer(v.valid_from_);
  r.integer(v.valid_until_);
  r.blob(v.public_key_, 16384);
  r.hash(v.capacity_domain_);
  r.integer(v.capacity_limit_);
}
inline void write(Writer& w, const Key& v) {
  w.header("VAK1");
  w.bytes(v.identity_);
  w.integer(v.role_);
  w.integer(v.suite_);
  w.integer(v.parameters_);
  w.integer(v.epoch_);
  w.integer(v.valid_from_);
  w.integer(v.valid_until_);
  w.blob(v.public_key_, 16384);
  w.bytes(v.capacity_domain_);
  w.integer(v.capacity_limit_);
}
struct Policy {
  std::uint64_t revision_{};
  Hash previous_{};
  Hash interface_digest_{};
  std::uint32_t effective_from_{};
  std::uint8_t phase_{};
  std::vector<Suite> suites_{};
  std::uint32_t max_envelope_{};
  std::uint32_t max_certificate_{};
  bool operator==(const Policy&) const = default;
};
inline void read(Reader& r, Policy& v) {
  r.header("VAP1");
  r.integer(v.revision_);
  r.hash(v.previous_);
  r.hash(v.interface_digest_);
  r.integer(v.effective_from_);
  r.integer(v.phase_);
  r.list(v.suites_, 1, 2, 4);
  r.integer(v.max_envelope_);
  r.integer(v.max_certificate_);
}
inline void write(Writer& w, const Policy& v) {
  w.header("VAP1");
  w.integer(v.revision_);
  w.bytes(v.previous_);
  w.bytes(v.interface_digest_);
  w.integer(v.effective_from_);
  w.integer(v.phase_);
  w.list(v.suites_, 1, 2);
  w.integer(v.max_envelope_);
  w.integer(v.max_certificate_);
}
struct Member {
  Hash identity_{};
  Hash stake_id_{};
  std::uint64_t weight_{};
  Hash adnl_id_{};
  std::vector<Key> keys_{};
  bool operator==(const Member&) const = default;
};
inline void read(Reader& r, Member& v) {
  r.hash(v.identity_);
  r.hash(v.stake_id_);
  r.integer(v.weight_);
  r.hash(v.adnl_id_);
  r.list(v.keys_, 1, 10, 105);
}
inline void write(Writer& w, const Member& v) {
  w.bytes(v.identity_);
  w.bytes(v.stake_id_);
  w.integer(v.weight_);
  w.bytes(v.adnl_id_);
  w.list(v.keys_, 1, 10);
}
struct Committee {
  Hash policy_{};
  Hash election_{};
  std::int32_t workchain_{};
  std::uint64_t shard_{};
  std::uint32_t catchain_{};
  std::uint32_t anchor_mc_{};
  std::vector<Member> members_{};
  bool operator==(const Committee&) const = default;
};
inline void read(Reader& r, Committee& v) {
  r.header("VAM1");
  r.hash(v.policy_);
  r.hash(v.election_);
  r.integer(v.workchain_);
  r.integer(v.shard_);
  r.integer(v.catchain_);
  r.integer(v.anchor_mc_);
  r.list(v.members_, 2, 400, 105);
}
inline void write(Writer& w, const Committee& v) {
  w.header("VAM1");
  w.bytes(v.policy_);
  w.bytes(v.election_);
  w.integer(v.workchain_);
  w.integer(v.shard_);
  w.integer(v.catchain_);
  w.integer(v.anchor_mc_);
  w.list(v.members_, 2, 400);
}
struct Duty {
  std::int32_t network_{};
  Hash genesis_root_{};
  Hash genesis_file_{};
  Hash policy_{};
  Hash committee_{};
  Hash session_{};
  std::int32_t workchain_{};
  std::uint64_t shard_{};
  std::uint32_t anchor_mc_{};
  std::uint32_t catchain_{};
  std::uint64_t position_{};
  std::uint8_t role_{};
  Hash payload_hash_{};
  bool operator==(const Duty&) const = default;
};
inline void read(Reader& r, Duty& v) {
  r.header("VAD1");
  r.integer(v.network_);
  r.hash(v.genesis_root_);
  r.hash(v.genesis_file_);
  r.hash(v.policy_);
  r.hash(v.committee_);
  r.hash(v.session_);
  r.integer(v.workchain_);
  r.integer(v.shard_);
  r.integer(v.anchor_mc_);
  r.integer(v.catchain_);
  r.integer(v.position_);
  r.integer(v.role_);
  r.hash(v.payload_hash_);
}
inline void write(Writer& w, const Duty& v) {
  w.header("VAD1");
  w.integer(v.network_);
  w.bytes(v.genesis_root_);
  w.bytes(v.genesis_file_);
  w.bytes(v.policy_);
  w.bytes(v.committee_);
  w.bytes(v.session_);
  w.integer(v.workchain_);
  w.integer(v.shard_);
  w.integer(v.anchor_mc_);
  w.integer(v.catchain_);
  w.integer(v.position_);
  w.integer(v.role_);
  w.bytes(v.payload_hash_);
}
struct Statement {
  Duty duty_{};
  Hash identity_{};
  std::vector<Keyref> keys_{};
  bool operator==(const Statement&) const = default;
};
inline void read(Reader& r, Statement& v) {
  r.header("VAS1");
  read(r, v.duty_);
  r.hash(v.identity_);
  r.list(v.keys_, 1, 2, 44);
}
inline void write(Writer& w, const Statement& v) {
  w.header("VAS1");
  write(w, v.duty_);
  w.bytes(v.identity_);
  w.list(v.keys_, 1, 2);
}
struct Envelope {
  Duty duty_{};
  Bytes payload_{};
  Record record_{};
  bool operator==(const Envelope&) const = default;
};
inline void read(Reader& r, Envelope& v) {
  r.header("VAE1");
  read(r, v.duty_);
  r.blob(v.payload_, 4096);
  read(r, v.record_);
}
inline void write(Writer& w, const Envelope& v) {
  w.header("VAE1");
  write(w, v.duty_);
  w.blob(v.payload_, 4096);
  write(w, v.record_);
}
struct Certificate {
  Duty duty_{};
  Bytes payload_{};
  std::vector<Record> records_{};
  bool operator==(const Certificate&) const = default;
};
inline void read(Reader& r, Certificate& v) {
  r.header("VAC1");
  read(r, v.duty_);
  r.blob(v.payload_, 4096);
  r.list(v.records_, 2, 400, 33);
}
inline void write(Writer& w, const Certificate& v) {
  w.header("VAC1");
  write(w, v.duty_);
  w.blob(v.payload_, 4096);
  w.list(v.records_, 2, 400);
}
struct Update {
  std::uint8_t operation_{};
  Hash identity_{};
  std::uint64_t nonce_{};
  Hash previous_{};
  std::uint32_t effective_from_{};
  Hash old_key_{};
  Bytes new_key_{};
  Bytes new_policy_{};
  Bytes operation_data_{};
  bool operator==(const Update&) const = default;
};
inline void read(Reader& r, Update& v) {
  r.header("VAU1");
  r.integer(v.operation_);
  r.hash(v.identity_);
  r.integer(v.nonce_);
  r.hash(v.previous_);
  r.integer(v.effective_from_);
  r.hash(v.old_key_);
  r.blob(v.new_key_, 32768);
  r.blob(v.new_policy_, 4096);
  r.blob(v.operation_data_, 4096);
}
inline void write(Writer& w, const Update& v) {
  w.header("VAU1");
  w.integer(v.operation_);
  w.bytes(v.identity_);
  w.integer(v.nonce_);
  w.bytes(v.previous_);
  w.integer(v.effective_from_);
  w.bytes(v.old_key_);
  w.blob(v.new_key_, 32768);
  w.blob(v.new_policy_, 4096);
  w.blob(v.operation_data_, 4096);
}
struct Transition {
  std::uint8_t operation_{};
  std::uint8_t role_{};
  std::uint16_t suite_{};
  std::uint16_t parameters_{};
  Hash old_key_{};
  Hash new_key_{};
  std::uint32_t effective_from_{};
  std::uint32_t accepted_at_{};
  std::uint64_t nonce_{};
  Hash predecessor_{};
  Hash update_id_{};
  Hash authorization_id_{};
  bool operator==(const Transition&) const = default;
};
inline void read(Reader& r, Transition& v) {
  r.header("VATr");
  r.integer(v.operation_);
  r.integer(v.role_);
  r.integer(v.suite_);
  r.integer(v.parameters_);
  r.hash(v.old_key_);
  r.hash(v.new_key_);
  r.integer(v.effective_from_);
  r.integer(v.accepted_at_);
  r.integer(v.nonce_);
  r.hash(v.predecessor_);
  r.hash(v.update_id_);
  r.hash(v.authorization_id_);
}
inline void write(Writer& w, const Transition& v) {
  w.header("VATr");
  w.integer(v.operation_);
  w.integer(v.role_);
  w.integer(v.suite_);
  w.integer(v.parameters_);
  w.bytes(v.old_key_);
  w.bytes(v.new_key_);
  w.integer(v.effective_from_);
  w.integer(v.accepted_at_);
  w.integer(v.nonce_);
  w.bytes(v.predecessor_);
  w.bytes(v.update_id_);
  w.bytes(v.authorization_id_);
}
struct Identity {
  Hash identity_{};
  Hash stake_id_{};
  std::int32_t owner_workchain_{};
  Hash owner_address_{};
  std::uint64_t next_nonce_{};
  Hash previous_{};
  std::vector<Roleref> active_{};
  std::vector<Transition> pending_{};
  bool operator==(const Identity&) const = default;
};
inline void read(Reader& r, Identity& v) {
  r.header("VAI1");
  r.hash(v.identity_);
  r.hash(v.stake_id_);
  r.integer(v.owner_workchain_);
  r.hash(v.owner_address_);
  r.integer(v.next_nonce_);
  r.hash(v.previous_);
  r.list(v.active_, 1, 10, 45);
  r.list(v.pending_, 1, 10, 190);
}
inline void write(Writer& w, const Identity& v) {
  w.header("VAI1");
  w.bytes(v.identity_);
  w.bytes(v.stake_id_);
  w.integer(v.owner_workchain_);
  w.bytes(v.owner_address_);
  w.integer(v.next_nonce_);
  w.bytes(v.previous_);
  w.list(v.active_, 1, 10);
  w.list(v.pending_, 1, 10);
}
struct Activation {
  std::uint64_t revision_{};
  Hash previous_{};
  Hash next_policy_{};
  std::uint32_t effective_from_{};
  std::uint32_t checkpoint_seqno_{};
  Hash checkpoint_root_{};
  Hash checkpoint_file_{};
  Hash checkpoint_state_{};
  bool operator==(const Activation&) const = default;
};
inline void read(Reader& r, Activation& v) {
  r.header("VAT1");
  r.integer(v.revision_);
  r.hash(v.previous_);
  r.hash(v.next_policy_);
  r.integer(v.effective_from_);
  r.integer(v.checkpoint_seqno_);
  r.hash(v.checkpoint_root_);
  r.hash(v.checkpoint_file_);
  r.hash(v.checkpoint_state_);
}
inline void write(Writer& w, const Activation& v) {
  w.header("VAT1");
  w.integer(v.revision_);
  w.bytes(v.previous_);
  w.bytes(v.next_policy_);
  w.integer(v.effective_from_);
  w.integer(v.checkpoint_seqno_);
  w.bytes(v.checkpoint_root_);
  w.bytes(v.checkpoint_file_);
  w.bytes(v.checkpoint_state_);
}
struct Observation {
  std::uint16_t suite_{};
  std::uint16_t parameters_{};
  Hash registry_root_{};
  std::uint32_t valid_from_{};
  std::uint32_t valid_until_{};
  std::uint8_t enabled_{};
  bool operator==(const Observation&) const = default;
};
inline void read(Reader& r, Observation& v) {
  r.header("VAO1");
  r.integer(v.suite_);
  r.integer(v.parameters_);
  r.hash(v.registry_root_);
  r.integer(v.valid_from_);
  r.integer(v.valid_until_);
  r.integer(v.enabled_);
}
inline void write(Writer& w, const Observation& v) {
  w.header("VAO1");
  w.integer(v.suite_);
  w.integer(v.parameters_);
  w.bytes(v.registry_root_);
  w.integer(v.valid_from_);
  w.integer(v.valid_until_);
  w.integer(v.enabled_);
}
struct Anchor {
  std::uint32_t seqno_{};
  Hash root_{};
  Hash file_{};
  Hash state_{};
  bool operator==(const Anchor&) const = default;
};
inline void read(Reader& r, Anchor& v) {
  r.header("VAB1");
  r.integer(v.seqno_);
  r.hash(v.root_);
  r.hash(v.file_);
  r.hash(v.state_);
}
inline void write(Writer& w, const Anchor& v) {
  w.header("VAB1");
  w.integer(v.seqno_);
  w.bytes(v.root_);
  w.bytes(v.file_);
  w.bytes(v.state_);
}
struct ObjectRef {
  std::uint8_t kind_{};
  std::uint32_t byte_length_{};
  Hash object_id_{};
  std::vector<Hash> chunk_hashes_{};
  bool operator==(const ObjectRef&) const = default;
};
inline void read(Reader& r, ObjectRef& v) {
  r.header("VAOr");
  r.integer(v.kind_);
  r.integer(v.byte_length_);
  r.hash(v.object_id_);
  r.list(v.chunk_hashes_, 1, 64, 32);
}
inline void write(Writer& w, const ObjectRef& v) {
  w.header("VAOr");
  w.integer(v.kind_);
  w.integer(v.byte_length_);
  w.bytes(v.object_id_);
  w.list(v.chunk_hashes_, 1, 64);
}
struct ObjectValue {
  std::uint8_t kind_{};
  Bytes inline_{};
  std::vector<ObjectRef> reference_{};
  bool operator==(const ObjectValue&) const = default;
};
inline void read(Reader& r, ObjectValue& v) {
  r.header("VAOv");
  r.integer(v.kind_);
  r.blob(v.inline_, 65536);
  r.list(v.reference_, 1, 1, 46);
}
inline void write(Writer& w, const ObjectValue& v) {
  w.header("VAOv");
  w.integer(v.kind_);
  w.blob(v.inline_, 65536);
  w.list(v.reference_, 1, 1);
}
struct Proofref {
  Anchor anchor_{};
  std::uint8_t kind_{};
  Hash object_id_{};
  Hash proof_hash_{};
  ObjectValue proof_{};
  bool operator==(const Proofref&) const = default;
};
inline void read(Reader& r, Proofref& v) {
  r.header("VAF1");
  read(r, v.anchor_);
  r.integer(v.kind_);
  r.hash(v.object_id_);
  r.hash(v.proof_hash_);
  read(r, v.proof_);
}
inline void write(Writer& w, const Proofref& v) {
  w.header("VAF1");
  write(w, v.anchor_);
  w.integer(v.kind_);
  w.bytes(v.object_id_);
  w.bytes(v.proof_hash_);
  write(w, v.proof_);
}
struct OwnerAuth {
  Hash update_id_{};
  Hash stake_id_{};
  std::int32_t owner_workchain_{};
  Hash owner_address_{};
  Proofref proof_{};
  bool operator==(const OwnerAuth&) const = default;
};
inline void read(Reader& r, OwnerAuth& v) {
  r.header("VAOw");
  r.hash(v.update_id_);
  r.hash(v.stake_id_);
  r.integer(v.owner_workchain_);
  r.hash(v.owner_address_);
  read(r, v.proof_);
}
inline void write(Writer& w, const OwnerAuth& v) {
  w.header("VAOw");
  w.bytes(v.update_id_);
  w.bytes(v.stake_id_);
  w.integer(v.owner_workchain_);
  w.bytes(v.owner_address_);
  write(w, v.proof_);
}
struct PossessionAuth {
  Hash update_id_{};
  Keyref key_{};
  Bytes signature_{};
  bool operator==(const PossessionAuth&) const = default;
};
inline void read(Reader& r, PossessionAuth& v) {
  r.header("VAPo");
  r.hash(v.update_id_);
  read(r, v.key_);
  r.blob(v.signature_, 65536);
}
inline void write(Writer& w, const PossessionAuth& v) {
  w.header("VAPo");
  w.bytes(v.update_id_);
  write(w, v.key_);
  w.blob(v.signature_, 65536);
}
struct IdentityAuth {
  Hash update_id_{};
  Hash identity_{};
  ObjectValue certificate_{};
  bool operator==(const IdentityAuth&) const = default;
};
inline void read(Reader& r, IdentityAuth& v) {
  r.header("VAAd");
  r.hash(v.update_id_);
  r.hash(v.identity_);
  read(r, v.certificate_);
}
inline void write(Writer& w, const IdentityAuth& v) {
  w.header("VAAd");
  w.bytes(v.update_id_);
  w.bytes(v.identity_);
  write(w, v.certificate_);
}
struct GovernanceAuth {
  Hash update_id_{};
  Hash committee_{};
  ObjectValue certificate_{};
  bool operator==(const GovernanceAuth&) const = default;
};
inline void read(Reader& r, GovernanceAuth& v) {
  r.header("VAGo");
  r.hash(v.update_id_);
  r.hash(v.committee_);
  read(r, v.certificate_);
}
inline void write(Writer& w, const GovernanceAuth& v) {
  w.header("VAGo");
  w.bytes(v.update_id_);
  w.bytes(v.committee_);
  write(w, v.certificate_);
}
struct Authorizations {
  std::vector<OwnerAuth> owner_{};
  std::vector<PossessionAuth> possession_{};
  std::vector<IdentityAuth> administration_{};
  std::vector<GovernanceAuth> governance_{};
  bool operator==(const Authorizations&) const = default;
};
inline void read(Reader& r, Authorizations& v) {
  r.header("VAA1");
  r.list(v.owner_, 1, 1, 303);
  r.list(v.possession_, 1, 1, 88);
  r.list(v.administration_, 1, 1, 86);
  r.list(v.governance_, 1, 1, 86);
}
inline void write(Writer& w, const Authorizations& v) {
  w.header("VAA1");
  w.list(v.owner_, 1, 1);
  w.list(v.possession_, 1, 1);
  w.list(v.administration_, 1, 1);
  w.list(v.governance_, 1, 1);
}
struct PermitBody {
  Hash issuer_{};
  Hash service_policy_{};
  Hash audience_{};
  std::int32_t network_{};
  Hash genesis_root_{};
  Hash genesis_file_{};
  Anchor anchor_{};
  Hash registry_root_{};
  Hash policy_{};
  Hash committee_{};
  Hash session_{};
  Hash identity_{};
  std::uint8_t method_{};
  Hash subject_{};
  std::uint32_t expires_mc_{};
  std::uint64_t fence_{};
  bool operator==(const PermitBody&) const = default;
};
inline void read(Reader& r, PermitBody& v) {
  r.header("VAPb");
  r.hash(v.issuer_);
  r.hash(v.service_policy_);
  r.hash(v.audience_);
  r.integer(v.network_);
  r.hash(v.genesis_root_);
  r.hash(v.genesis_file_);
  read(r, v.anchor_);
  r.hash(v.registry_root_);
  r.hash(v.policy_);
  r.hash(v.committee_);
  r.hash(v.session_);
  r.hash(v.identity_);
  r.integer(v.method_);
  r.hash(v.subject_);
  r.integer(v.expires_mc_);
  r.integer(v.fence_);
}
inline void write(Writer& w, const PermitBody& v) {
  w.header("VAPb");
  w.bytes(v.issuer_);
  w.bytes(v.service_policy_);
  w.bytes(v.audience_);
  w.integer(v.network_);
  w.bytes(v.genesis_root_);
  w.bytes(v.genesis_file_);
  write(w, v.anchor_);
  w.bytes(v.registry_root_);
  w.bytes(v.policy_);
  w.bytes(v.committee_);
  w.bytes(v.session_);
  w.bytes(v.identity_);
  w.integer(v.method_);
  w.bytes(v.subject_);
  w.integer(v.expires_mc_);
  w.integer(v.fence_);
}
struct ServiceComponent {
  std::uint16_t suite_{};
  std::uint16_t parameters_{};
  Hash key_id_{};
  Bytes signature_{};
  bool operator==(const ServiceComponent&) const = default;
};
inline void read(Reader& r, ServiceComponent& v) {
  r.integer(v.suite_);
  r.integer(v.parameters_);
  r.hash(v.key_id_);
  r.blob(v.signature_, 65536);
}
inline void write(Writer& w, const ServiceComponent& v) {
  w.integer(v.suite_);
  w.integer(v.parameters_);
  w.bytes(v.key_id_);
  w.blob(v.signature_, 65536);
}
struct Permit {
  PermitBody body_{};
  std::vector<ServiceComponent> components_{};
  bool operator==(const Permit&) const = default;
};
inline void read(Reader& r, Permit& v) {
  r.header("VAPt");
  read(r, v.body_);
  r.list(v.components_, 1, 2, 40);
}
inline void write(Writer& w, const Permit& v) {
  w.header("VAPt");
  write(w, v.body_);
  w.list(v.components_, 1, 2);
}
struct ReceiptBody {
  Hash issuer_{};
  Hash service_policy_{};
  Hash audience_{};
  Hash request_id_{};
  std::uint8_t method_{};
  Hash subject_{};
  Hash result_hash_{};
  std::uint64_t journal_sequence_{};
  std::uint64_t fence_{};
  std::uint8_t state_{};
  Hash context_id_{};
  bool operator==(const ReceiptBody&) const = default;
};
inline void read(Reader& r, ReceiptBody& v) {
  r.header("VARb");
  r.hash(v.issuer_);
  r.hash(v.service_policy_);
  r.hash(v.audience_);
  r.hash(v.request_id_);
  r.integer(v.method_);
  r.hash(v.subject_);
  r.hash(v.result_hash_);
  r.integer(v.journal_sequence_);
  r.integer(v.fence_);
  r.integer(v.state_);
  r.hash(v.context_id_);
}
inline void write(Writer& w, const ReceiptBody& v) {
  w.header("VARb");
  w.bytes(v.issuer_);
  w.bytes(v.service_policy_);
  w.bytes(v.audience_);
  w.bytes(v.request_id_);
  w.integer(v.method_);
  w.bytes(v.subject_);
  w.bytes(v.result_hash_);
  w.integer(v.journal_sequence_);
  w.integer(v.fence_);
  w.integer(v.state_);
  w.bytes(v.context_id_);
}
struct Receipt {
  ReceiptBody body_{};
  std::vector<ServiceComponent> components_{};
  bool operator==(const Receipt&) const = default;
};
inline void read(Reader& r, Receipt& v) {
  r.header("VARt");
  read(r, v.body_);
  r.list(v.components_, 1, 2, 40);
}
inline void write(Writer& w, const Receipt& v) {
  w.header("VARt");
  write(w, v.body_);
  w.list(v.components_, 1, 2);
}
struct Capabilities {
  Hash interface_digest_{};
  std::vector<Suite> installed_{};
  std::vector<Suite> admitted_{};
  std::uint32_t max_request_{};
  std::uint32_t max_result_{};
  std::uint8_t persistent_journal_{};
  std::uint8_t fencing_{};
  std::uint8_t stateful_{};
  bool operator==(const Capabilities&) const = default;
};
inline void read(Reader& r, Capabilities& v) {
  r.header("VAc1");
  r.hash(v.interface_digest_);
  r.list(v.installed_, 1, 2, 4);
  r.list(v.admitted_, 1, 2, 4);
  r.integer(v.max_request_);
  r.integer(v.max_result_);
  r.integer(v.persistent_journal_);
  r.integer(v.fencing_);
  r.integer(v.stateful_);
}
inline void write(Writer& w, const Capabilities& v) {
  w.header("VAc1");
  w.bytes(v.interface_digest_);
  w.list(v.installed_, 1, 2);
  w.list(v.admitted_, 1, 2);
  w.integer(v.max_request_);
  w.integer(v.max_result_);
  w.integer(v.persistent_journal_);
  w.integer(v.fencing_);
  w.integer(v.stateful_);
}
struct ApiError {
  Hash request_id_{};
  std::uint8_t method_{};
  std::uint16_t code_{};
  std::uint8_t retryable_{};
  std::uint8_t request_state_{};
  Bytes message_{};
  bool operator==(const ApiError&) const = default;
};
inline void read(Reader& r, ApiError& v) {
  r.header("VAEr");
  r.hash(v.request_id_);
  r.integer(v.method_);
  r.integer(v.code_);
  r.integer(v.retryable_);
  r.integer(v.request_state_);
  r.blob(v.message_, 256);
}
inline void write(Writer& w, const ApiError& v) {
  w.header("VAEr");
  w.bytes(v.request_id_);
  w.integer(v.method_);
  w.integer(v.code_);
  w.integer(v.retryable_);
  w.integer(v.request_state_);
  w.blob(v.message_, 256);
}
struct Cursor {
  Anchor anchor_{};
  Hash query_id_{};
  Hash last_identity_{};
  bool operator==(const Cursor&) const = default;
};
inline void read(Reader& r, Cursor& v) {
  r.header("VACu");
  read(r, v.anchor_);
  r.hash(v.query_id_);
  r.hash(v.last_identity_);
}
inline void write(Writer& w, const Cursor& v) {
  w.header("VACu");
  write(w, v.anchor_);
  w.bytes(v.query_id_);
  w.bytes(v.last_identity_);
}
struct KeyHandle {
  Key key_{};
  Hash handle_{};
  bool operator==(const KeyHandle&) const = default;
};
inline void read(Reader& r, KeyHandle& v) {
  r.header("VAKh");
  read(r, v.key_);
  r.hash(v.handle_);
}
inline void write(Writer& w, const KeyHandle& v) {
  w.header("VAKh");
  write(w, v.key_);
  w.bytes(v.handle_);
}
struct SignResult {
  Hash request_id_{};
  Hash statement_id_{};
  Record record_{};
  std::uint64_t fence_{};
  Receipt receipt_{};
  bool operator==(const SignResult&) const = default;
};
inline void read(Reader& r, SignResult& v) {
  r.header("VASr");
  r.hash(v.request_id_);
  r.hash(v.statement_id_);
  read(r, v.record_);
  r.integer(v.fence_);
  read(r, v.receipt_);
}
inline void write(Writer& w, const SignResult& v) {
  w.header("VASr");
  w.bytes(v.request_id_);
  w.bytes(v.statement_id_);
  write(w, v.record_);
  w.integer(v.fence_);
  write(w, v.receipt_);
}
struct RequestState {
  Hash request_id_{};
  std::uint8_t state_{};
  Hash statement_id_{};
  std::uint64_t fence_{};
  std::vector<SignResult> result_{};
  std::vector<Receipt> receipt_{};
  bool operator==(const RequestState&) const = default;
};
inline void read(Reader& r, RequestState& v) {
  r.header("VAQs");
  r.hash(v.request_id_);
  r.integer(v.state_);
  r.hash(v.statement_id_);
  r.integer(v.fence_);
  r.list(v.result_, 1, 1, 372);
  r.list(v.receipt_, 1, 1, 259);
}
inline void write(Writer& w, const RequestState& v) {
  w.header("VAQs");
  w.bytes(v.request_id_);
  w.integer(v.state_);
  w.bytes(v.statement_id_);
  w.integer(v.fence_);
  w.list(v.result_, 1, 1);
  w.list(v.receipt_, 1, 1);
}
struct ProfileResult {
  Anchor anchor_{};
  Hash interface_digest_{};
  Hash policy_{};
  std::vector<Suite> installed_{};
  std::vector<Suite> active_{};
  std::uint8_t can_parse_{};
  std::uint8_t can_verify_{};
  Proofref proof_{};
  bool operator==(const ProfileResult&) const = default;
};
inline void read(Reader& r, ProfileResult& v) {
  r.header("VAPr");
  read(r, v.anchor_);
  r.hash(v.interface_digest_);
  r.hash(v.policy_);
  r.list(v.installed_, 1, 2, 4);
  r.list(v.active_, 1, 2, 4);
  r.integer(v.can_parse_);
  r.integer(v.can_verify_);
  read(r, v.proof_);
}
inline void write(Writer& w, const ProfileResult& v) {
  w.header("VAPr");
  write(w, v.anchor_);
  w.bytes(v.interface_digest_);
  w.bytes(v.policy_);
  w.list(v.installed_, 1, 2);
  w.list(v.active_, 1, 2);
  w.integer(v.can_parse_);
  w.integer(v.can_verify_);
  write(w, v.proof_);
}
struct PolicyResult {
  Anchor anchor_{};
  Policy policy_{};
  Proofref proof_{};
  bool operator==(const PolicyResult&) const = default;
};
inline void read(Reader& r, PolicyResult& v) {
  r.header("VAPl");
  read(r, v.anchor_);
  read(r, v.policy_);
  read(r, v.proof_);
}
inline void write(Writer& w, const PolicyResult& v) {
  w.header("VAPl");
  write(w, v.anchor_);
  write(w, v.policy_);
  write(w, v.proof_);
}
struct RegistryResult {
  Anchor anchor_{};
  Hash query_id_{};
  std::vector<Identity> identities_{};
  std::vector<Cursor> cursor_{};
  Proofref proof_{};
  bool operator==(const RegistryResult&) const = default;
};
inline void read(Reader& r, RegistryResult& v) {
  r.header("VARg");
  read(r, v.anchor_);
  r.hash(v.query_id_);
  r.list(v.identities_, 1, 128, 150);
  r.list(v.cursor_, 1, 1, 180);
  read(r, v.proof_);
}
inline void write(Writer& w, const RegistryResult& v) {
  w.header("VARg");
  write(w, v.anchor_);
  w.bytes(v.query_id_);
  w.list(v.identities_, 1, 128);
  w.list(v.cursor_, 1, 1);
  write(w, v.proof_);
}
struct KeyResult {
  Anchor anchor_{};
  Key key_{};
  Proofref proof_{};
  bool operator==(const KeyResult&) const = default;
};
inline void read(Reader& r, KeyResult& v) {
  r.header("VAKr");
  read(r, v.anchor_);
  read(r, v.key_);
  read(r, v.proof_);
}
inline void write(Writer& w, const KeyResult& v) {
  w.header("VAKr");
  write(w, v.anchor_);
  write(w, v.key_);
  write(w, v.proof_);
}
struct CertificateResult {
  Anchor anchor_{};
  std::uint8_t era_{};
  Hash interface_digest_{};
  ObjectValue certificate_{};
  Proofref committee_{};
  Proofref policy_{};
  bool operator==(const CertificateResult&) const = default;
};
inline void read(Reader& r, CertificateResult& v) {
  r.header("VACr");
  read(r, v.anchor_);
  r.integer(v.era_);
  r.hash(v.interface_digest_);
  read(r, v.certificate_);
  read(r, v.committee_);
  read(r, v.policy_);
}
inline void write(Writer& w, const CertificateResult& v) {
  w.header("VACr");
  write(w, v.anchor_);
  w.integer(v.era_);
  w.bytes(v.interface_digest_);
  write(w, v.certificate_);
  write(w, v.committee_);
  write(w, v.policy_);
}
struct VerifyResult {
  Anchor anchor_{};
  Hash certificate_id_{};
  Hash policy_{};
  Hash committee_{};
  Hash duty_{};
  std::vector<Hash> signers_{};
  std::uint64_t weight_{};
  bool operator==(const VerifyResult&) const = default;
};
inline void read(Reader& r, VerifyResult& v) {
  r.header("VAVr");
  read(r, v.anchor_);
  r.hash(v.certificate_id_);
  r.hash(v.policy_);
  r.hash(v.committee_);
  r.hash(v.duty_);
  r.list(v.signers_, 2, 400, 32);
  r.integer(v.weight_);
}
inline void write(Writer& w, const VerifyResult& v) {
  w.header("VAVr");
  write(w, v.anchor_);
  w.bytes(v.certificate_id_);
  w.bytes(v.policy_);
  w.bytes(v.committee_);
  w.bytes(v.duty_);
  w.list(v.signers_, 2, 400);
  w.integer(v.weight_);
}
struct CapabilitiesRequest {
  bool operator==(const CapabilitiesRequest&) const = default;
};
inline void read(Reader& r, CapabilitiesRequest& v) {
  r.header("VAq1");
}
inline void write(Writer& w, const CapabilitiesRequest& v) {
  w.header("VAq1");
}
struct PublicRequest {
  Hash key_id_{};
  bool operator==(const PublicRequest&) const = default;
};
inline void read(Reader& r, PublicRequest& v) {
  r.header("VAq2");
  r.hash(v.key_id_);
}
inline void write(Writer& w, const PublicRequest& v) {
  w.header("VAq2");
  w.bytes(v.key_id_);
}
struct PrepareRequest {
  Hash preparation_id_{};
  Hash identity_{};
  std::uint8_t role_{};
  std::uint16_t suite_{};
  std::uint16_t parameters_{};
  std::uint64_t epoch_{};
  std::uint32_t valid_from_{};
  std::uint32_t valid_until_{};
  std::uint8_t mode_{};
  Hash provider_handle_{};
  std::uint64_t fence_{};
  bool operator==(const PrepareRequest&) const = default;
};
inline void read(Reader& r, PrepareRequest& v) {
  r.header("VAq3");
  r.hash(v.preparation_id_);
  r.hash(v.identity_);
  r.integer(v.role_);
  r.integer(v.suite_);
  r.integer(v.parameters_);
  r.integer(v.epoch_);
  r.integer(v.valid_from_);
  r.integer(v.valid_until_);
  r.integer(v.mode_);
  r.hash(v.provider_handle_);
  r.integer(v.fence_);
}
inline void write(Writer& w, const PrepareRequest& v) {
  w.header("VAq3");
  w.bytes(v.preparation_id_);
  w.bytes(v.identity_);
  w.integer(v.role_);
  w.integer(v.suite_);
  w.integer(v.parameters_);
  w.integer(v.epoch_);
  w.integer(v.valid_from_);
  w.integer(v.valid_until_);
  w.integer(v.mode_);
  w.bytes(v.provider_handle_);
  w.integer(v.fence_);
}
struct StageRequest {
  Key key_{};
  Hash handle_{};
  Update update_{};
  Authorizations authorizations_{};
  Permit permit_{};
  std::uint64_t fence_{};
  bool operator==(const StageRequest&) const = default;
};
inline void read(Reader& r, StageRequest& v) {
  r.header("VAq4");
  read(r, v.key_);
  r.hash(v.handle_);
  read(r, v.update_);
  read(r, v.authorizations_);
  read(r, v.permit_);
  r.integer(v.fence_);
}
inline void write(Writer& w, const StageRequest& v) {
  w.header("VAq4");
  write(w, v.key_);
  w.bytes(v.handle_);
  write(w, v.update_);
  write(w, v.authorizations_);
  write(w, v.permit_);
  w.integer(v.fence_);
}
struct SignRequest {
  Hash request_id_{};
  std::vector<Hash> key_handles_{};
  Bytes envelope_template_{};
  Permit permit_{};
  std::uint64_t fence_{};
  bool operator==(const SignRequest&) const = default;
};
inline void read(Reader& r, SignRequest& v) {
  r.header("VAq5");
  r.hash(v.request_id_);
  r.list(v.key_handles_, 1, 2, 32);
  r.blob(v.envelope_template_, 262144);
  read(r, v.permit_);
  r.integer(v.fence_);
}
inline void write(Writer& w, const SignRequest& v) {
  w.header("VAq5");
  w.bytes(v.request_id_);
  w.list(v.key_handles_, 1, 2);
  w.blob(v.envelope_template_, 262144);
  write(w, v.permit_);
  w.integer(v.fence_);
}
struct ResultRequest {
  Hash request_id_{};
  bool operator==(const ResultRequest&) const = default;
};
inline void read(Reader& r, ResultRequest& v) {
  r.header("VAq6");
  r.hash(v.request_id_);
}
inline void write(Writer& w, const ResultRequest& v) {
  w.header("VAq6");
  w.bytes(v.request_id_);
}
struct RetireRequest {
  Hash key_id_{};
  Update update_{};
  Authorizations authorizations_{};
  Permit permit_{};
  std::uint64_t fence_{};
  bool operator==(const RetireRequest&) const = default;
};
inline void read(Reader& r, RetireRequest& v) {
  r.header("VAq7");
  r.hash(v.key_id_);
  read(r, v.update_);
  read(r, v.authorizations_);
  read(r, v.permit_);
  r.integer(v.fence_);
}
inline void write(Writer& w, const RetireRequest& v) {
  w.header("VAq7");
  w.bytes(v.key_id_);
  write(w, v.update_);
  write(w, v.authorizations_);
  write(w, v.permit_);
  w.integer(v.fence_);
}
struct PrepareResult {
  KeyHandle prepared_{};
  Receipt receipt_{};
  bool operator==(const PrepareResult&) const = default;
};
inline void read(Reader& r, PrepareResult& v) {
  r.header("VAk3");
  read(r, v.prepared_);
  read(r, v.receipt_);
}
inline void write(Writer& w, const PrepareResult& v) {
  w.header("VAk3");
  write(w, v.prepared_);
  write(w, v.receipt_);
}
struct StageResult {
  Key key_{};
  PossessionAuth possession_{};
  Receipt receipt_{};
  bool operator==(const StageResult&) const = default;
};
inline void read(Reader& r, StageResult& v) {
  r.header("VAk4");
  read(r, v.key_);
  read(r, v.possession_);
  read(r, v.receipt_);
}
inline void write(Writer& w, const StageResult& v) {
  w.header("VAk4");
  write(w, v.key_);
  write(w, v.possession_);
  write(w, v.receipt_);
}
struct RetireResult {
  Hash key_id_{};
  Hash update_id_{};
  Receipt receipt_{};
  bool operator==(const RetireResult&) const = default;
};
inline void read(Reader& r, RetireResult& v) {
  r.header("VAk7");
  r.hash(v.key_id_);
  r.hash(v.update_id_);
  read(r, v.receipt_);
}
inline void write(Writer& w, const RetireResult& v) {
  w.header("VAk7");
  w.bytes(v.key_id_);
  w.bytes(v.update_id_);
  write(w, v.receipt_);
}
struct GetProfileRequest {
  Anchor anchor_{};
  bool operator==(const GetProfileRequest&) const = default;
};
inline void read(Reader& r, GetProfileRequest& v) {
  r.header("VAq8");
  read(r, v.anchor_);
}
inline void write(Writer& w, const GetProfileRequest& v) {
  w.header("VAq8");
  write(w, v.anchor_);
}
struct GetPolicyRequest {
  Anchor anchor_{};
  Hash policy_id_{};
  bool operator==(const GetPolicyRequest&) const = default;
};
inline void read(Reader& r, GetPolicyRequest& v) {
  r.header("VAq9");
  read(r, v.anchor_);
  r.hash(v.policy_id_);
}
inline void write(Writer& w, const GetPolicyRequest& v) {
  w.header("VAq9");
  write(w, v.anchor_);
  w.bytes(v.policy_id_);
}
struct GetRegistryRequest {
  Anchor anchor_{};
  std::uint8_t limit_{};
  std::vector<Cursor> cursor_{};
  bool operator==(const GetRegistryRequest&) const = default;
};
inline void read(Reader& r, GetRegistryRequest& v) {
  r.header("VAqa");
  read(r, v.anchor_);
  r.integer(v.limit_);
  r.list(v.cursor_, 1, 1, 180);
}
inline void write(Writer& w, const GetRegistryRequest& v) {
  w.header("VAqa");
  write(w, v.anchor_);
  w.integer(v.limit_);
  w.list(v.cursor_, 1, 1);
}
struct GetKeyRequest {
  Anchor anchor_{};
  Hash key_id_{};
  bool operator==(const GetKeyRequest&) const = default;
};
inline void read(Reader& r, GetKeyRequest& v) {
  r.header("VAqb");
  read(r, v.anchor_);
  r.hash(v.key_id_);
}
inline void write(Writer& w, const GetKeyRequest& v) {
  w.header("VAqb");
  write(w, v.anchor_);
  w.bytes(v.key_id_);
}
struct GetCertificateRequest {
  Anchor anchor_{};
  Hash certificate_id_{};
  bool operator==(const GetCertificateRequest&) const = default;
};
inline void read(Reader& r, GetCertificateRequest& v) {
  r.header("VAqc");
  read(r, v.anchor_);
  r.hash(v.certificate_id_);
}
inline void write(Writer& w, const GetCertificateRequest& v) {
  w.header("VAqc");
  write(w, v.anchor_);
  w.bytes(v.certificate_id_);
}
struct VerifyCertificateRequest {
  Anchor anchor_{};
  ObjectValue certificate_{};
  Proofref committee_{};
  Proofref policy_{};
  bool operator==(const VerifyCertificateRequest&) const = default;
};
inline void read(Reader& r, VerifyCertificateRequest& v) {
  r.header("VAqd");
  read(r, v.anchor_);
  read(r, v.certificate_);
  read(r, v.committee_);
  read(r, v.policy_);
}
inline void write(Writer& w, const VerifyCertificateRequest& v) {
  w.header("VAqd");
  write(w, v.anchor_);
  write(w, v.certificate_);
  write(w, v.committee_);
  write(w, v.policy_);
}
struct SignResultBody {
  Hash request_id_{};
  Hash statement_id_{};
  Record record_{};
  std::uint64_t fence_{};
  bool operator==(const SignResultBody&) const = default;
};
inline void read(Reader& r, SignResultBody& v) {
  r.header("VASb");
  r.hash(v.request_id_);
  r.hash(v.statement_id_);
  read(r, v.record_);
  r.integer(v.fence_);
}
inline void write(Writer& w, const SignResultBody& v) {
  w.header("VASb");
  w.bytes(v.request_id_);
  w.bytes(v.statement_id_);
  write(w, v.record_);
  w.integer(v.fence_);
}
struct PrepareResultBody {
  KeyHandle prepared_{};
  bool operator==(const PrepareResultBody&) const = default;
};
inline void read(Reader& r, PrepareResultBody& v) {
  r.header("VAkb");
  read(r, v.prepared_);
}
inline void write(Writer& w, const PrepareResultBody& v) {
  w.header("VAkb");
  write(w, v.prepared_);
}
struct StageResultBody {
  Key key_{};
  PossessionAuth possession_{};
  bool operator==(const StageResultBody&) const = default;
};
inline void read(Reader& r, StageResultBody& v) {
  r.header("VAsb");
  read(r, v.key_);
  read(r, v.possession_);
}
inline void write(Writer& w, const StageResultBody& v) {
  w.header("VAsb");
  write(w, v.key_);
  write(w, v.possession_);
}
struct RetireResultBody {
  Hash key_id_{};
  Hash update_id_{};
  bool operator==(const RetireResultBody&) const = default;
};
inline void read(Reader& r, RetireResultBody& v) {
  r.header("VArb");
  r.hash(v.key_id_);
  r.hash(v.update_id_);
}
inline void write(Writer& w, const RetireResultBody& v) {
  w.header("VArb");
  w.bytes(v.key_id_);
  w.bytes(v.update_id_);
}
struct ProfileState {
  Hash interface_digest_{};
  Hash policy_{};
  std::vector<Suite> active_{};
  bool operator==(const ProfileState&) const = default;
};
inline void read(Reader& r, ProfileState& v) {
  r.header("VAPs");
  r.hash(v.interface_digest_);
  r.hash(v.policy_);
  r.list(v.active_, 1, 2, 4);
}
inline void write(Writer& w, const ProfileState& v) {
  w.header("VAPs");
  w.bytes(v.interface_digest_);
  w.bytes(v.policy_);
  w.list(v.active_, 1, 2);
}
struct ChunkRequest {
  Anchor anchor_{};
  ObjectRef manifest_{};
  std::uint8_t index_{};
  bool operator==(const ChunkRequest&) const = default;
};
inline void read(Reader& r, ChunkRequest& v) {
  r.header("VAqe");
  read(r, v.anchor_);
  read(r, v.manifest_);
  r.integer(v.index_);
}
inline void write(Writer& w, const ChunkRequest& v) {
  w.header("VAqe");
  write(w, v.anchor_);
  write(w, v.manifest_);
  w.integer(v.index_);
}
struct ChunkResult {
  Anchor anchor_{};
  Hash manifest_id_{};
  std::uint8_t index_{};
  Bytes data_{};
  bool operator==(const ChunkResult&) const = default;
};
inline void read(Reader& r, ChunkResult& v) {
  r.header("VARe");
  read(r, v.anchor_);
  r.hash(v.manifest_id_);
  r.integer(v.index_);
  r.blob(v.data_, 1048576);
}
inline void write(Writer& w, const ChunkResult& v) {
  w.header("VARe");
  write(w, v.anchor_);
  w.bytes(v.manifest_id_);
  w.integer(v.index_);
  w.blob(v.data_, 1048576);
}
struct PutChunkRequest {
  Anchor anchor_{};
  ObjectRef manifest_{};
  std::uint8_t index_{};
  Bytes data_{};
  bool operator==(const PutChunkRequest&) const = default;
};
inline void read(Reader& r, PutChunkRequest& v) {
  r.header("VAqf");
  read(r, v.anchor_);
  read(r, v.manifest_);
  r.integer(v.index_);
  r.blob(v.data_, 1048576);
}
inline void write(Writer& w, const PutChunkRequest& v) {
  w.header("VAqf");
  write(w, v.anchor_);
  write(w, v.manifest_);
  w.integer(v.index_);
  w.blob(v.data_, 1048576);
}
struct PutChunkResult {
  Anchor anchor_{};
  Hash manifest_id_{};
  std::uint8_t index_{};
  bool operator==(const PutChunkResult&) const = default;
};
inline void read(Reader& r, PutChunkResult& v) {
  r.header("VARf");
  read(r, v.anchor_);
  r.hash(v.manifest_id_);
  r.integer(v.index_);
}
inline void write(Writer& w, const PutChunkResult& v) {
  w.header("VARf");
  write(w, v.anchor_);
  w.bytes(v.manifest_id_);
  w.integer(v.index_);
}
struct ServicePolicy {
  Hash issuer_{};
  std::uint64_t revision_{};
  Hash previous_{};
  std::vector<Suite> suites_{};
  bool operator==(const ServicePolicy&) const = default;
};
inline void read(Reader& r, ServicePolicy& v) {
  r.header("VASp");
  r.hash(v.issuer_);
  r.integer(v.revision_);
  r.hash(v.previous_);
  r.list(v.suites_, 1, 2, 4);
}
inline void write(Writer& w, const ServicePolicy& v) {
  w.header("VASp");
  w.bytes(v.issuer_);
  w.integer(v.revision_);
  w.bytes(v.previous_);
  w.list(v.suites_, 1, 2);
}
} // namespace tos::auth
