// Copyright 2026 TOS Blockchain Teams. SPDX-License-Identifier: GPL-3.0-only
//! Per-key, non-authorizing V5R2 proof-of-possession wire encoding.
//!
//! Challenges must be freshly generated by the client and checked against an
//! authenticated transaction. A repeated POP is not enrollment or authority.
//! Receipt checks consume authenticated transactions and locally pinned enrollment.
//! They do not independently verify signatures or replace chain-proof verification.
use crate::wallet_v5r2::{AuthRole, encode_pq_submission};
use chain_block::{BuilderData, Cell, Deserializable, IBitstring, StateInit};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RescuePolicy {
    Ready,
    Required,
}

pub struct PopBinding {
    pub global_id: i32,
    pub network: [u8; 32],
    pub account: [u8; 32],
    pub module: [u8; 32],
    pub challenge: [u8; 32],
    pub valid_until: u32,
}

/// Authenticated transactions and their authenticated pre-states for one POP
/// paid by the enrolled fee vault. Neither transaction alone proves delivery.
pub struct FundedPopReceipts<'a> {
    pub fee: &'a crate::proven_transactions::ProvenTransaction,
    pub module: &'a crate::proven_transactions::ProvenTransaction,
    pub fee_before: Cell,
    pub module_before: Cell,
}

/// Immutable POP3 request with a PPS3 submission, separate from AUTH/SUB3.
pub struct PopRequest {
    cell: Cell,
    role: AuthRole,
    digest: [u8; 32],
}

impl PopRequest {
    /// Reconstruct a retained initial challenge for a verified execution time.
    /// Parsing is not proof of possession or challenge freshness. Receipt checks
    /// must still bind its exact bytes to authenticated funded execution.
    pub fn from_initial_cell(
        cell: Cell,
        enrollment: &crate::wallet_v5r2_genesis::WalletGenesis,
        execution_time: u32,
    ) -> anyhow::Result<Self> {
        use chain_block::{CellType, SliceData};
        anyhow::ensure!(
            cell.cell_type() == CellType::Ordinary && cell.level() == 0,
            "ordinary POP request required"
        );
        let mut wire = SliceData::load_cell(cell.clone())?;
        anyhow::ensure!(
            wire.remaining_bits() == 616 && wire.remaining_references() == 2,
            "retained POP request shape mismatch"
        );
        anyhow::ensure!(wire.get_next_u32()? == 0x504f5033, "retained POP opcode mismatch");
        wire.move_by(32 + 256)?;
        let role = match wire.get_next_byte()? {
            1 => AuthRole::Primary,
            2 => AuthRole::Rescue,
            _ => anyhow::bail!("retained POP role invalid"),
        };
        let challenge = *wire.get_next_hash()?.as_array();
        let deadline = wire.get_next_u32()?;
        let (request, _, _) = Self::from_enrolled(
            enrollment.module_init(),
            *enrollment.wallet_init().repr_hash().as_array(),
            role,
            challenge,
            deadline,
            execution_time,
        )?;
        anyhow::ensure!(
            request.cell.repr_hash() == cell.repr_hash(),
            "retained POP enrollment or canonical encoding mismatch"
        );
        Ok(request)
    }

    /// `primary_key_hash` is the hash of the canonical 1,312-byte public-key
    /// cell chain, not a hash of raw bytes. All bindings must match verified
    /// module state; `proven_time` is from a fresh proof-checked chain view.
    pub fn new(
        binding: PopBinding,
        role: AuthRole,
        policy: RescuePolicy,
        primary_key_hash: [u8; 32],
        rescue_key: [u8; 32],
        proven_time: u32,
    ) -> anyhow::Result<Self> {
        anyhow::ensure!(binding.challenge != [0; 32], "POP challenge must be nonzero");
        anyhow::ensure!(binding.account != binding.module, "wallet and module must differ");
        let ttl = binding
            .valid_until
            .checked_sub(proven_time)
            .ok_or_else(|| anyhow::anyhow!("expired POP deadline"))?;
        anyhow::ensure!((1..=3600).contains(&ttl), "POP TTL must be 1..=3600 seconds");
        let mut parties = BuilderData::new();
        parties.append_raw(&[0x80, 0], 11)?;
        parties.append_u256(&binding.account)?;
        parties.append_u256(&binding.module)?;
        let mut keys = BuilderData::new();
        keys.append_u8(1)?; // ML-DSA-44 only.
        keys.append_u256(&primary_key_hash)?;
        keys.append_u256(&rescue_key)?;
        keys.append_u8(match policy {
            RescuePolicy::Ready => 1,
            RescuePolicy::Required => 2,
        })?;
        let mut b = BuilderData::new();
        b.append_u32(0x504f5033)?;
        b.append_i32(binding.global_id)?;
        b.append_u256(&binding.network)?;
        b.append_u8(match role {
            AuthRole::Primary => 1,
            AuthRole::Rescue => 2,
        })?;
        b.append_u256(&binding.challenge)?;
        b.append_u32(binding.valid_until)?;
        b.checked_append_reference(parties.into_cell()?)?;
        b.checked_append_reference(keys.into_cell()?)?;
        let cell = b.into_cell()?;
        let mut domain = BuilderData::new();
        domain.append_raw(b"TOS-POP1", 64)?;
        domain.checked_append_reference(cell.clone())?;
        let digest = *domain.into_cell()?.repr_hash().as_array();
        Ok(Self { cell, role, digest })
    }

    /// Prove execution of this freshly generated challenge under the enrolled
    /// module code/key data. This is per-key possession, never wallet authority.
    pub fn require_initial_receipt(
        &self,
        receipt: &crate::proven_transactions::ProvenTransaction,
        pre_state: Cell,
        enrollment: &crate::wallet_v5r2_genesis::WalletGenesis,
    ) -> anyhow::Result<()> {
        self.require_receipt(
            receipt,
            pre_state,
            enrollment.module_init(),
            *enrollment.wallet_init().repr_hash().as_array(),
        )
    }

    pub fn require_successor_receipt(
        &self,
        receipt: &crate::proven_transactions::ProvenTransaction,
        pre_state: Cell,
        enrollment: &crate::wallet_v5r2_genesis::SuccessorDeployment,
    ) -> anyhow::Result<()> {
        self.require_receipt(receipt, pre_state, enrollment.module_init(), *enrollment.wallet())
    }

    /// Prove that the enrolled initial fee route funded this exact POP.
    pub fn require_initial_funded_receipt(
        &self,
        receipts: &FundedPopReceipts<'_>,
        submitted_external: &Cell,
        enrollment: &crate::wallet_v5r2_genesis::WalletGenesis,
    ) -> anyhow::Result<()> {
        self.require_funded_receipt(
            receipts,
            submitted_external,
            enrollment.module_init(),
            enrollment.vault_init(),
            *enrollment.wallet_init().repr_hash().as_array(),
        )
    }

    /// Historical funded POP through the exact successor vault, before migration.
    /// This is per-key evidence; both keys and current route readiness are needed.
    pub fn require_successor_funded_receipt(
        &self,
        receipts: &FundedPopReceipts<'_>,
        submitted_external: &Cell,
        enrollment: &crate::wallet_v5r2_genesis::SuccessorDeployment,
    ) -> anyhow::Result<()> {
        self.require_funded_receipt(
            receipts,
            submitted_external,
            enrollment.module_init(),
            enrollment.vault_init(),
            *enrollment.wallet(),
        )
    }

    pub(crate) fn require_funded_receipt(
        &self,
        receipts: &FundedPopReceipts<'_>,
        submitted_external: &Cell,
        module_init: &Cell,
        vault_init: &Cell,
        wallet: [u8; 32],
    ) -> anyhow::Result<()> {
        let before = receipts.fee.pre_account(receipts.fee_before.clone())?;
        let init = StateInit::construct_from_cell(vault_init.clone())?;
        anyhow::ensure!(
            before.get_addr().map(ToString::to_string)
                == Some(format!("0:{}", vault_init.repr_hash().to_hex_string())),
            "POP funding vault address mismatch"
        );
        anyhow::ensure!(before.get_code() == init.code, "POP funding vault code mismatch");
        let data =
            before.get_data().ok_or_else(|| anyhow::anyhow!("POP funding vault data missing"))?;
        let expected =
            init.data.ok_or_else(|| anyhow::anyhow!("POP funding enrollment data missing"))?;
        crate::wallet_v5r2_state::checked_counter(&data, &expected)?;
        receipts.fee.require_inbound(submitted_external)?;
        let input = receipts
            .fee
            .transaction()
            .read_in_msg()?
            .ok_or_else(|| anyhow::anyhow!("POP funding input missing"))?;
        anyhow::ensure!(input.is_inbound_external(), "POP funding requires external input");
        self.require_receipt(receipts.module, receipts.module_before.clone(), module_init, wallet)?;
        let delivered = receipts
            .module
            .transaction()
            .in_msg_cell()
            .ok_or_else(|| anyhow::anyhow!("POP module input missing"))?;
        receipts.fee.require_internal_delivery(receipts.module, delivered.repr_hash().as_array())
    }

    pub(crate) fn require_receipt(
        &self,
        receipt: &crate::proven_transactions::ProvenTransaction,
        pre_state: Cell,
        module_init: &Cell,
        wallet: [u8; 32],
    ) -> anyhow::Result<()> {
        use chain_block::SliceData;
        let mut original = SliceData::load_cell(self.cell.clone())?;
        original.move_by(32 + 32 + 256 + 8)?;
        let challenge = *original.get_next_hash()?.as_array();
        let valid_until = original.get_next_u32()?;
        let (expected, _, _) = Self::from_enrolled(
            module_init,
            wallet,
            self.role,
            challenge,
            valid_until,
            receipt.transaction().now(),
        )?;
        anyhow::ensure!(
            expected.cell.repr_hash() == self.cell.repr_hash(),
            "POP receipt enrollment binding mismatch"
        );
        let before = receipt.pre_account(pre_state)?;
        let init = StateInit::construct_from_cell(module_init.clone())?;
        let address =
            before.get_addr().ok_or_else(|| anyhow::anyhow!("POP pre-state has no address"))?;
        anyhow::ensure!(
            address.to_string() == format!("0:{}", module_init.repr_hash().to_hex_string()),
            "POP module address differs from enrollment"
        );
        anyhow::ensure!(
            before.get_code() == init.code && before.get_data() == init.data,
            "POP executed code or keys differ from enrollment"
        );
        receipt.require_complete_execution()?;
        let message = receipt
            .transaction()
            .read_in_msg()?
            .ok_or_else(|| anyhow::anyhow!("POP inbound missing"))?;
        let header = message.int_header().ok_or_else(|| anyhow::anyhow!("POP must be internal"))?;
        anyhow::ensure!(!header.bounced, "bounced message is not POP");
        let mut body =
            message.body().cloned().ok_or_else(|| anyhow::anyhow!("POP body missing"))?;
        anyhow::ensure!(
            body.remaining_bits() == 32 && body.remaining_references() == 2,
            "POP submission shape mismatch"
        );
        anyhow::ensure!(body.get_next_u32()? == 0x50505333, "POP submission opcode mismatch");
        let challenge = body.checked_drain_reference()?;
        anyhow::ensure!(
            challenge.repr_hash() == self.cell.repr_hash(),
            "POP challenge differs from request"
        );
        // The proven execution of enrolled code verifies the signature reference.
        // No signature verdict is taken from RPC or inferred from framing alone.
        Ok(())
    }

    pub fn cell(&self) -> &Cell {
        &self.cell
    }
    pub fn digest(&self) -> &[u8; 32] {
        &self.digest
    }
    pub fn role(&self) -> AuthRole {
        self.role
    }
    pub fn signing_context(&self) -> &'static [u8] {
        b"TOS-RESCUE-POP-v1"
    }

    /// Framing only; exact role size does not imply signature validity.
    pub fn encode_submission(&self, signature: &[u8]) -> anyhow::Result<Cell> {
        encode_pq_submission(0x50505333, &self.cell, self.role, signature)
    }

    /// Generate a new CSPRNG challenge bound to the complete initial enrollment.
    /// Time must come from fresh verified chain evidence. Retain this exact
    /// request through funded execution and receipt verification; regenerating
    /// during a retry creates a different possession proof.
    #[cfg(feature = "native-wallet-signer")]
    pub fn fresh_initial(
        enrollment: &crate::wallet_v5r2_genesis::WalletGenesis,
        role: AuthRole,
        valid_until: u32,
        proven_time: u32,
    ) -> anyhow::Result<Self> {
        let (request, _, _) = Self::from_enrolled(
            enrollment.module_init(),
            *enrollment.wallet_init().repr_hash().as_array(),
            role,
            wallet_pq_signer::fresh_pop_challenge()?,
            valid_until,
            proven_time,
        )?;
        Ok(request)
    }

    /// Generate a fresh challenge for a proposed successor before migration.
    #[cfg(feature = "native-wallet-signer")]
    pub fn fresh_successor(
        enrollment: &crate::wallet_v5r2_genesis::SuccessorDeployment,
        role: AuthRole,
        valid_until: u32,
        proven_time: u32,
    ) -> anyhow::Result<Self> {
        let (request, _, _) = Self::from_enrolled(
            enrollment.module_init(),
            *enrollment.wallet(),
            role,
            wallet_pq_signer::fresh_pop_challenge()?,
            valid_until,
            proven_time,
        )?;
        Ok(request)
    }

    /// Sign this challenge only for the exact locally pinned enrollment. POP
    /// confers no authority and does not depend on primary retirement policy.
    /// Caller supplies fresh proof-checked chain time and a fresh challenge;
    /// require_initial_receipt must still establish its funded execution.
    #[cfg(feature = "native-wallet-signer")]
    pub fn sign_initial(
        &self,
        enrollment: &crate::wallet_v5r2_genesis::WalletGenesis,
        proven_time: u32,
        signer: &mut wallet_pq_signer::Signer,
    ) -> anyhow::Result<Cell> {
        self.sign_enrolled(
            enrollment.module_init(),
            *enrollment.wallet_init().repr_hash().as_array(),
            proven_time,
            signer,
        )
    }

    /// Successor POP is allowed before installation in the wallet. Its receipt
    /// proves possession/execution for this exact proposed tuple, not migration.
    #[cfg(feature = "native-wallet-signer")]
    pub fn sign_successor(
        &self,
        enrollment: &crate::wallet_v5r2_genesis::SuccessorDeployment,
        proven_time: u32,
        signer: &mut wallet_pq_signer::Signer,
    ) -> anyhow::Result<Cell> {
        self.sign_enrolled(enrollment.module_init(), *enrollment.wallet(), proven_time, signer)
    }

    fn from_enrolled(
        module_init: &Cell,
        wallet: [u8; 32],
        role: AuthRole,
        challenge: [u8; 32],
        valid_until: u32,
        proven_time: u32,
    ) -> anyhow::Result<(Self, Cell, [u8; 32])> {
        use chain_block::SliceData;
        let init = StateInit::construct_from_cell(module_init.clone())?;
        let data = init.data.ok_or_else(|| anyhow::anyhow!("enrolled module data missing"))?;
        let mut data = SliceData::load_cell(data)?;
        anyhow::ensure!(data.get_next_byte()? == 1, "unsupported module layout");
        let global_id = i32::from_be_bytes(data.get_next_u32()?.to_be_bytes());
        let network = *data.get_next_hash()?.as_array();
        anyhow::ensure!(data.get_next_byte()? == 1, "unsupported primary suite");
        let rescue_key = *data.get_next_hash()?.as_array();
        let policy = match data.get_next_byte()? {
            1 => RescuePolicy::Ready,
            2 => RescuePolicy::Required,
            _ => anyhow::bail!("unsupported rescue policy"),
        };
        let primary = data.checked_drain_reference()?;
        anyhow::ensure!(
            data.remaining_bits() == 0 && data.remaining_references() == 0,
            "module data tail"
        );
        let request = Self::new(
            PopBinding {
                global_id,
                network,
                account: wallet,
                module: *module_init.repr_hash().as_array(),
                challenge,
                valid_until,
            },
            role,
            policy,
            *primary.repr_hash().as_array(),
            rescue_key,
            proven_time,
        )?;
        Ok((request, primary, rescue_key))
    }

    #[cfg(feature = "native-wallet-signer")]
    fn sign_enrolled(
        &self,
        module_init: &Cell,
        wallet: [u8; 32],
        proven_time: u32,
        signer: &mut wallet_pq_signer::Signer,
    ) -> anyhow::Result<Cell> {
        let (role, key) = self.enrolled_signing_key(module_init, wallet, proven_time)?;
        let signature =
            signer.sign_bound(role, &key, wallet_pq_signer::Purpose::Pop, self.digest())?;
        self.encode_submission(&signature)
    }

    /// Resolve custody only after validating the complete pinned enrollment and
    /// deadline. Shared by native signing and asynchronous Vault preflight.
    #[cfg(feature = "native-wallet-signer")]
    pub(crate) fn enrolled_signing_key(
        &self,
        module_init: &Cell,
        wallet: [u8; 32],
        proven_time: u32,
    ) -> anyhow::Result<(wallet_pq_signer::Role, Vec<u8>)> {
        use chain_block::SliceData;
        let mut original = SliceData::load_cell(self.cell.clone())?;
        original.move_by(32 + 32 + 256 + 8)?;
        let challenge = *original.get_next_hash()?.as_array();
        let valid_until = original.get_next_u32()?;
        let (expected, primary, rescue_key) = Self::from_enrolled(
            module_init,
            wallet,
            self.role,
            challenge,
            valid_until,
            proven_time,
        )?;
        anyhow::ensure!(
            expected.cell.repr_hash() == self.cell.repr_hash(),
            "POP enrollment binding mismatch"
        );
        let (role, key) = match self.role {
            AuthRole::Primary => (
                wallet_pq_signer::Role::Primary,
                crate::wallet_v5r2_wallet_state::primary_key_bytes(primary)?,
            ),
            AuthRole::Rescue => (wallet_pq_signer::Role::Rescue, rescue_key.to_vec()),
        };
        Ok((role, key))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn hash(value: u8) -> [u8; 32] {
        let mut h = [0; 32];
        h[31] = value;
        h
    }
    fn binding() -> PopBinding {
        PopBinding {
            global_id: 42,
            network: hash(123),
            account: hash(100),
            module: hash(101),
            challenge: hash(99),
            valid_until: 1_780_000_600,
        }
    }
    fn request(b: PopBinding, role: AuthRole, policy: RescuePolicy) -> anyhow::Result<PopRequest> {
        PopRequest::new(b, role, policy, hash(111), hash(222), 1_780_000_000)
    }
    #[test]
    fn retained_initial_pop_reconstructs_only_exact_enrollment() {
        use crate::wallet_v5r2_genesis::{
            WalletGenesis,
            tests::{bundle, parameters},
        };
        let enrollment = WalletGenesis::new(bundle(), parameters()).expect("enrollment");
        let now = 1_780_000_000;
        for role in [AuthRole::Primary, AuthRole::Rescue] {
            let (request, _, _) = PopRequest::from_enrolled(
                enrollment.module_init(),
                *enrollment.wallet_init().repr_hash().as_array(),
                role,
                [7; 32],
                now + 600,
                now,
            )
            .expect("request");
            let restored = PopRequest::from_initial_cell(request.cell().clone(), &enrollment, now)
                .expect("retained request");
            assert_eq!(restored.digest(), request.digest());
            assert_eq!(restored.role(), role);
            assert!(
                PopRequest::from_initial_cell(request.cell().clone(), &enrollment, now + 600)
                    .is_err()
            );
            let (other, _, _) = PopRequest::from_enrolled(
                enrollment.module_init(),
                [9; 32],
                role,
                [7; 32],
                now + 600,
                now,
            )
            .expect("different wallet");
            assert!(
                PopRequest::from_initial_cell(other.cell().clone(), &enrollment, now).is_err(),
                "retained POP accepted another wallet"
            );
        }
        assert!(PopRequest::from_initial_cell(Cell::default(), &enrollment, now).is_err());
    }

    #[test]
    fn independent_pop_vectors() {
        let vectors: serde_json::Value =
            serde_json::from_str(include_str!("../tests/fixtures/v5r2/pop-wire.json"))
                .expect("vectors");
        for item in vectors.as_array().expect("array") {
            let role = if item["role"] == 1 { AuthRole::Primary } else { AuthRole::Rescue };
            let policy =
                if item["policy"] == 1 { RescuePolicy::Ready } else { RescuePolicy::Required };
            let req = request(binding(), role, policy).expect("request");
            assert_eq!(hex::encode(req.cell().repr_hash().as_array()), item["request_hash"]);
            assert_eq!(hex::encode(req.digest()), item["digest"]);
            assert_eq!(req.signing_context(), b"TOS-RESCUE-POP-v1");
            let sub = req.encode_submission(&vec![0xa5; role.signature_bytes()]).expect("framing");
            assert_eq!(hex::encode(sub.repr_hash().as_array()), item["submission_hash"]);
            for len in [64, role.signature_bytes() - 1, role.signature_bytes() + 1] {
                assert!(req.encode_submission(&vec![0; len]).is_err());
            }
        }
    }
    #[test]
    fn zero_challenge_and_equal_parties_refused() {
        let mut b = binding();
        b.challenge = [0; 32];
        assert!(
            request(b, AuthRole::Rescue, RescuePolicy::Required)
                .err()
                .expect("zero challenge refused")
                .to_string()
                .contains("challenge must be nonzero")
        );
        let mut b = binding();
        b.module = b.account;
        assert!(
            request(b, AuthRole::Rescue, RescuePolicy::Required)
                .err()
                .expect("equal parties refused")
                .to_string()
                .contains("wallet and module must differ")
        );
    }
    #[test]
    fn pop_deadline_boundaries() {
        for delta in [-1i64, 0, 1, 3600, 3601] {
            let mut b = binding();
            b.valid_until = u32::try_from(1_780_000_000i64 + delta).expect("time");
            assert_eq!(
                request(b, AuthRole::Primary, RescuePolicy::Ready).is_ok(),
                delta > 0 && delta <= 3600
            );
        }
    }
}
