// Copyright 2026 TOS Blockchain Teams. SPDX-License-Identifier: GPL-3.0-only
//! Per-key, non-authorizing V5R2 proof-of-possession wire encoding.
//!
//! Challenges must be freshly generated by the client and checked against an
//! authenticated transaction. A repeated POP is not enrollment or authority.
//! This module does not verify signatures, chain proofs or module code identity.
use crate::wallet_v5r2::{AuthRole, encode_pq_submission};
use chain_block::{BuilderData, Cell, IBitstring};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RescuePolicy {
    Ready,
    Required,
}

pub struct PopBinding {
    pub global_id: i32,
    pub network: [u8; 32],
    pub account: [u8; 32],
    pub module: [u8; 32],
    pub challenge: [u8; 32],
    pub valid_until: u32,
}

/// Immutable POP3 request with a PPS3 submission, separate from AUTH/SUB3.
pub struct PopRequest {
    cell: Cell,
    role: AuthRole,
    digest: [u8; 32],
}

impl PopRequest {
    /// `primary_key_hash` is the hash of the canonical 1,312-byte public-key
    /// cell chain, not a hash of raw bytes. All bindings must match verified
    /// module state; `proven_time` is from a fresh proof-checked chain view.
    pub fn new(
        binding: PopBinding,
        role: AuthRole,
        policy: RescuePolicy,
        primary_key_hash: [u8; 32],
        rescue_key: [u8; 32],
        proven_time: u32,
    ) -> anyhow::Result<Self> {
        anyhow::ensure!(binding.challenge != [0; 32], "POP challenge must be nonzero");
        anyhow::ensure!(binding.account != binding.module, "wallet and module must differ");
        let ttl = binding
            .valid_until
            .checked_sub(proven_time)
            .ok_or_else(|| anyhow::anyhow!("expired POP deadline"))?;
        anyhow::ensure!((1..=3600).contains(&ttl), "POP TTL must be 1..=3600 seconds");
        let mut parties = BuilderData::new();
        parties.append_raw(&[0x80, 0], 11)?;
        parties.append_u256(&binding.account)?;
        parties.append_u256(&binding.module)?;
        let mut keys = BuilderData::new();
        keys.append_u8(1)?; // ML-DSA-44 only.
        keys.append_u256(&primary_key_hash)?;
        keys.append_u256(&rescue_key)?;
        keys.append_u8(match policy {
            RescuePolicy::Ready => 1,
            RescuePolicy::Required => 2,
        })?;
        let mut b = BuilderData::new();
        b.append_u32(0x504f5033)?;
        b.append_i32(binding.global_id)?;
        b.append_u256(&binding.network)?;
        b.append_u8(match role {
            AuthRole::Primary => 1,
            AuthRole::Rescue => 2,
        })?;
        b.append_u256(&binding.challenge)?;
        b.append_u32(binding.valid_until)?;
        b.checked_append_reference(parties.into_cell()?)?;
        b.checked_append_reference(keys.into_cell()?)?;
        let cell = b.into_cell()?;
        let mut domain = BuilderData::new();
        domain.append_raw(b"TOS-POP1", 64)?;
        domain.checked_append_reference(cell.clone())?;
        let digest = *domain.into_cell()?.repr_hash().as_array();
        Ok(Self { cell, role, digest })
    }

    pub fn cell(&self) -> &Cell {
        &self.cell
    }
    pub fn digest(&self) -> &[u8; 32] {
        &self.digest
    }
    pub fn role(&self) -> AuthRole {
        self.role
    }
    pub fn signing_context(&self) -> &'static [u8] {
        b"TOS-RESCUE-POP-v1"
    }

    /// Framing only; exact role size does not imply signature validity.
    pub fn encode_submission(&self, signature: &[u8]) -> anyhow::Result<Cell> {
        encode_pq_submission(0x50505333, &self.cell, self.role, signature)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn hash(value: u8) -> [u8; 32] {
        let mut h = [0; 32];
        h[31] = value;
        h
    }
    fn binding() -> PopBinding {
        PopBinding {
            global_id: 42,
            network: hash(123),
            account: hash(100),
            module: hash(101),
            challenge: hash(99),
            valid_until: 1_780_000_600,
        }
    }
    fn request(b: PopBinding, role: AuthRole, policy: RescuePolicy) -> anyhow::Result<PopRequest> {
        PopRequest::new(b, role, policy, hash(111), hash(222), 1_780_000_000)
    }
    #[test]
    fn independent_pop_vectors() {
        let vectors: serde_json::Value =
            serde_json::from_str(include_str!("../tests/fixtures/v5r2/pop-wire.json"))
                .expect("vectors");
        for item in vectors.as_array().expect("array") {
            let role = if item["role"] == 1 { AuthRole::Primary } else { AuthRole::Rescue };
            let policy =
                if item["policy"] == 1 { RescuePolicy::Ready } else { RescuePolicy::Required };
            let req = request(binding(), role, policy).expect("request");
            assert_eq!(hex::encode(req.cell().repr_hash().as_array()), item["request_hash"]);
            assert_eq!(hex::encode(req.digest()), item["digest"]);
            assert_eq!(req.signing_context(), b"TOS-RESCUE-POP-v1");
            let sub = req.encode_submission(&vec![0xa5; role.signature_bytes()]).expect("framing");
            assert_eq!(hex::encode(sub.repr_hash().as_array()), item["submission_hash"]);
            for len in [64, role.signature_bytes() - 1, role.signature_bytes() + 1] {
                assert!(req.encode_submission(&vec![0; len]).is_err());
            }
        }
    }
    #[test]
    fn zero_challenge_and_equal_parties_refused() {
        let mut b = binding();
        b.challenge = [0; 32];
        assert!(
            request(b, AuthRole::Rescue, RescuePolicy::Required)
                .err()
                .expect("zero challenge refused")
                .to_string()
                .contains("challenge must be nonzero")
        );
        let mut b = binding();
        b.module = b.account;
        assert!(
            request(b, AuthRole::Rescue, RescuePolicy::Required)
                .err()
                .expect("equal parties refused")
                .to_string()
                .contains("wallet and module must differ")
        );
    }
    #[test]
    fn pop_deadline_boundaries() {
        for delta in [-1i64, 0, 1, 3600, 3601] {
            let mut b = binding();
            b.valid_until = u32::try_from(1_780_000_000i64 + delta).expect("time");
            assert_eq!(
                request(b, AuthRole::Primary, RescuePolicy::Ready).is_ok(),
                delta > 0 && delta <= 3600
            );
        }
    }
}
