name: Clear all GH cache

on:
  workflow_dispatch

permissions: {}

jobs:
  clear-cache:
    permissions:
      contents: read
      actions: write
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Clear all cache
        run: gh cache delete --all
