#pragma once
#include <array>
#include <cstddef>
namespace tos::health {
struct FixedMetricDescriptor {
  const char *name; const char *type; const char *suffix;
  std::array<std::array<const char *, 2>, 3> labels; std::size_t label_count; double scale;
};
inline constexpr std::array<FixedMetricDescriptor, 149> consensus_metric_catalog{{
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "proposal"}}, {{"phase", "requested"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "proposal"}}, {{"phase", "signed"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "proposal"}}, {{"phase", "candidate_published"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "proposal"}}, {{"outcome", "enqueued"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "proposal"}}, {{"outcome", "failed"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "proposal"}}, {{"outcome", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "proposal"}}, {{"outcome", "suppressed"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "proposal"}}, {{"outcome", "unknown"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_pending", "gauge", "", {{{{"action", "proposal"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_action_oldest_age_seconds", "gauge", "", {{{{"action", "proposal"}}, {{"", ""}}, {{"", ""}}}}, 1, 1e-09},
  {"tos_consensus_action_accounting_complete", "gauge", "", {{{{"action", "proposal"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "proposal"}}, {{"reason", "missing_signer"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "proposal"}}, {{"reason", "sign_backend"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "proposal"}}, {{"reason", "finality_behind"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "proposal"}}, {{"reason", "superseded"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "proposal"}}, {{"reason", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "requested"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "intent_committed"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "signed"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "signed_committed"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "local_applied"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "broadcast_enqueued"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "requested"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "signed"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "signed_committed"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "restored_signed"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"phase", "local_applied"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"outcome", "enqueued"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"outcome", "failed"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"outcome", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"outcome", "suppressed"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"outcome", "unknown"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_pending", "gauge", "", {{{{"action", "notarize_vote"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_action_oldest_age_seconds", "gauge", "", {{{{"action", "notarize_vote"}}, {{"", ""}}, {{"", ""}}}}, 1, 1e-09},
  {"tos_consensus_action_accounting_complete", "gauge", "", {{{{"action", "notarize_vote"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"reason", "intent_storage"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"reason", "missing_signer"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"reason", "sign_backend"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"reason", "signed_storage"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"reason", "duplicate_or_stale"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"reason", "finality_behind"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"reason", "journal_unusable"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "notarize_vote"}}, {{"reason", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "requested"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "intent_committed"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "signed"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "signed_committed"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "local_applied"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "broadcast_enqueued"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "requested"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "signed"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "signed_committed"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "restored_signed"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"phase", "local_applied"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"outcome", "enqueued"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"outcome", "failed"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"outcome", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"outcome", "suppressed"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"outcome", "unknown"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_pending", "gauge", "", {{{{"action", "finalize_vote"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_action_oldest_age_seconds", "gauge", "", {{{{"action", "finalize_vote"}}, {{"", ""}}, {{"", ""}}}}, 1, 1e-09},
  {"tos_consensus_action_accounting_complete", "gauge", "", {{{{"action", "finalize_vote"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"reason", "intent_storage"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"reason", "missing_signer"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"reason", "sign_backend"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"reason", "signed_storage"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"reason", "duplicate_or_stale"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"reason", "finality_behind"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"reason", "journal_unusable"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "finalize_vote"}}, {{"reason", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "requested"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "intent_committed"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "signed"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "signed_committed"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "local_applied"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "broadcast_enqueued"}}, {{"origin", "live"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "requested"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "signed"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "signed_committed"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "restored_signed"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_actions_total", "counter", "", {{{{"action", "skip_vote"}}, {{"phase", "local_applied"}}, {{"origin", "replay"}}}}, 3, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "skip_vote"}}, {{"outcome", "enqueued"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "skip_vote"}}, {{"outcome", "failed"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "skip_vote"}}, {{"outcome", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "skip_vote"}}, {{"outcome", "suppressed"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_outcomes_total", "counter", "", {{{{"action", "skip_vote"}}, {{"outcome", "unknown"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_pending", "gauge", "", {{{{"action", "skip_vote"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_action_oldest_age_seconds", "gauge", "", {{{{"action", "skip_vote"}}, {{"", ""}}, {{"", ""}}}}, 1, 1e-09},
  {"tos_consensus_action_accounting_complete", "gauge", "", {{{{"action", "skip_vote"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "skip_vote"}}, {{"reason", "intent_storage"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "skip_vote"}}, {{"reason", "missing_signer"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "skip_vote"}}, {{"reason", "sign_backend"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "skip_vote"}}, {{"reason", "signed_storage"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "skip_vote"}}, {{"reason", "duplicate_or_stale"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "skip_vote"}}, {{"reason", "finality_behind"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "skip_vote"}}, {{"reason", "journal_unusable"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_action_failures_total", "counter", "", {{{{"action", "skip_vote"}}, {{"reason", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_proposal_retries_total", "counter", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_consensus_proposal_empty_candidates_total", "counter", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_consensus_sessions", "gauge", "", {{{{"state", "active"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_sessions", "gauge", "", {{{{"state", "stopping"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_sessions_started_total", "counter", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_consensus_session_stop_started_total", "counter", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_consensus_sessions_stopped_total", "counter", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_consensus_leader_windows_total", "counter", "", {{{{"result", "observed"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_leader_windows_total", "counter", "", {{{{"result", "started"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_storage_operations_total", "counter", "", {{{{"operation", "own_vote_intent"}}, {{"result", "success"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operations_total", "counter", "", {{{{"operation", "own_vote_intent"}}, {{"result", "failure"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operations_total", "counter", "", {{{{"operation", "own_vote_intent"}}, {{"result", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operations_total", "counter", "", {{{{"operation", "own_vote_intent"}}, {{"result", "duplicate"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "bucket", {{{{"operation", "own_vote_intent"}}, {{"result", "success"}}, {{"le", "1"}}}}, 3, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "bucket", {{{{"operation", "own_vote_intent"}}, {{"result", "success"}}, {{"le", "+Inf"}}}}, 3, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "count", {{{{"operation", "own_vote_intent"}}, {{"result", "success"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "sum", {{{{"operation", "own_vote_intent"}}, {{"result", "success"}}, {{"", ""}}}}, 2, 1e-06},
  {"tos_storage_operation_duration_seconds", "histogram", "bucket", {{{{"operation", "own_vote_intent"}}, {{"result", "failure"}}, {{"le", "1"}}}}, 3, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "bucket", {{{{"operation", "own_vote_intent"}}, {{"result", "failure"}}, {{"le", "+Inf"}}}}, 3, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "count", {{{{"operation", "own_vote_intent"}}, {{"result", "failure"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "sum", {{{{"operation", "own_vote_intent"}}, {{"result", "failure"}}, {{"", ""}}}}, 2, 1e-06},
  {"tos_storage_operations_total", "counter", "", {{{{"operation", "own_signed_vote"}}, {{"result", "success"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operations_total", "counter", "", {{{{"operation", "own_signed_vote"}}, {{"result", "failure"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operations_total", "counter", "", {{{{"operation", "own_signed_vote"}}, {{"result", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operations_total", "counter", "", {{{{"operation", "own_signed_vote"}}, {{"result", "duplicate"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "bucket", {{{{"operation", "own_signed_vote"}}, {{"result", "success"}}, {{"le", "1"}}}}, 3, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "bucket", {{{{"operation", "own_signed_vote"}}, {{"result", "success"}}, {{"le", "+Inf"}}}}, 3, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "count", {{{{"operation", "own_signed_vote"}}, {{"result", "success"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "sum", {{{{"operation", "own_signed_vote"}}, {{"result", "success"}}, {{"", ""}}}}, 2, 1e-06},
  {"tos_storage_operation_duration_seconds", "histogram", "bucket", {{{{"operation", "own_signed_vote"}}, {{"result", "failure"}}, {{"le", "1"}}}}, 3, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "bucket", {{{{"operation", "own_signed_vote"}}, {{"result", "failure"}}, {{"le", "+Inf"}}}}, 3, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "count", {{{{"operation", "own_signed_vote"}}, {{"result", "failure"}}, {{"", ""}}}}, 2, 1},
  {"tos_storage_operation_duration_seconds", "histogram", "sum", {{{{"operation", "own_signed_vote"}}, {{"result", "failure"}}, {{"", ""}}}}, 2, 1e-06},
  {"tos_state_resolver_waiters", "gauge", "", {{{{"kind", "state"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_state_resolver_oldest_waiter_age_seconds", "gauge", "", {{{{"kind", "state"}}, {{"", ""}}, {{"", ""}}}}, 1, 1e-09},
  {"tos_state_resolver_results_total", "counter", "", {{{{"operation", "state"}}, {{"result", "success"}}, {{"", ""}}}}, 2, 1},
  {"tos_state_resolver_results_total", "counter", "", {{{{"operation", "state"}}, {{"result", "failure"}}, {{"", ""}}}}, 2, 1},
  {"tos_state_resolver_results_total", "counter", "", {{{{"operation", "state"}}, {{"result", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_state_resolver_waiters", "gauge", "", {{{{"kind", "finalization"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_state_resolver_oldest_waiter_age_seconds", "gauge", "", {{{{"kind", "finalization"}}, {{"", ""}}, {{"", ""}}}}, 1, 1e-09},
  {"tos_state_resolver_results_total", "counter", "", {{{{"operation", "finalization"}}, {{"result", "success"}}, {{"", ""}}}}, 2, 1},
  {"tos_state_resolver_results_total", "counter", "", {{{{"operation", "finalization"}}, {{"result", "failure"}}, {{"", ""}}}}, 2, 1},
  {"tos_state_resolver_results_total", "counter", "", {{{{"operation", "finalization"}}, {{"result", "cancelled"}}, {{"", ""}}}}, 2, 1},
  {"tos_consensus_current_slot", "gauge", "", {{{{"scope", "masterchain"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_consensus_last_finalized_slot", "gauge", "", {{{{"scope", "masterchain"}}, {{"", ""}}, {{"", ""}}}}, 1, 1},
  {"tos_diagnostic_dropped_total", "counter", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_diagnostic_sampled_out_total", "counter", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_diagnostic_queue_records", "gauge", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_diagnostic_queue_bytes", "gauge", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_diagnostic_sent_total", "counter", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_diagnostic_enabled", "gauge", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
  {"tos_diagnostic_counter_complete", "gauge", "", {{{{"", ""}}, {{"", ""}}, {{"", ""}}}}, 0, 1},
}};
static_assert(consensus_metric_catalog.size() <= 256);
static_assert([] {
  for (const auto &descriptor : consensus_metric_catalog) {
    if (descriptor.name == nullptr || descriptor.type == nullptr || descriptor.suffix == nullptr ||
        descriptor.label_count > descriptor.labels.size()) return false;
    for (const auto &label : descriptor.labels)
      if (label[0] == nullptr || label[1] == nullptr) return false;
  }
  return true;
}(), "Frozen metric catalog requires non-null strings and bounded labels");
}  // namespace tos::health
