// Generated by tools/validator-auth/generate.py.
pub const VALIDATOR_AUTH_PROFILE_FINGERPRINT: [u8; 32] = [
    155, 17, 133, 5, 171, 154, 63, 104, 17, 141, 197, 11, 81, 242, 116, 43, 61, 41, 202, 129, 198,
    190, 33, 92, 245, 75, 40, 244, 222, 131, 181, 104,
];
