// Generated by tools/validator-auth/generate.py.
pub const VALIDATOR_AUTH_PROFILE_FINGERPRINT: [u8; 32] = [
    254, 46, 143, 108, 249, 96, 36, 192, 229, 101, 90, 226, 40, 32, 13, 64, 153, 144, 199, 33, 23,
    81, 179, 20, 155, 146, 238, 72, 99, 79, 74, 26,
];
